// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package order

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// AlpacaServiceClient is the client API for AlpacaService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type AlpacaServiceClient interface {
	CreateAlpacaOrder(ctx context.Context, in *AlpacaOrderDetails, opts ...grpc.CallOption) (*emptypb.Empty, error)
	// rpc Get(Filter) returns (Records) {}
	UpdateAlpacaOrder(ctx context.Context, in *AlpacaOrderDetails, opts ...grpc.CallOption) (*emptypb.Empty, error)
}

type alpacaServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewAlpacaServiceClient(cc grpc.ClientConnInterface) AlpacaServiceClient {
	return &alpacaServiceClient{cc}
}

func (c *alpacaServiceClient) CreateAlpacaOrder(ctx context.Context, in *AlpacaOrderDetails, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, "/order.AlpacaService/CreateAlpacaOrder", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *alpacaServiceClient) UpdateAlpacaOrder(ctx context.Context, in *AlpacaOrderDetails, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, "/order.AlpacaService/UpdateAlpacaOrder", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AlpacaServiceServer is the server API for AlpacaService service.
// All implementations should embed UnimplementedAlpacaServiceServer
// for forward compatibility
type AlpacaServiceServer interface {
	CreateAlpacaOrder(context.Context, *AlpacaOrderDetails) (*emptypb.Empty, error)
	// rpc Get(Filter) returns (Records) {}
	UpdateAlpacaOrder(context.Context, *AlpacaOrderDetails) (*emptypb.Empty, error)
}

// UnimplementedAlpacaServiceServer should be embedded to have forward compatible implementations.
type UnimplementedAlpacaServiceServer struct {
}

func (UnimplementedAlpacaServiceServer) CreateAlpacaOrder(context.Context, *AlpacaOrderDetails) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateAlpacaOrder not implemented")
}
func (UnimplementedAlpacaServiceServer) UpdateAlpacaOrder(context.Context, *AlpacaOrderDetails) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateAlpacaOrder not implemented")
}

// UnsafeAlpacaServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AlpacaServiceServer will
// result in compilation errors.
type UnsafeAlpacaServiceServer interface {
	mustEmbedUnimplementedAlpacaServiceServer()
}

func RegisterAlpacaServiceServer(s grpc.ServiceRegistrar, srv AlpacaServiceServer) {
	s.RegisterService(&AlpacaService_ServiceDesc, srv)
}

func _AlpacaService_CreateAlpacaOrder_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AlpacaOrderDetails)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AlpacaServiceServer).CreateAlpacaOrder(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/order.AlpacaService/CreateAlpacaOrder",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AlpacaServiceServer).CreateAlpacaOrder(ctx, req.(*AlpacaOrderDetails))
	}
	return interceptor(ctx, in, info, handler)
}

func _AlpacaService_UpdateAlpacaOrder_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AlpacaOrderDetails)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AlpacaServiceServer).UpdateAlpacaOrder(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/order.AlpacaService/UpdateAlpacaOrder",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AlpacaServiceServer).UpdateAlpacaOrder(ctx, req.(*AlpacaOrderDetails))
	}
	return interceptor(ctx, in, info, handler)
}

// AlpacaService_ServiceDesc is the grpc.ServiceDesc for AlpacaService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var AlpacaService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "order.AlpacaService",
	HandlerType: (*AlpacaServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateAlpacaOrder",
			Handler:    _AlpacaService_CreateAlpacaOrder_Handler,
		},
		{
			MethodName: "UpdateAlpacaOrder",
			Handler:    _AlpacaService_UpdateAlpacaOrder_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "alpaca-grpc.proto",
}
