// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             v4.24.3
// source: alpaca-grpc.proto

package transaction

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	AlpacaTrades_Create_FullMethodName = "/transaction.AlpacaTrades/Create"
	AlpacaTrades_Update_FullMethodName = "/transaction.AlpacaTrades/Update"
)

// AlpacaTradesClient is the client API for AlpacaTrades service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type AlpacaTradesClient interface {
	Create(ctx context.Context, in *AlpacaOrderDetails, opts ...grpc.CallOption) (*emptypb.Empty, error)
	// rpc Get(Filter) returns (Records) {}
	Update(ctx context.Context, in *AlpacaOrderDetails, opts ...grpc.CallOption) (*emptypb.Empty, error)
}

type alpacaTradesClient struct {
	cc grpc.ClientConnInterface
}

func NewAlpacaTradesClient(cc grpc.ClientConnInterface) AlpacaTradesClient {
	return &alpacaTradesClient{cc}
}

func (c *alpacaTradesClient) Create(ctx context.Context, in *AlpacaOrderDetails, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, AlpacaTrades_Create_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *alpacaTradesClient) Update(ctx context.Context, in *AlpacaOrderDetails, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, AlpacaTrades_Update_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AlpacaTradesServer is the server API for AlpacaTrades service.
// All implementations should embed UnimplementedAlpacaTradesServer
// for forward compatibility
type AlpacaTradesServer interface {
	Create(context.Context, *AlpacaOrderDetails) (*emptypb.Empty, error)
	// rpc Get(Filter) returns (Records) {}
	Update(context.Context, *AlpacaOrderDetails) (*emptypb.Empty, error)
}

// UnimplementedAlpacaTradesServer should be embedded to have forward compatible implementations.
type UnimplementedAlpacaTradesServer struct {
}

func (UnimplementedAlpacaTradesServer) Create(context.Context, *AlpacaOrderDetails) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Create not implemented")
}
func (UnimplementedAlpacaTradesServer) Update(context.Context, *AlpacaOrderDetails) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Update not implemented")
}

// UnsafeAlpacaTradesServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AlpacaTradesServer will
// result in compilation errors.
type UnsafeAlpacaTradesServer interface {
	mustEmbedUnimplementedAlpacaTradesServer()
}

func RegisterAlpacaTradesServer(s grpc.ServiceRegistrar, srv AlpacaTradesServer) {
	s.RegisterService(&AlpacaTrades_ServiceDesc, srv)
}

func _AlpacaTrades_Create_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AlpacaOrderDetails)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AlpacaTradesServer).Create(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AlpacaTrades_Create_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AlpacaTradesServer).Create(ctx, req.(*AlpacaOrderDetails))
	}
	return interceptor(ctx, in, info, handler)
}

func _AlpacaTrades_Update_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AlpacaOrderDetails)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AlpacaTradesServer).Update(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AlpacaTrades_Update_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AlpacaTradesServer).Update(ctx, req.(*AlpacaOrderDetails))
	}
	return interceptor(ctx, in, info, handler)
}

// AlpacaTrades_ServiceDesc is the grpc.ServiceDesc for AlpacaTrades service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var AlpacaTrades_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "transaction.AlpacaTrades",
	HandlerType: (*AlpacaTradesServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Create",
			Handler:    _AlpacaTrades_Create_Handler,
		},
		{
			MethodName: "Update",
			Handler:    _AlpacaTrades_Update_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "alpaca-grpc.proto",
}
