// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             v5.29.0
// source: attestation-grpc.proto

package order

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	AttestationService_Create_FullMethodName = "/order.AttestationService/Create"
	AttestationService_Update_FullMethodName = "/order.AttestationService/Update"
	AttestationService_Get_FullMethodName    = "/order.AttestationService/Get"
	AttestationService_List_FullMethodName   = "/order.AttestationService/List"
)

// AttestationServiceClient is the client API for AttestationService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type AttestationServiceClient interface {
	Create(ctx context.Context, in *Attestation, opts ...grpc.CallOption) (*emptypb.Empty, error)
	Update(ctx context.Context, in *Attestation, opts ...grpc.CallOption) (*emptypb.Empty, error)
	Get(ctx context.Context, in *AttestationID, opts ...grpc.CallOption) (*Attestation, error)
	List(ctx context.Context, in *AttestationQuery, opts ...grpc.CallOption) (*Attestations, error)
}

type attestationServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewAttestationServiceClient(cc grpc.ClientConnInterface) AttestationServiceClient {
	return &attestationServiceClient{cc}
}

func (c *attestationServiceClient) Create(ctx context.Context, in *Attestation, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, AttestationService_Create_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *attestationServiceClient) Update(ctx context.Context, in *Attestation, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, AttestationService_Update_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *attestationServiceClient) Get(ctx context.Context, in *AttestationID, opts ...grpc.CallOption) (*Attestation, error) {
	out := new(Attestation)
	err := c.cc.Invoke(ctx, AttestationService_Get_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *attestationServiceClient) List(ctx context.Context, in *AttestationQuery, opts ...grpc.CallOption) (*Attestations, error) {
	out := new(Attestations)
	err := c.cc.Invoke(ctx, AttestationService_List_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AttestationServiceServer is the server API for AttestationService service.
// All implementations should embed UnimplementedAttestationServiceServer
// for forward compatibility
type AttestationServiceServer interface {
	Create(context.Context, *Attestation) (*emptypb.Empty, error)
	Update(context.Context, *Attestation) (*emptypb.Empty, error)
	Get(context.Context, *AttestationID) (*Attestation, error)
	List(context.Context, *AttestationQuery) (*Attestations, error)
}

// UnimplementedAttestationServiceServer should be embedded to have forward compatible implementations.
type UnimplementedAttestationServiceServer struct {
}

func (UnimplementedAttestationServiceServer) Create(context.Context, *Attestation) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Create not implemented")
}
func (UnimplementedAttestationServiceServer) Update(context.Context, *Attestation) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Update not implemented")
}
func (UnimplementedAttestationServiceServer) Get(context.Context, *AttestationID) (*Attestation, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Get not implemented")
}
func (UnimplementedAttestationServiceServer) List(context.Context, *AttestationQuery) (*Attestations, error) {
	return nil, status.Errorf(codes.Unimplemented, "method List not implemented")
}

// UnsafeAttestationServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AttestationServiceServer will
// result in compilation errors.
type UnsafeAttestationServiceServer interface {
	mustEmbedUnimplementedAttestationServiceServer()
}

func RegisterAttestationServiceServer(s grpc.ServiceRegistrar, srv AttestationServiceServer) {
	s.RegisterService(&AttestationService_ServiceDesc, srv)
}

func _AttestationService_Create_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Attestation)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AttestationServiceServer).Create(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AttestationService_Create_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AttestationServiceServer).Create(ctx, req.(*Attestation))
	}
	return interceptor(ctx, in, info, handler)
}

func _AttestationService_Update_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Attestation)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AttestationServiceServer).Update(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AttestationService_Update_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AttestationServiceServer).Update(ctx, req.(*Attestation))
	}
	return interceptor(ctx, in, info, handler)
}

func _AttestationService_Get_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AttestationID)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AttestationServiceServer).Get(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AttestationService_Get_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AttestationServiceServer).Get(ctx, req.(*AttestationID))
	}
	return interceptor(ctx, in, info, handler)
}

func _AttestationService_List_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AttestationQuery)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AttestationServiceServer).List(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AttestationService_List_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AttestationServiceServer).List(ctx, req.(*AttestationQuery))
	}
	return interceptor(ctx, in, info, handler)
}

// AttestationService_ServiceDesc is the grpc.ServiceDesc for AttestationService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var AttestationService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "order.AttestationService",
	HandlerType: (*AttestationServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Create",
			Handler:    _AttestationService_Create_Handler,
		},
		{
			MethodName: "Update",
			Handler:    _AttestationService_Update_Handler,
		},
		{
			MethodName: "Get",
			Handler:    _AttestationService_Get_Handler,
		},
		{
			MethodName: "List",
			Handler:    _AttestationService_List_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "attestation-grpc.proto",
}
