// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: sologenic/com-fs-order-model/attestation-grpc.proto

package order

import (
	metadata "github.com/sologenic/com-fs-utils-lib/models/metadata"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type AttestationID struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	Network           metadata.Network       `protobuf:"varint,1,opt,name=Network,proto3,enum=metadata.Network" json:"Network,omitempty"`
	SmartContractAddr string                 `protobuf:"bytes,2,opt,name=SmartContractAddr,proto3" json:"SmartContractAddr,omitempty"`
	Denom             string                 `protobuf:"bytes,3,opt,name=Denom,proto3" json:"Denom,omitempty"`
	BlockHeight       *int64                 `protobuf:"varint,4,opt,name=BlockHeight,proto3,oneof" json:"BlockHeight,omitempty"` // Default will return the latest attestation
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *AttestationID) Reset() {
	*x = AttestationID{}
	mi := &file_sologenic_com_fs_order_model_attestation_grpc_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AttestationID) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AttestationID) ProtoMessage() {}

func (x *AttestationID) ProtoReflect() protoreflect.Message {
	mi := &file_sologenic_com_fs_order_model_attestation_grpc_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AttestationID.ProtoReflect.Descriptor instead.
func (*AttestationID) Descriptor() ([]byte, []int) {
	return file_sologenic_com_fs_order_model_attestation_grpc_proto_rawDescGZIP(), []int{0}
}

func (x *AttestationID) GetNetwork() metadata.Network {
	if x != nil {
		return x.Network
	}
	return metadata.Network(0)
}

func (x *AttestationID) GetSmartContractAddr() string {
	if x != nil {
		return x.SmartContractAddr
	}
	return ""
}

func (x *AttestationID) GetDenom() string {
	if x != nil {
		return x.Denom
	}
	return ""
}

func (x *AttestationID) GetBlockHeight() int64 {
	if x != nil && x.BlockHeight != nil {
		return *x.BlockHeight
	}
	return 0
}

type AttestationQuery struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	Network           metadata.Network       `protobuf:"varint,1,opt,name=Network,proto3,enum=metadata.Network" json:"Network,omitempty"`
	SmartContractAddr string                 `protobuf:"bytes,2,opt,name=SmartContractAddr,proto3" json:"SmartContractAddr,omitempty"`
	Denom             string                 `protobuf:"bytes,3,opt,name=Denom,proto3" json:"Denom,omitempty"`
	Offset            *int32                 `protobuf:"varint,5,opt,name=Offset,proto3,oneof" json:"Offset,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *AttestationQuery) Reset() {
	*x = AttestationQuery{}
	mi := &file_sologenic_com_fs_order_model_attestation_grpc_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AttestationQuery) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AttestationQuery) ProtoMessage() {}

func (x *AttestationQuery) ProtoReflect() protoreflect.Message {
	mi := &file_sologenic_com_fs_order_model_attestation_grpc_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AttestationQuery.ProtoReflect.Descriptor instead.
func (*AttestationQuery) Descriptor() ([]byte, []int) {
	return file_sologenic_com_fs_order_model_attestation_grpc_proto_rawDescGZIP(), []int{1}
}

func (x *AttestationQuery) GetNetwork() metadata.Network {
	if x != nil {
		return x.Network
	}
	return metadata.Network(0)
}

func (x *AttestationQuery) GetSmartContractAddr() string {
	if x != nil {
		return x.SmartContractAddr
	}
	return ""
}

func (x *AttestationQuery) GetDenom() string {
	if x != nil {
		return x.Denom
	}
	return ""
}

func (x *AttestationQuery) GetOffset() int32 {
	if x != nil && x.Offset != nil {
		return *x.Offset
	}
	return 0
}

var File_sologenic_com_fs_order_model_attestation_grpc_proto protoreflect.FileDescriptor

const file_sologenic_com_fs_order_model_attestation_grpc_proto_rawDesc = "" +
	"\n" +
	"3sologenic/com-fs-order-model/attestation-grpc.proto\x12\x05order\x1a\x1bgoogle/protobuf/empty.proto\x1a.sologenic/com-fs-order-model/attestation.proto\x1a9sologenic/com-fs-utils-lib/models/metadata/metadata.proto\"\xb7\x01\n" +
	"\rAttestationID\x12+\n" +
	"\aNetwork\x18\x01 \x01(\x0e2\x11.metadata.NetworkR\aNetwork\x12,\n" +
	"\x11SmartContractAddr\x18\x02 \x01(\tR\x11SmartContractAddr\x12\x14\n" +
	"\x05Denom\x18\x03 \x01(\tR\x05Denom\x12%\n" +
	"\vBlockHeight\x18\x04 \x01(\x03H\x00R\vBlockHeight\x88\x01\x01B\x0e\n" +
	"\f_BlockHeight\"\xab\x01\n" +
	"\x10AttestationQuery\x12+\n" +
	"\aNetwork\x18\x01 \x01(\x0e2\x11.metadata.NetworkR\aNetwork\x12,\n" +
	"\x11SmartContractAddr\x18\x02 \x01(\tR\x11SmartContractAddr\x12\x14\n" +
	"\x05Denom\x18\x03 \x01(\tR\x05Denom\x12\x1b\n" +
	"\x06Offset\x18\x05 \x01(\x05H\x00R\x06Offset\x88\x01\x01B\t\n" +
	"\a_Offset2\xef\x01\n" +
	"\x12AttestationService\x126\n" +
	"\x06Create\x12\x12.order.Attestation\x1a\x16.google.protobuf.Empty\"\x00\x126\n" +
	"\x06Update\x12\x12.order.Attestation\x1a\x16.google.protobuf.Empty\"\x00\x121\n" +
	"\x03Get\x12\x14.order.AttestationID\x1a\x12.order.Attestation\"\x00\x126\n" +
	"\x04List\x12\x17.order.AttestationQuery\x1a\x13.order.Attestations\"\x00B/Z-github.com/sologenic/com-fs-order-model;orderb\x06proto3"

var (
	file_sologenic_com_fs_order_model_attestation_grpc_proto_rawDescOnce sync.Once
	file_sologenic_com_fs_order_model_attestation_grpc_proto_rawDescData []byte
)

func file_sologenic_com_fs_order_model_attestation_grpc_proto_rawDescGZIP() []byte {
	file_sologenic_com_fs_order_model_attestation_grpc_proto_rawDescOnce.Do(func() {
		file_sologenic_com_fs_order_model_attestation_grpc_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_sologenic_com_fs_order_model_attestation_grpc_proto_rawDesc), len(file_sologenic_com_fs_order_model_attestation_grpc_proto_rawDesc)))
	})
	return file_sologenic_com_fs_order_model_attestation_grpc_proto_rawDescData
}

var file_sologenic_com_fs_order_model_attestation_grpc_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_sologenic_com_fs_order_model_attestation_grpc_proto_goTypes = []any{
	(*AttestationID)(nil),    // 0: order.AttestationID
	(*AttestationQuery)(nil), // 1: order.AttestationQuery
	(metadata.Network)(0),    // 2: metadata.Network
	(*Attestation)(nil),      // 3: order.Attestation
	(*emptypb.Empty)(nil),    // 4: google.protobuf.Empty
	(*Attestations)(nil),     // 5: order.Attestations
}
var file_sologenic_com_fs_order_model_attestation_grpc_proto_depIdxs = []int32{
	2, // 0: order.AttestationID.Network:type_name -> metadata.Network
	2, // 1: order.AttestationQuery.Network:type_name -> metadata.Network
	3, // 2: order.AttestationService.Create:input_type -> order.Attestation
	3, // 3: order.AttestationService.Update:input_type -> order.Attestation
	0, // 4: order.AttestationService.Get:input_type -> order.AttestationID
	1, // 5: order.AttestationService.List:input_type -> order.AttestationQuery
	4, // 6: order.AttestationService.Create:output_type -> google.protobuf.Empty
	4, // 7: order.AttestationService.Update:output_type -> google.protobuf.Empty
	3, // 8: order.AttestationService.Get:output_type -> order.Attestation
	5, // 9: order.AttestationService.List:output_type -> order.Attestations
	6, // [6:10] is the sub-list for method output_type
	2, // [2:6] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_sologenic_com_fs_order_model_attestation_grpc_proto_init() }
func file_sologenic_com_fs_order_model_attestation_grpc_proto_init() {
	if File_sologenic_com_fs_order_model_attestation_grpc_proto != nil {
		return
	}
	file_sologenic_com_fs_order_model_attestation_proto_init()
	file_sologenic_com_fs_order_model_attestation_grpc_proto_msgTypes[0].OneofWrappers = []any{}
	file_sologenic_com_fs_order_model_attestation_grpc_proto_msgTypes[1].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_sologenic_com_fs_order_model_attestation_grpc_proto_rawDesc), len(file_sologenic_com_fs_order_model_attestation_grpc_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_sologenic_com_fs_order_model_attestation_grpc_proto_goTypes,
		DependencyIndexes: file_sologenic_com_fs_order_model_attestation_grpc_proto_depIdxs,
		MessageInfos:      file_sologenic_com_fs_order_model_attestation_grpc_proto_msgTypes,
	}.Build()
	File_sologenic_com_fs_order_model_attestation_grpc_proto = out.File
	file_sologenic_com_fs_order_model_attestation_grpc_proto_goTypes = nil
	file_sologenic_com_fs_order_model_attestation_grpc_proto_depIdxs = nil
}
