// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.30.2
// source: attestation.proto

package order

import (
	decimal "github.com/sologenic/com-fs-utils-lib/go/decimal"
	metadata "github.com/sologenic/com-fs-utils-lib/models/metadata"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// key: Denom-SmartContractAddr-Network-BlockHeight
type Attestation struct {
	state                    protoimpl.MessageState `protogen:"open.v1"`
	Network                  metadata.Network       `protobuf:"varint,1,opt,name=Network,proto3,enum=metadata.Network" json:"Network,omitempty"`
	SmartContractAddr        string                 `protobuf:"bytes,2,opt,name=SmartContractAddr,proto3" json:"SmartContractAddr,omitempty"`
	Denom                    string                 `protobuf:"bytes,3,opt,name=Denom,proto3" json:"Denom,omitempty"`
	BrokerQuantity           *decimal.Decimal       `protobuf:"bytes,4,opt,name=BrokerQuantity,proto3,oneof" json:"BrokerQuantity,omitempty"`
	ChainQuantity            *decimal.Decimal       `protobuf:"bytes,5,opt,name=ChainQuantity,proto3" json:"ChainQuantity,omitempty"`
	BlockHeight              int64                  `protobuf:"varint,6,opt,name=BlockHeight,proto3" json:"BlockHeight,omitempty"`
	Timestamp                *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=Timestamp,proto3" json:"Timestamp,omitempty"`
	ReattestationBlockHeight *int64                 `protobuf:"varint,8,opt,name=ReattestationBlockHeight,proto3,oneof" json:"ReattestationBlockHeight,omitempty"`
	unknownFields            protoimpl.UnknownFields
	sizeCache                protoimpl.SizeCache
}

func (x *Attestation) Reset() {
	*x = Attestation{}
	mi := &file_attestation_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Attestation) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Attestation) ProtoMessage() {}

func (x *Attestation) ProtoReflect() protoreflect.Message {
	mi := &file_attestation_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Attestation.ProtoReflect.Descriptor instead.
func (*Attestation) Descriptor() ([]byte, []int) {
	return file_attestation_proto_rawDescGZIP(), []int{0}
}

func (x *Attestation) GetNetwork() metadata.Network {
	if x != nil {
		return x.Network
	}
	return metadata.Network(0)
}

func (x *Attestation) GetSmartContractAddr() string {
	if x != nil {
		return x.SmartContractAddr
	}
	return ""
}

func (x *Attestation) GetDenom() string {
	if x != nil {
		return x.Denom
	}
	return ""
}

func (x *Attestation) GetBrokerQuantity() *decimal.Decimal {
	if x != nil {
		return x.BrokerQuantity
	}
	return nil
}

func (x *Attestation) GetChainQuantity() *decimal.Decimal {
	if x != nil {
		return x.ChainQuantity
	}
	return nil
}

func (x *Attestation) GetBlockHeight() int64 {
	if x != nil {
		return x.BlockHeight
	}
	return 0
}

func (x *Attestation) GetTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

func (x *Attestation) GetReattestationBlockHeight() int64 {
	if x != nil && x.ReattestationBlockHeight != nil {
		return *x.ReattestationBlockHeight
	}
	return 0
}

type Attestations struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Attestations  []*Attestation         `protobuf:"bytes,1,rep,name=Attestations,proto3" json:"Attestations,omitempty"`
	Offset        *int32                 `protobuf:"varint,2,opt,name=Offset,proto3,oneof" json:"Offset,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Attestations) Reset() {
	*x = Attestations{}
	mi := &file_attestation_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Attestations) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Attestations) ProtoMessage() {}

func (x *Attestations) ProtoReflect() protoreflect.Message {
	mi := &file_attestation_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Attestations.ProtoReflect.Descriptor instead.
func (*Attestations) Descriptor() ([]byte, []int) {
	return file_attestation_proto_rawDescGZIP(), []int{1}
}

func (x *Attestations) GetAttestations() []*Attestation {
	if x != nil {
		return x.Attestations
	}
	return nil
}

func (x *Attestations) GetOffset() int32 {
	if x != nil && x.Offset != nil {
		return *x.Offset
	}
	return 0
}

var File_attestation_proto protoreflect.FileDescriptor

const file_attestation_proto_rawDesc = "" +
	"\n" +
	"\x11attestation.proto\x12\x05order\x1a\x1fgoogle/protobuf/timestamp.proto\x1a3sologenic/com-fs-utils-lib/go/decimal/decimal.proto\x1a9sologenic/com-fs-utils-lib/models/metadata/metadata.proto\"\xc2\x03\n" +
	"\vAttestation\x12+\n" +
	"\aNetwork\x18\x01 \x01(\x0e2\x11.metadata.NetworkR\aNetwork\x12,\n" +
	"\x11SmartContractAddr\x18\x02 \x01(\tR\x11SmartContractAddr\x12\x14\n" +
	"\x05Denom\x18\x03 \x01(\tR\x05Denom\x12=\n" +
	"\x0eBrokerQuantity\x18\x04 \x01(\v2\x10.decimal.DecimalH\x00R\x0eBrokerQuantity\x88\x01\x01\x126\n" +
	"\rChainQuantity\x18\x05 \x01(\v2\x10.decimal.DecimalR\rChainQuantity\x12 \n" +
	"\vBlockHeight\x18\x06 \x01(\x03R\vBlockHeight\x128\n" +
	"\tTimestamp\x18\a \x01(\v2\x1a.google.protobuf.TimestampR\tTimestamp\x12?\n" +
	"\x18ReattestationBlockHeight\x18\b \x01(\x03H\x01R\x18ReattestationBlockHeight\x88\x01\x01B\x11\n" +
	"\x0f_BrokerQuantityB\x1b\n" +
	"\x19_ReattestationBlockHeight\"n\n" +
	"\fAttestations\x126\n" +
	"\fAttestations\x18\x01 \x03(\v2\x12.order.AttestationR\fAttestations\x12\x1b\n" +
	"\x06Offset\x18\x02 \x01(\x05H\x00R\x06Offset\x88\x01\x01B\t\n" +
	"\a_OffsetB/Z-github.com/sologenic/com-fs-order-model;orderb\x06proto3"

var (
	file_attestation_proto_rawDescOnce sync.Once
	file_attestation_proto_rawDescData []byte
)

func file_attestation_proto_rawDescGZIP() []byte {
	file_attestation_proto_rawDescOnce.Do(func() {
		file_attestation_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_attestation_proto_rawDesc), len(file_attestation_proto_rawDesc)))
	})
	return file_attestation_proto_rawDescData
}

var file_attestation_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_attestation_proto_goTypes = []any{
	(*Attestation)(nil),           // 0: order.Attestation
	(*Attestations)(nil),          // 1: order.Attestations
	(metadata.Network)(0),         // 2: metadata.Network
	(*decimal.Decimal)(nil),       // 3: decimal.Decimal
	(*timestamppb.Timestamp)(nil), // 4: google.protobuf.Timestamp
}
var file_attestation_proto_depIdxs = []int32{
	2, // 0: order.Attestation.Network:type_name -> metadata.Network
	3, // 1: order.Attestation.BrokerQuantity:type_name -> decimal.Decimal
	3, // 2: order.Attestation.ChainQuantity:type_name -> decimal.Decimal
	4, // 3: order.Attestation.Timestamp:type_name -> google.protobuf.Timestamp
	0, // 4: order.Attestations.Attestations:type_name -> order.Attestation
	5, // [5:5] is the sub-list for method output_type
	5, // [5:5] is the sub-list for method input_type
	5, // [5:5] is the sub-list for extension type_name
	5, // [5:5] is the sub-list for extension extendee
	0, // [0:5] is the sub-list for field type_name
}

func init() { file_attestation_proto_init() }
func file_attestation_proto_init() {
	if File_attestation_proto != nil {
		return
	}
	file_attestation_proto_msgTypes[0].OneofWrappers = []any{}
	file_attestation_proto_msgTypes[1].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_attestation_proto_rawDesc), len(file_attestation_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_attestation_proto_goTypes,
		DependencyIndexes: file_attestation_proto_depIdxs,
		MessageInfos:      file_attestation_proto_msgTypes,
	}.Build()
	File_attestation_proto = out.File
	file_attestation_proto_goTypes = nil
	file_attestation_proto_depIdxs = nil
}
