syntax = "proto3";

package order;

option go_package = "github.com/sologenic/com-fs-order-model;order";

import "google/protobuf/timestamp.proto";
import "sologenic/com-fs-utils-lib/models/decimal/decimal.proto";
import "sologenic/com-fs-utils-lib/models/metadata/metadata.proto";

// key: Denom-SmartContractAddr-Network-BlockHeight
message Attestation {
    metadata.Network Network = 1;
    string SmartContractAddr = 2;
    string Denom = 3;
    optional decimal.Decimal BrokerQuantity = 4; 
    decimal.Decimal ChainQuantity = 5;
    int64 BlockHeight = 6;
    google.protobuf.Timestamp Timestamp = 7;
    optional int64 ReattestationBlockHeight = 8;
}

message Attestations {
    repeated Attestation Attestations = 1;
    optional int32 Offset = 2;
}