// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: broker.proto

package order

import (
	decimal "github.com/sologenic/com-fs-utils-lib/go/decimal"
	metadata "github.com/sologenic/com-fs-utils-lib/models/metadata"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type AssetClass int32

const (
	AssetClass_NOT_USED_ASSET_CLASS AssetClass = 0
	AssetClass_US_EQUITY            AssetClass = 1
	AssetClass_CRYPTO               AssetClass = 2
)

// Enum value maps for AssetClass.
var (
	AssetClass_name = map[int32]string{
		0: "NOT_USED_ASSET_CLASS",
		1: "US_EQUITY",
		2: "CRYPTO",
	}
	AssetClass_value = map[string]int32{
		"NOT_USED_ASSET_CLASS": 0,
		"US_EQUITY":            1,
		"CRYPTO":               2,
	}
)

func (x AssetClass) Enum() *AssetClass {
	p := new(AssetClass)
	*p = x
	return p
}

func (x AssetClass) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (AssetClass) Descriptor() protoreflect.EnumDescriptor {
	return file_broker_proto_enumTypes[0].Descriptor()
}

func (AssetClass) Type() protoreflect.EnumType {
	return &file_broker_proto_enumTypes[0]
}

func (x AssetClass) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use AssetClass.Descriptor instead.
func (AssetClass) EnumDescriptor() ([]byte, []int) {
	return file_broker_proto_rawDescGZIP(), []int{0}
}

type TimeInForce int32

const (
	TimeInForce_NOT_USED_TIME_IN_FORCE TimeInForce = 0
	TimeInForce_DAY                    TimeInForce = 1
	TimeInForce_GTC                    TimeInForce = 2
	TimeInForce_GTT                    TimeInForce = 3
	// TODO: the below types will be implemented in the future
	TimeInForce_OPG TimeInForce = 4
	TimeInForce_CLS TimeInForce = 5
	TimeInForce_IOC TimeInForce = 6
	TimeInForce_FOK TimeInForce = 7
)

// Enum value maps for TimeInForce.
var (
	TimeInForce_name = map[int32]string{
		0: "NOT_USED_TIME_IN_FORCE",
		1: "DAY",
		2: "GTC",
		3: "GTT",
		4: "OPG",
		5: "CLS",
		6: "IOC",
		7: "FOK",
	}
	TimeInForce_value = map[string]int32{
		"NOT_USED_TIME_IN_FORCE": 0,
		"DAY":                    1,
		"GTC":                    2,
		"GTT":                    3,
		"OPG":                    4,
		"CLS":                    5,
		"IOC":                    6,
		"FOK":                    7,
	}
)

func (x TimeInForce) Enum() *TimeInForce {
	p := new(TimeInForce)
	*p = x
	return p
}

func (x TimeInForce) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (TimeInForce) Descriptor() protoreflect.EnumDescriptor {
	return file_broker_proto_enumTypes[1].Descriptor()
}

func (TimeInForce) Type() protoreflect.EnumType {
	return &file_broker_proto_enumTypes[1]
}

func (x TimeInForce) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use TimeInForce.Descriptor instead.
func (TimeInForce) EnumDescriptor() ([]byte, []int) {
	return file_broker_proto_rawDescGZIP(), []int{1}
}

type TradeType int32

const (
	TradeType_NOT_USED_TRADE_TYPE TradeType = 0
	TradeType_MARKET              TradeType = 1
	TradeType_LIMIT               TradeType = 2
	// TODO: the below types will be implemented in the future
	TradeType_STOP               TradeType = 3
	TradeType_STOP_LIMIT         TradeType = 4
	TradeType_OPEN_CLOSE_AUCTION TradeType = 5
	TradeType_BRACKET            TradeType = 6
	TradeType_OCO                TradeType = 7 // One-Cancels-Other
	TradeType_OTO                TradeType = 8 // One-Triggers-Other
	TradeType_TRAILING_STOP      TradeType = 9
)

// Enum value maps for TradeType.
var (
	TradeType_name = map[int32]string{
		0: "NOT_USED_TRADE_TYPE",
		1: "MARKET",
		2: "LIMIT",
		3: "STOP",
		4: "STOP_LIMIT",
		5: "OPEN_CLOSE_AUCTION",
		6: "BRACKET",
		7: "OCO",
		8: "OTO",
		9: "TRAILING_STOP",
	}
	TradeType_value = map[string]int32{
		"NOT_USED_TRADE_TYPE": 0,
		"MARKET":              1,
		"LIMIT":               2,
		"STOP":                3,
		"STOP_LIMIT":          4,
		"OPEN_CLOSE_AUCTION":  5,
		"BRACKET":             6,
		"OCO":                 7,
		"OTO":                 8,
		"TRAILING_STOP":       9,
	}
)

func (x TradeType) Enum() *TradeType {
	p := new(TradeType)
	*p = x
	return p
}

func (x TradeType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (TradeType) Descriptor() protoreflect.EnumDescriptor {
	return file_broker_proto_enumTypes[2].Descriptor()
}

func (TradeType) Type() protoreflect.EnumType {
	return &file_broker_proto_enumTypes[2]
}

func (x TradeType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use TradeType.Descriptor instead.
func (TradeType) EnumDescriptor() ([]byte, []int) {
	return file_broker_proto_rawDescGZIP(), []int{2}
}

type OrderClass int32

const (
	OrderClass_NOT_USED_ORDER_CLASS OrderClass = 0
	OrderClass_ORDER_CLASS_SIMPLE   OrderClass = 1
	OrderClass_ORDER_CLASS_BRACKET  OrderClass = 2
	OrderClass_ORDER_CLASS_OCO      OrderClass = 3 // One-Cancels-Other
	OrderClass_ORDER_CLASS_OTO      OrderClass = 4 // One-Triggers-Other
)

// Enum value maps for OrderClass.
var (
	OrderClass_name = map[int32]string{
		0: "NOT_USED_ORDER_CLASS",
		1: "ORDER_CLASS_SIMPLE",
		2: "ORDER_CLASS_BRACKET",
		3: "ORDER_CLASS_OCO",
		4: "ORDER_CLASS_OTO",
	}
	OrderClass_value = map[string]int32{
		"NOT_USED_ORDER_CLASS": 0,
		"ORDER_CLASS_SIMPLE":   1,
		"ORDER_CLASS_BRACKET":  2,
		"ORDER_CLASS_OCO":      3,
		"ORDER_CLASS_OTO":      4,
	}
)

func (x OrderClass) Enum() *OrderClass {
	p := new(OrderClass)
	*p = x
	return p
}

func (x OrderClass) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (OrderClass) Descriptor() protoreflect.EnumDescriptor {
	return file_broker_proto_enumTypes[3].Descriptor()
}

func (OrderClass) Type() protoreflect.EnumType {
	return &file_broker_proto_enumTypes[3]
}

func (x OrderClass) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use OrderClass.Descriptor instead.
func (OrderClass) EnumDescriptor() ([]byte, []int) {
	return file_broker_proto_rawDescGZIP(), []int{3}
}

type BrokerOrderStatus int32

const (
	BrokerOrderStatus_NOT_USED_ALPACA_ORDER_STATUS BrokerOrderStatus = 0
	// common statuses
	BrokerOrderStatus_PENDING_NEW      BrokerOrderStatus = 1 // the order has been received by Alpaca, and routed to the exchanges, but has not yet been accepted for execution.
	BrokerOrderStatus_NEW              BrokerOrderStatus = 2 // the order has been received by Alpaca, and routed to exchanges for execution.
	BrokerOrderStatus_PARTIALLY_FILLED BrokerOrderStatus = 3 // the order has been partially filled.
	BrokerOrderStatus_FILLED           BrokerOrderStatus = 4 // the order has been filled, and no further updates will occur for the order.
	BrokerOrderStatus_DONE_FOR_DAY     BrokerOrderStatus = 5 // the order is done executing for the day, and will not receive further updates until the next trading day.
	BrokerOrderStatus_CANCELED         BrokerOrderStatus = 6 // the order has been canceled, and no further updates will occur for the order. This can be either due to a cancel request by the user, or the order has been canceled by the exchanges due to its time-in-force.
	BrokerOrderStatus_EXPIRED          BrokerOrderStatus = 7 // the order has expired, and no further updates will occur for the order.
	// uncommon statuses
	BrokerOrderStatus_PENDING_CANCEL       BrokerOrderStatus = 8  // the order is waiting to be canceled.
	BrokerOrderStatus_ACCEPTED             BrokerOrderStatus = 9  // the order has been received by Alpaca, but hasn’t yet been routed to the execution venue.
	BrokerOrderStatus_ACCEPTED_FOR_BIDDING BrokerOrderStatus = 10 // the order has been received by exchanges, and is evaluated for pricing.
	BrokerOrderStatus_STOPPED              BrokerOrderStatus = 11 // the order has been stopped, and a trade is guaranteed for the order, usually at a stated price or better, but has not yet occurred.
	BrokerOrderStatus_REJECTED             BrokerOrderStatus = 12 // the order has been rejected, and no further updates will occur for the order.
	BrokerOrderStatus_SUSPENDED            BrokerOrderStatus = 13 // the order has been suspended, and is not eligible for trading.
	BrokerOrderStatus_CALCULATED           BrokerOrderStatus = 14 // the order has been completed for the day (either filled or done for day), but remaining settlement calculations are still pending.
)

// Enum value maps for BrokerOrderStatus.
var (
	BrokerOrderStatus_name = map[int32]string{
		0:  "NOT_USED_ALPACA_ORDER_STATUS",
		1:  "PENDING_NEW",
		2:  "NEW",
		3:  "PARTIALLY_FILLED",
		4:  "FILLED",
		5:  "DONE_FOR_DAY",
		6:  "CANCELED",
		7:  "EXPIRED",
		8:  "PENDING_CANCEL",
		9:  "ACCEPTED",
		10: "ACCEPTED_FOR_BIDDING",
		11: "STOPPED",
		12: "REJECTED",
		13: "SUSPENDED",
		14: "CALCULATED",
	}
	BrokerOrderStatus_value = map[string]int32{
		"NOT_USED_ALPACA_ORDER_STATUS": 0,
		"PENDING_NEW":                  1,
		"NEW":                          2,
		"PARTIALLY_FILLED":             3,
		"FILLED":                       4,
		"DONE_FOR_DAY":                 5,
		"CANCELED":                     6,
		"EXPIRED":                      7,
		"PENDING_CANCEL":               8,
		"ACCEPTED":                     9,
		"ACCEPTED_FOR_BIDDING":         10,
		"STOPPED":                      11,
		"REJECTED":                     12,
		"SUSPENDED":                    13,
		"CALCULATED":                   14,
	}
)

func (x BrokerOrderStatus) Enum() *BrokerOrderStatus {
	p := new(BrokerOrderStatus)
	*p = x
	return p
}

func (x BrokerOrderStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (BrokerOrderStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_broker_proto_enumTypes[4].Descriptor()
}

func (BrokerOrderStatus) Type() protoreflect.EnumType {
	return &file_broker_proto_enumTypes[4]
}

func (x BrokerOrderStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use BrokerOrderStatus.Descriptor instead.
func (BrokerOrderStatus) EnumDescriptor() ([]byte, []int) {
	return file_broker_proto_rawDescGZIP(), []int{4}
}

// Key orderID-SmartContractAddr-network (is as unique identifier for the order in message to Alpaca)
type BrokerOrderDetails struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	BrokerAssignedID string                 `protobuf:"bytes,1,opt,name=BrokerAssignedID,proto3" json:"BrokerAssignedID,omitempty"` // auto generated ID from Alpaca
	ClientOrderID    *ClientOrderID         `protobuf:"bytes,2,opt,name=ClientOrderID,proto3" json:"ClientOrderID,omitempty"`       // unique identifier for the order in message to Alpaca, value is from the key function
	SubmittedAt      *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=SubmittedAt,proto3" json:"SubmittedAt,omitempty"`
	FilledAt         *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=FilledAt,proto3,oneof" json:"FilledAt,omitempty"`
	ExpiredAt        *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=ExpiredAt,proto3,oneof" json:"ExpiredAt,omitempty"`
	CancelledAt      *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=CancelledAt,proto3,oneof" json:"CancelledAt,omitempty"`
	FailedAt         *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=FailedAt,proto3,oneof" json:"FailedAt,omitempty"`
	AssetID          string                 `protobuf:"bytes,8,opt,name=AssetID,proto3" json:"AssetID,omitempty"`
	Symbol           string                 `protobuf:"bytes,9,opt,name=Symbol,proto3" json:"Symbol,omitempty"`
	AssetClass       AssetClass             `protobuf:"varint,10,opt,name=AssetClass,proto3,enum=order.AssetClass" json:"AssetClass,omitempty"`
	OrderClass       OrderClass             `protobuf:"varint,11,opt,name=OrderClass,proto3,enum=order.OrderClass" json:"OrderClass,omitempty"`
	Type             TradeType              `protobuf:"varint,12,opt,name=Type,proto3,enum=order.TradeType" json:"Type,omitempty"`
	Side             OrderType              `protobuf:"varint,13,opt,name=Side,proto3,enum=order.OrderType" json:"Side,omitempty"`
	TimeInForce      TimeInForce            `protobuf:"varint,14,opt,name=TimeInForce,proto3,enum=order.TimeInForce" json:"TimeInForce,omitempty"`
	// Notional and Qty are optional as one can be null if the other is present. However, both cannot be null or present at the same time.
	Notional       *decimal.Decimal       `protobuf:"bytes,15,opt,name=Notional,proto3,oneof" json:"Notional,omitempty"`
	OrderQty       *decimal.Decimal       `protobuf:"bytes,16,opt,name=OrderQty,proto3,oneof" json:"OrderQty,omitempty"`
	FilledQty      *decimal.Decimal       `protobuf:"bytes,17,opt,name=FilledQty,proto3" json:"FilledQty,omitempty"` // defaults to 0, updated as previous `FilledQty` + `PartialQty`
	FilledAvgPrice *decimal.Decimal       `protobuf:"bytes,18,opt,name=FilledAvgPrice,proto3,oneof" json:"FilledAvgPrice,omitempty"`
	LimitPrice     *decimal.Decimal       `protobuf:"bytes,19,opt,name=LimitPrice,proto3,oneof" json:"LimitPrice,omitempty"`
	StopPrice      *decimal.Decimal       `protobuf:"bytes,20,opt,name=StopPrice,proto3,oneof" json:"StopPrice,omitempty"`
	TrailPrice     *decimal.Decimal       `protobuf:"bytes,21,opt,name=TrailPrice,proto3,oneof" json:"TrailPrice,omitempty"`
	TrailPercent   *decimal.Decimal       `protobuf:"bytes,22,opt,name=TrailPercent,proto3,oneof" json:"TrailPercent,omitempty"`
	HWM            *decimal.Decimal       `protobuf:"bytes,23,opt,name=HWM,proto3,oneof" json:"HWM,omitempty"`                // High Water Mark, used for trailing stop orders
	ExtendedHours  bool                   `protobuf:"varint,24,opt,name=ExtendedHours,proto3" json:"ExtendedHours,omitempty"` // defaults to false
	CreatedAt      *timestamppb.Timestamp `protobuf:"bytes,25,opt,name=CreatedAt,proto3" json:"CreatedAt,omitempty"`
	UpdatedAt      *timestamppb.Timestamp `protobuf:"bytes,26,opt,name=UpdatedAt,proto3,oneof" json:"UpdatedAt,omitempty"`
	Status         BrokerOrderStatus      `protobuf:"varint,27,opt,name=Status,proto3,enum=order.BrokerOrderStatus" json:"Status,omitempty"` // status of the order in Alpaca
	// "position_qty" field from Alpaca Trade Update's event msg.
	// Since all orders will flow through Sologenic's custodial account, this will represent the total count of all shares on our platform.
	TotalPosition *decimal.Decimal `protobuf:"bytes,28,opt,name=TotalPosition,proto3,oneof" json:"TotalPosition,omitempty"`
	// "price" field from Alpaca Trade Update's event msg.
	// Represents the price of the order processed at the time of partial fill. For example, if a 3 step partial fill occurs for an order at prices $1, $1.1 and $0.9,
	// the `PartialPrice` will be $1, $1.1 and $0.9 respectively. The average of these prices will be the `FilledAvgPrice`.
	PartialPrice *decimal.Decimal `protobuf:"bytes,29,opt,name=PartialPrice,proto3,oneof" json:"PartialPrice,omitempty"`
	// "qty" field from Alpaca Trade Update's event msg.
	// Represents the partial order processed at the time of partial fill.
	// For example, if a order for 10 shares is partially filled with 5, 3 and 2 shares, the `PartialQty` will be 5, 3 and 2 respectively.
	PartialQty *decimal.Decimal `protobuf:"bytes,30,opt,name=PartialQty,proto3,oneof" json:"PartialQty,omitempty"`
	// Bookkeeping: did we process this event from alpaca order log?
	ProcessInfo   *ProcessInfo `protobuf:"bytes,31,opt,name=ProcessInfo,proto3,oneof" json:"ProcessInfo,omitempty"`
	InstanceID    *string      `protobuf:"bytes,32,opt,name=InstanceID,proto3,oneof" json:"InstanceID,omitempty"` // ID used by logs to identify the instance where the log was created/ processed
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BrokerOrderDetails) Reset() {
	*x = BrokerOrderDetails{}
	mi := &file_broker_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BrokerOrderDetails) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BrokerOrderDetails) ProtoMessage() {}

func (x *BrokerOrderDetails) ProtoReflect() protoreflect.Message {
	mi := &file_broker_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BrokerOrderDetails.ProtoReflect.Descriptor instead.
func (*BrokerOrderDetails) Descriptor() ([]byte, []int) {
	return file_broker_proto_rawDescGZIP(), []int{0}
}

func (x *BrokerOrderDetails) GetBrokerAssignedID() string {
	if x != nil {
		return x.BrokerAssignedID
	}
	return ""
}

func (x *BrokerOrderDetails) GetClientOrderID() *ClientOrderID {
	if x != nil {
		return x.ClientOrderID
	}
	return nil
}

func (x *BrokerOrderDetails) GetSubmittedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.SubmittedAt
	}
	return nil
}

func (x *BrokerOrderDetails) GetFilledAt() *timestamppb.Timestamp {
	if x != nil {
		return x.FilledAt
	}
	return nil
}

func (x *BrokerOrderDetails) GetExpiredAt() *timestamppb.Timestamp {
	if x != nil {
		return x.ExpiredAt
	}
	return nil
}

func (x *BrokerOrderDetails) GetCancelledAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CancelledAt
	}
	return nil
}

func (x *BrokerOrderDetails) GetFailedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.FailedAt
	}
	return nil
}

func (x *BrokerOrderDetails) GetAssetID() string {
	if x != nil {
		return x.AssetID
	}
	return ""
}

func (x *BrokerOrderDetails) GetSymbol() string {
	if x != nil {
		return x.Symbol
	}
	return ""
}

func (x *BrokerOrderDetails) GetAssetClass() AssetClass {
	if x != nil {
		return x.AssetClass
	}
	return AssetClass_NOT_USED_ASSET_CLASS
}

func (x *BrokerOrderDetails) GetOrderClass() OrderClass {
	if x != nil {
		return x.OrderClass
	}
	return OrderClass_NOT_USED_ORDER_CLASS
}

func (x *BrokerOrderDetails) GetType() TradeType {
	if x != nil {
		return x.Type
	}
	return TradeType_NOT_USED_TRADE_TYPE
}

func (x *BrokerOrderDetails) GetSide() OrderType {
	if x != nil {
		return x.Side
	}
	return OrderType_NOT_USED_ORDER_TYPE
}

func (x *BrokerOrderDetails) GetTimeInForce() TimeInForce {
	if x != nil {
		return x.TimeInForce
	}
	return TimeInForce_NOT_USED_TIME_IN_FORCE
}

func (x *BrokerOrderDetails) GetNotional() *decimal.Decimal {
	if x != nil {
		return x.Notional
	}
	return nil
}

func (x *BrokerOrderDetails) GetOrderQty() *decimal.Decimal {
	if x != nil {
		return x.OrderQty
	}
	return nil
}

func (x *BrokerOrderDetails) GetFilledQty() *decimal.Decimal {
	if x != nil {
		return x.FilledQty
	}
	return nil
}

func (x *BrokerOrderDetails) GetFilledAvgPrice() *decimal.Decimal {
	if x != nil {
		return x.FilledAvgPrice
	}
	return nil
}

func (x *BrokerOrderDetails) GetLimitPrice() *decimal.Decimal {
	if x != nil {
		return x.LimitPrice
	}
	return nil
}

func (x *BrokerOrderDetails) GetStopPrice() *decimal.Decimal {
	if x != nil {
		return x.StopPrice
	}
	return nil
}

func (x *BrokerOrderDetails) GetTrailPrice() *decimal.Decimal {
	if x != nil {
		return x.TrailPrice
	}
	return nil
}

func (x *BrokerOrderDetails) GetTrailPercent() *decimal.Decimal {
	if x != nil {
		return x.TrailPercent
	}
	return nil
}

func (x *BrokerOrderDetails) GetHWM() *decimal.Decimal {
	if x != nil {
		return x.HWM
	}
	return nil
}

func (x *BrokerOrderDetails) GetExtendedHours() bool {
	if x != nil {
		return x.ExtendedHours
	}
	return false
}

func (x *BrokerOrderDetails) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *BrokerOrderDetails) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

func (x *BrokerOrderDetails) GetStatus() BrokerOrderStatus {
	if x != nil {
		return x.Status
	}
	return BrokerOrderStatus_NOT_USED_ALPACA_ORDER_STATUS
}

func (x *BrokerOrderDetails) GetTotalPosition() *decimal.Decimal {
	if x != nil {
		return x.TotalPosition
	}
	return nil
}

func (x *BrokerOrderDetails) GetPartialPrice() *decimal.Decimal {
	if x != nil {
		return x.PartialPrice
	}
	return nil
}

func (x *BrokerOrderDetails) GetPartialQty() *decimal.Decimal {
	if x != nil {
		return x.PartialQty
	}
	return nil
}

func (x *BrokerOrderDetails) GetProcessInfo() *ProcessInfo {
	if x != nil {
		return x.ProcessInfo
	}
	return nil
}

func (x *BrokerOrderDetails) GetInstanceID() string {
	if x != nil && x.InstanceID != nil {
		return *x.InstanceID
	}
	return ""
}

type ClientOrderID struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	Network           metadata.Network       `protobuf:"varint,1,opt,name=Network,proto3,enum=metadata.Network" json:"Network,omitempty"`
	SmartContractAddr string                 `protobuf:"bytes,2,opt,name=SmartContractAddr,proto3" json:"SmartContractAddr,omitempty"`
	OrderID           int64                  `protobuf:"varint,3,opt,name=OrderID,proto3" json:"OrderID,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *ClientOrderID) Reset() {
	*x = ClientOrderID{}
	mi := &file_broker_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClientOrderID) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClientOrderID) ProtoMessage() {}

func (x *ClientOrderID) ProtoReflect() protoreflect.Message {
	mi := &file_broker_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClientOrderID.ProtoReflect.Descriptor instead.
func (*ClientOrderID) Descriptor() ([]byte, []int) {
	return file_broker_proto_rawDescGZIP(), []int{1}
}

func (x *ClientOrderID) GetNetwork() metadata.Network {
	if x != nil {
		return x.Network
	}
	return metadata.Network(0)
}

func (x *ClientOrderID) GetSmartContractAddr() string {
	if x != nil {
		return x.SmartContractAddr
	}
	return ""
}

func (x *ClientOrderID) GetOrderID() int64 {
	if x != nil {
		return x.OrderID
	}
	return 0
}

type BrokerOrderDetailsList struct {
	state                  protoimpl.MessageState `protogen:"open.v1"`
	BrokerOrderDetailsList []*BrokerOrderDetails  `protobuf:"bytes,1,rep,name=BrokerOrderDetailsList,proto3" json:"BrokerOrderDetailsList,omitempty"`
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *BrokerOrderDetailsList) Reset() {
	*x = BrokerOrderDetailsList{}
	mi := &file_broker_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BrokerOrderDetailsList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BrokerOrderDetailsList) ProtoMessage() {}

func (x *BrokerOrderDetailsList) ProtoReflect() protoreflect.Message {
	mi := &file_broker_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BrokerOrderDetailsList.ProtoReflect.Descriptor instead.
func (*BrokerOrderDetailsList) Descriptor() ([]byte, []int) {
	return file_broker_proto_rawDescGZIP(), []int{2}
}

func (x *BrokerOrderDetailsList) GetBrokerOrderDetailsList() []*BrokerOrderDetails {
	if x != nil {
		return x.BrokerOrderDetailsList
	}
	return nil
}

var File_broker_proto protoreflect.FileDescriptor

const file_broker_proto_rawDesc = "" +
	"\n" +
	"\fbroker.proto\x12\x05order\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\n" +
	"util.proto\x1a3sologenic/com-fs-utils-lib/go/decimal/decimal.proto\x1a9sologenic/com-fs-utils-lib/models/metadata/metadata.proto\"\x95\x0f\n" +
	"\x12BrokerOrderDetails\x12*\n" +
	"\x10BrokerAssignedID\x18\x01 \x01(\tR\x10BrokerAssignedID\x12:\n" +
	"\rClientOrderID\x18\x02 \x01(\v2\x14.order.ClientOrderIDR\rClientOrderID\x12<\n" +
	"\vSubmittedAt\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\vSubmittedAt\x12;\n" +
	"\bFilledAt\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampH\x00R\bFilledAt\x88\x01\x01\x12=\n" +
	"\tExpiredAt\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampH\x01R\tExpiredAt\x88\x01\x01\x12A\n" +
	"\vCancelledAt\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampH\x02R\vCancelledAt\x88\x01\x01\x12;\n" +
	"\bFailedAt\x18\a \x01(\v2\x1a.google.protobuf.TimestampH\x03R\bFailedAt\x88\x01\x01\x12\x18\n" +
	"\aAssetID\x18\b \x01(\tR\aAssetID\x12\x16\n" +
	"\x06Symbol\x18\t \x01(\tR\x06Symbol\x121\n" +
	"\n" +
	"AssetClass\x18\n" +
	" \x01(\x0e2\x11.order.AssetClassR\n" +
	"AssetClass\x121\n" +
	"\n" +
	"OrderClass\x18\v \x01(\x0e2\x11.order.OrderClassR\n" +
	"OrderClass\x12$\n" +
	"\x04Type\x18\f \x01(\x0e2\x10.order.TradeTypeR\x04Type\x12$\n" +
	"\x04Side\x18\r \x01(\x0e2\x10.order.OrderTypeR\x04Side\x124\n" +
	"\vTimeInForce\x18\x0e \x01(\x0e2\x12.order.TimeInForceR\vTimeInForce\x121\n" +
	"\bNotional\x18\x0f \x01(\v2\x10.decimal.DecimalH\x04R\bNotional\x88\x01\x01\x121\n" +
	"\bOrderQty\x18\x10 \x01(\v2\x10.decimal.DecimalH\x05R\bOrderQty\x88\x01\x01\x12.\n" +
	"\tFilledQty\x18\x11 \x01(\v2\x10.decimal.DecimalR\tFilledQty\x12=\n" +
	"\x0eFilledAvgPrice\x18\x12 \x01(\v2\x10.decimal.DecimalH\x06R\x0eFilledAvgPrice\x88\x01\x01\x125\n" +
	"\n" +
	"LimitPrice\x18\x13 \x01(\v2\x10.decimal.DecimalH\aR\n" +
	"LimitPrice\x88\x01\x01\x123\n" +
	"\tStopPrice\x18\x14 \x01(\v2\x10.decimal.DecimalH\bR\tStopPrice\x88\x01\x01\x125\n" +
	"\n" +
	"TrailPrice\x18\x15 \x01(\v2\x10.decimal.DecimalH\tR\n" +
	"TrailPrice\x88\x01\x01\x129\n" +
	"\fTrailPercent\x18\x16 \x01(\v2\x10.decimal.DecimalH\n" +
	"R\fTrailPercent\x88\x01\x01\x12'\n" +
	"\x03HWM\x18\x17 \x01(\v2\x10.decimal.DecimalH\vR\x03HWM\x88\x01\x01\x12$\n" +
	"\rExtendedHours\x18\x18 \x01(\bR\rExtendedHours\x128\n" +
	"\tCreatedAt\x18\x19 \x01(\v2\x1a.google.protobuf.TimestampR\tCreatedAt\x12=\n" +
	"\tUpdatedAt\x18\x1a \x01(\v2\x1a.google.protobuf.TimestampH\fR\tUpdatedAt\x88\x01\x01\x120\n" +
	"\x06Status\x18\x1b \x01(\x0e2\x18.order.BrokerOrderStatusR\x06Status\x12;\n" +
	"\rTotalPosition\x18\x1c \x01(\v2\x10.decimal.DecimalH\rR\rTotalPosition\x88\x01\x01\x129\n" +
	"\fPartialPrice\x18\x1d \x01(\v2\x10.decimal.DecimalH\x0eR\fPartialPrice\x88\x01\x01\x125\n" +
	"\n" +
	"PartialQty\x18\x1e \x01(\v2\x10.decimal.DecimalH\x0fR\n" +
	"PartialQty\x88\x01\x01\x129\n" +
	"\vProcessInfo\x18\x1f \x01(\v2\x12.order.ProcessInfoH\x10R\vProcessInfo\x88\x01\x01\x12#\n" +
	"\n" +
	"InstanceID\x18  \x01(\tH\x11R\n" +
	"InstanceID\x88\x01\x01B\v\n" +
	"\t_FilledAtB\f\n" +
	"\n" +
	"_ExpiredAtB\x0e\n" +
	"\f_CancelledAtB\v\n" +
	"\t_FailedAtB\v\n" +
	"\t_NotionalB\v\n" +
	"\t_OrderQtyB\x11\n" +
	"\x0f_FilledAvgPriceB\r\n" +
	"\v_LimitPriceB\f\n" +
	"\n" +
	"_StopPriceB\r\n" +
	"\v_TrailPriceB\x0f\n" +
	"\r_TrailPercentB\x06\n" +
	"\x04_HWMB\f\n" +
	"\n" +
	"_UpdatedAtB\x10\n" +
	"\x0e_TotalPositionB\x0f\n" +
	"\r_PartialPriceB\r\n" +
	"\v_PartialQtyB\x0e\n" +
	"\f_ProcessInfoB\r\n" +
	"\v_InstanceID\"\x84\x01\n" +
	"\rClientOrderID\x12+\n" +
	"\aNetwork\x18\x01 \x01(\x0e2\x11.metadata.NetworkR\aNetwork\x12,\n" +
	"\x11SmartContractAddr\x18\x02 \x01(\tR\x11SmartContractAddr\x12\x18\n" +
	"\aOrderID\x18\x03 \x01(\x03R\aOrderID\"k\n" +
	"\x16BrokerOrderDetailsList\x12Q\n" +
	"\x16BrokerOrderDetailsList\x18\x01 \x03(\v2\x19.order.BrokerOrderDetailsR\x16BrokerOrderDetailsList*A\n" +
	"\n" +
	"AssetClass\x12\x18\n" +
	"\x14NOT_USED_ASSET_CLASS\x10\x00\x12\r\n" +
	"\tUS_EQUITY\x10\x01\x12\n" +
	"\n" +
	"\x06CRYPTO\x10\x02*h\n" +
	"\vTimeInForce\x12\x1a\n" +
	"\x16NOT_USED_TIME_IN_FORCE\x10\x00\x12\a\n" +
	"\x03DAY\x10\x01\x12\a\n" +
	"\x03GTC\x10\x02\x12\a\n" +
	"\x03GTT\x10\x03\x12\a\n" +
	"\x03OPG\x10\x04\x12\a\n" +
	"\x03CLS\x10\x05\x12\a\n" +
	"\x03IOC\x10\x06\x12\a\n" +
	"\x03FOK\x10\a*\x9f\x01\n" +
	"\tTradeType\x12\x17\n" +
	"\x13NOT_USED_TRADE_TYPE\x10\x00\x12\n" +
	"\n" +
	"\x06MARKET\x10\x01\x12\t\n" +
	"\x05LIMIT\x10\x02\x12\b\n" +
	"\x04STOP\x10\x03\x12\x0e\n" +
	"\n" +
	"STOP_LIMIT\x10\x04\x12\x16\n" +
	"\x12OPEN_CLOSE_AUCTION\x10\x05\x12\v\n" +
	"\aBRACKET\x10\x06\x12\a\n" +
	"\x03OCO\x10\a\x12\a\n" +
	"\x03OTO\x10\b\x12\x11\n" +
	"\rTRAILING_STOP\x10\t*\x81\x01\n" +
	"\n" +
	"OrderClass\x12\x18\n" +
	"\x14NOT_USED_ORDER_CLASS\x10\x00\x12\x16\n" +
	"\x12ORDER_CLASS_SIMPLE\x10\x01\x12\x17\n" +
	"\x13ORDER_CLASS_BRACKET\x10\x02\x12\x13\n" +
	"\x0fORDER_CLASS_OCO\x10\x03\x12\x13\n" +
	"\x0fORDER_CLASS_OTO\x10\x04*\x94\x02\n" +
	"\x11BrokerOrderStatus\x12 \n" +
	"\x1cNOT_USED_ALPACA_ORDER_STATUS\x10\x00\x12\x0f\n" +
	"\vPENDING_NEW\x10\x01\x12\a\n" +
	"\x03NEW\x10\x02\x12\x14\n" +
	"\x10PARTIALLY_FILLED\x10\x03\x12\n" +
	"\n" +
	"\x06FILLED\x10\x04\x12\x10\n" +
	"\fDONE_FOR_DAY\x10\x05\x12\f\n" +
	"\bCANCELED\x10\x06\x12\v\n" +
	"\aEXPIRED\x10\a\x12\x12\n" +
	"\x0ePENDING_CANCEL\x10\b\x12\f\n" +
	"\bACCEPTED\x10\t\x12\x18\n" +
	"\x14ACCEPTED_FOR_BIDDING\x10\n" +
	"\x12\v\n" +
	"\aSTOPPED\x10\v\x12\f\n" +
	"\bREJECTED\x10\f\x12\r\n" +
	"\tSUSPENDED\x10\r\x12\x0e\n" +
	"\n" +
	"CALCULATED\x10\x0eB/Z-github.com/sologenic/com-fs-order-model;orderb\x06proto3"

var (
	file_broker_proto_rawDescOnce sync.Once
	file_broker_proto_rawDescData []byte
)

func file_broker_proto_rawDescGZIP() []byte {
	file_broker_proto_rawDescOnce.Do(func() {
		file_broker_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_broker_proto_rawDesc), len(file_broker_proto_rawDesc)))
	})
	return file_broker_proto_rawDescData
}

var file_broker_proto_enumTypes = make([]protoimpl.EnumInfo, 5)
var file_broker_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_broker_proto_goTypes = []any{
	(AssetClass)(0),                // 0: order.AssetClass
	(TimeInForce)(0),               // 1: order.TimeInForce
	(TradeType)(0),                 // 2: order.TradeType
	(OrderClass)(0),                // 3: order.OrderClass
	(BrokerOrderStatus)(0),         // 4: order.BrokerOrderStatus
	(*BrokerOrderDetails)(nil),     // 5: order.BrokerOrderDetails
	(*ClientOrderID)(nil),          // 6: order.ClientOrderID
	(*BrokerOrderDetailsList)(nil), // 7: order.BrokerOrderDetailsList
	(*timestamppb.Timestamp)(nil),  // 8: google.protobuf.Timestamp
	(OrderType)(0),                 // 9: order.OrderType
	(*decimal.Decimal)(nil),        // 10: decimal.Decimal
	(*ProcessInfo)(nil),            // 11: order.ProcessInfo
	(metadata.Network)(0),          // 12: metadata.Network
}
var file_broker_proto_depIdxs = []int32{
	6,  // 0: order.BrokerOrderDetails.ClientOrderID:type_name -> order.ClientOrderID
	8,  // 1: order.BrokerOrderDetails.SubmittedAt:type_name -> google.protobuf.Timestamp
	8,  // 2: order.BrokerOrderDetails.FilledAt:type_name -> google.protobuf.Timestamp
	8,  // 3: order.BrokerOrderDetails.ExpiredAt:type_name -> google.protobuf.Timestamp
	8,  // 4: order.BrokerOrderDetails.CancelledAt:type_name -> google.protobuf.Timestamp
	8,  // 5: order.BrokerOrderDetails.FailedAt:type_name -> google.protobuf.Timestamp
	0,  // 6: order.BrokerOrderDetails.AssetClass:type_name -> order.AssetClass
	3,  // 7: order.BrokerOrderDetails.OrderClass:type_name -> order.OrderClass
	2,  // 8: order.BrokerOrderDetails.Type:type_name -> order.TradeType
	9,  // 9: order.BrokerOrderDetails.Side:type_name -> order.OrderType
	1,  // 10: order.BrokerOrderDetails.TimeInForce:type_name -> order.TimeInForce
	10, // 11: order.BrokerOrderDetails.Notional:type_name -> decimal.Decimal
	10, // 12: order.BrokerOrderDetails.OrderQty:type_name -> decimal.Decimal
	10, // 13: order.BrokerOrderDetails.FilledQty:type_name -> decimal.Decimal
	10, // 14: order.BrokerOrderDetails.FilledAvgPrice:type_name -> decimal.Decimal
	10, // 15: order.BrokerOrderDetails.LimitPrice:type_name -> decimal.Decimal
	10, // 16: order.BrokerOrderDetails.StopPrice:type_name -> decimal.Decimal
	10, // 17: order.BrokerOrderDetails.TrailPrice:type_name -> decimal.Decimal
	10, // 18: order.BrokerOrderDetails.TrailPercent:type_name -> decimal.Decimal
	10, // 19: order.BrokerOrderDetails.HWM:type_name -> decimal.Decimal
	8,  // 20: order.BrokerOrderDetails.CreatedAt:type_name -> google.protobuf.Timestamp
	8,  // 21: order.BrokerOrderDetails.UpdatedAt:type_name -> google.protobuf.Timestamp
	4,  // 22: order.BrokerOrderDetails.Status:type_name -> order.BrokerOrderStatus
	10, // 23: order.BrokerOrderDetails.TotalPosition:type_name -> decimal.Decimal
	10, // 24: order.BrokerOrderDetails.PartialPrice:type_name -> decimal.Decimal
	10, // 25: order.BrokerOrderDetails.PartialQty:type_name -> decimal.Decimal
	11, // 26: order.BrokerOrderDetails.ProcessInfo:type_name -> order.ProcessInfo
	12, // 27: order.ClientOrderID.Network:type_name -> metadata.Network
	5,  // 28: order.BrokerOrderDetailsList.BrokerOrderDetailsList:type_name -> order.BrokerOrderDetails
	29, // [29:29] is the sub-list for method output_type
	29, // [29:29] is the sub-list for method input_type
	29, // [29:29] is the sub-list for extension type_name
	29, // [29:29] is the sub-list for extension extendee
	0,  // [0:29] is the sub-list for field type_name
}

func init() { file_broker_proto_init() }
func file_broker_proto_init() {
	if File_broker_proto != nil {
		return
	}
	file_util_proto_init()
	file_broker_proto_msgTypes[0].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_broker_proto_rawDesc), len(file_broker_proto_rawDesc)),
			NumEnums:      5,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_broker_proto_goTypes,
		DependencyIndexes: file_broker_proto_depIdxs,
		EnumInfos:         file_broker_proto_enumTypes,
		MessageInfos:      file_broker_proto_msgTypes,
	}.Build()
	File_broker_proto = out.File
	file_broker_proto_goTypes = nil
	file_broker_proto_depIdxs = nil
}
