// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             v4.24.3
// source: broker-smartcontract-grpc.proto

package order

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	BrokerSmartContractService_CreateBrokerSmartContractOrder_FullMethodName = "/order.BrokerSmartContractService/CreateBrokerSmartContractOrder"
	BrokerSmartContractService_UpdateBrokerSmartContractOrder_FullMethodName = "/order.BrokerSmartContractService/UpdateBrokerSmartContractOrder"
)

// BrokerSmartContractServiceClient is the client API for BrokerSmartContractService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type BrokerSmartContractServiceClient interface {
	CreateBrokerSmartContractOrder(ctx context.Context, in *Order, opts ...grpc.CallOption) (*emptypb.Empty, error)
	// rpc Get(Filter) returns (Records) {}
	UpdateBrokerSmartContractOrder(ctx context.Context, in *Order, opts ...grpc.CallOption) (*emptypb.Empty, error)
}

type brokerSmartContractServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewBrokerSmartContractServiceClient(cc grpc.ClientConnInterface) BrokerSmartContractServiceClient {
	return &brokerSmartContractServiceClient{cc}
}

func (c *brokerSmartContractServiceClient) CreateBrokerSmartContractOrder(ctx context.Context, in *Order, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, BrokerSmartContractService_CreateBrokerSmartContractOrder_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *brokerSmartContractServiceClient) UpdateBrokerSmartContractOrder(ctx context.Context, in *Order, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, BrokerSmartContractService_UpdateBrokerSmartContractOrder_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// BrokerSmartContractServiceServer is the server API for BrokerSmartContractService service.
// All implementations should embed UnimplementedBrokerSmartContractServiceServer
// for forward compatibility
type BrokerSmartContractServiceServer interface {
	CreateBrokerSmartContractOrder(context.Context, *Order) (*emptypb.Empty, error)
	// rpc Get(Filter) returns (Records) {}
	UpdateBrokerSmartContractOrder(context.Context, *Order) (*emptypb.Empty, error)
}

// UnimplementedBrokerSmartContractServiceServer should be embedded to have forward compatible implementations.
type UnimplementedBrokerSmartContractServiceServer struct {
}

func (UnimplementedBrokerSmartContractServiceServer) CreateBrokerSmartContractOrder(context.Context, *Order) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateBrokerSmartContractOrder not implemented")
}
func (UnimplementedBrokerSmartContractServiceServer) UpdateBrokerSmartContractOrder(context.Context, *Order) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateBrokerSmartContractOrder not implemented")
}

// UnsafeBrokerSmartContractServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to BrokerSmartContractServiceServer will
// result in compilation errors.
type UnsafeBrokerSmartContractServiceServer interface {
	mustEmbedUnimplementedBrokerSmartContractServiceServer()
}

func RegisterBrokerSmartContractServiceServer(s grpc.ServiceRegistrar, srv BrokerSmartContractServiceServer) {
	s.RegisterService(&BrokerSmartContractService_ServiceDesc, srv)
}

func _BrokerSmartContractService_CreateBrokerSmartContractOrder_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Order)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BrokerSmartContractServiceServer).CreateBrokerSmartContractOrder(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BrokerSmartContractService_CreateBrokerSmartContractOrder_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BrokerSmartContractServiceServer).CreateBrokerSmartContractOrder(ctx, req.(*Order))
	}
	return interceptor(ctx, in, info, handler)
}

func _BrokerSmartContractService_UpdateBrokerSmartContractOrder_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Order)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BrokerSmartContractServiceServer).UpdateBrokerSmartContractOrder(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BrokerSmartContractService_UpdateBrokerSmartContractOrder_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BrokerSmartContractServiceServer).UpdateBrokerSmartContractOrder(ctx, req.(*Order))
	}
	return interceptor(ctx, in, info, handler)
}

// BrokerSmartContractService_ServiceDesc is the grpc.ServiceDesc for BrokerSmartContractService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var BrokerSmartContractService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "order.BrokerSmartContractService",
	HandlerType: (*BrokerSmartContractServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateBrokerSmartContractOrder",
			Handler:    _BrokerSmartContractService_CreateBrokerSmartContractOrder_Handler,
		},
		{
			MethodName: "UpdateBrokerSmartContractOrder",
			Handler:    _BrokerSmartContractService_UpdateBrokerSmartContractOrder_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "broker-smartcontract-grpc.proto",
}
