// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package order

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// BrokerLogServiceClient is the client API for BrokerLogService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type BrokerLogServiceClient interface {
	// Non-transaction
	CreateBrokerLog(ctx context.Context, in *BrokerOrderDetails, opts ...grpc.CallOption) (*Key, error)
	// TODO: determine if we will need the Update method -> with the introduction of the LockLogRecord message,
	// we can handle the must have state and target state dynamically. Therefore, we may not need the Update method.
	UpdateBrokerLog(ctx context.Context, in *BrokerOrderDetails, opts ...grpc.CallOption) (*emptypb.Empty, error)
	// Transaction
	SetBrokerLogLock(ctx context.Context, in *LockLogRecord, opts ...grpc.CallOption) (*BrokerOrderDetails, error)
}

type brokerLogServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewBrokerLogServiceClient(cc grpc.ClientConnInterface) BrokerLogServiceClient {
	return &brokerLogServiceClient{cc}
}

func (c *brokerLogServiceClient) CreateBrokerLog(ctx context.Context, in *BrokerOrderDetails, opts ...grpc.CallOption) (*Key, error) {
	out := new(Key)
	err := c.cc.Invoke(ctx, "/order.BrokerLogService/CreateBrokerLog", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *brokerLogServiceClient) UpdateBrokerLog(ctx context.Context, in *BrokerOrderDetails, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, "/order.BrokerLogService/UpdateBrokerLog", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *brokerLogServiceClient) SetBrokerLogLock(ctx context.Context, in *LockLogRecord, opts ...grpc.CallOption) (*BrokerOrderDetails, error) {
	out := new(BrokerOrderDetails)
	err := c.cc.Invoke(ctx, "/order.BrokerLogService/SetBrokerLogLock", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// BrokerLogServiceServer is the server API for BrokerLogService service.
// All implementations should embed UnimplementedBrokerLogServiceServer
// for forward compatibility
type BrokerLogServiceServer interface {
	// Non-transaction
	CreateBrokerLog(context.Context, *BrokerOrderDetails) (*Key, error)
	// TODO: determine if we will need the Update method -> with the introduction of the LockLogRecord message,
	// we can handle the must have state and target state dynamically. Therefore, we may not need the Update method.
	UpdateBrokerLog(context.Context, *BrokerOrderDetails) (*emptypb.Empty, error)
	// Transaction
	SetBrokerLogLock(context.Context, *LockLogRecord) (*BrokerOrderDetails, error)
}

// UnimplementedBrokerLogServiceServer should be embedded to have forward compatible implementations.
type UnimplementedBrokerLogServiceServer struct {
}

func (UnimplementedBrokerLogServiceServer) CreateBrokerLog(context.Context, *BrokerOrderDetails) (*Key, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateBrokerLog not implemented")
}
func (UnimplementedBrokerLogServiceServer) UpdateBrokerLog(context.Context, *BrokerOrderDetails) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateBrokerLog not implemented")
}
func (UnimplementedBrokerLogServiceServer) SetBrokerLogLock(context.Context, *LockLogRecord) (*BrokerOrderDetails, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SetBrokerLogLock not implemented")
}

// UnsafeBrokerLogServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to BrokerLogServiceServer will
// result in compilation errors.
type UnsafeBrokerLogServiceServer interface {
	mustEmbedUnimplementedBrokerLogServiceServer()
}

func RegisterBrokerLogServiceServer(s grpc.ServiceRegistrar, srv BrokerLogServiceServer) {
	s.RegisterService(&BrokerLogService_ServiceDesc, srv)
}

func _BrokerLogService_CreateBrokerLog_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BrokerOrderDetails)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BrokerLogServiceServer).CreateBrokerLog(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/order.BrokerLogService/CreateBrokerLog",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BrokerLogServiceServer).CreateBrokerLog(ctx, req.(*BrokerOrderDetails))
	}
	return interceptor(ctx, in, info, handler)
}

func _BrokerLogService_UpdateBrokerLog_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BrokerOrderDetails)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BrokerLogServiceServer).UpdateBrokerLog(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/order.BrokerLogService/UpdateBrokerLog",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BrokerLogServiceServer).UpdateBrokerLog(ctx, req.(*BrokerOrderDetails))
	}
	return interceptor(ctx, in, info, handler)
}

func _BrokerLogService_SetBrokerLogLock_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LockLogRecord)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BrokerLogServiceServer).SetBrokerLogLock(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/order.BrokerLogService/SetBrokerLogLock",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BrokerLogServiceServer).SetBrokerLogLock(ctx, req.(*LockLogRecord))
	}
	return interceptor(ctx, in, info, handler)
}

// BrokerLogService_ServiceDesc is the grpc.ServiceDesc for BrokerLogService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var BrokerLogService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "order.BrokerLogService",
	HandlerType: (*BrokerLogServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateBrokerLog",
			Handler:    _BrokerLogService_CreateBrokerLog_Handler,
		},
		{
			MethodName: "UpdateBrokerLog",
			Handler:    _BrokerLogService_UpdateBrokerLog_Handler,
		},
		{
			MethodName: "SetBrokerLogLock",
			Handler:    _BrokerLogService_SetBrokerLogLock_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "broker-grpc.proto",
}
