// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v1.181.2
//   protoc               v5.29.3
// source: broker-grpc.proto

/* eslint-disable */
import {
  type CallOptions,
  ChannelCredentials,
  Client,
  type ClientOptions,
  type ClientUnaryCall,
  type handleUnaryCall,
  makeGenericClientConstructor,
  Metadata,
  type ServiceError,
  type UntypedServiceImplementation,
} from "@grpc/grpc-js";
import { BrokerOrderDetails, BrokerOrderDetailsList } from "./broker";
import { Empty } from "./google/protobuf/empty";
import { InstanceID, Key, LockLogRecord } from "./util";

export const protobufPackage = "order";

/** Broker Trade Update Log */
export type BrokerLogServiceService = typeof BrokerLogServiceService;
export const BrokerLogServiceService = {
  create: {
    path: "/order.BrokerLogService/Create",
    requestStream: false,
    responseStream: false,
    requestSerialize: (value: BrokerOrderDetails) => Buffer.from(BrokerOrderDetails.encode(value).finish()),
    requestDeserialize: (value: Buffer) => BrokerOrderDetails.decode(value),
    responseSerialize: (value: Key) => Buffer.from(Key.encode(value).finish()),
    responseDeserialize: (value: Buffer) => Key.decode(value),
  },
  /** Transaction */
  setLock: {
    path: "/order.BrokerLogService/SetLock",
    requestStream: false,
    responseStream: false,
    requestSerialize: (value: LockLogRecord) => Buffer.from(LockLogRecord.encode(value).finish()),
    requestDeserialize: (value: Buffer) => LockLogRecord.decode(value),
    responseSerialize: (value: BrokerOrderDetails) => Buffer.from(BrokerOrderDetails.encode(value).finish()),
    responseDeserialize: (value: Buffer) => BrokerOrderDetails.decode(value),
  },
  /** For recovery, get all unprocessed Broker Logs. Unprocessed logs are logs that are in the states `OPEN` or `LOCKED`. */
  getAllUnprocessed: {
    path: "/order.BrokerLogService/GetAllUnprocessed",
    requestStream: false,
    responseStream: false,
    requestSerialize: (value: InstanceID) => Buffer.from(InstanceID.encode(value).finish()),
    requestDeserialize: (value: Buffer) => InstanceID.decode(value),
    responseSerialize: (value: BrokerOrderDetailsList) => Buffer.from(BrokerOrderDetailsList.encode(value).finish()),
    responseDeserialize: (value: Buffer) => BrokerOrderDetailsList.decode(value),
  },
  /** Starting point for rescanner */
  getLatest: {
    path: "/order.BrokerLogService/GetLatest",
    requestStream: false,
    responseStream: false,
    requestSerialize: (value: Empty) => Buffer.from(Empty.encode(value).finish()),
    requestDeserialize: (value: Buffer) => Empty.decode(value),
    responseSerialize: (value: BrokerOrderDetails) => Buffer.from(BrokerOrderDetails.encode(value).finish()),
    responseDeserialize: (value: Buffer) => BrokerOrderDetails.decode(value),
  },
} as const;

export interface BrokerLogServiceServer extends UntypedServiceImplementation {
  create: handleUnaryCall<BrokerOrderDetails, Key>;
  /** Transaction */
  setLock: handleUnaryCall<LockLogRecord, BrokerOrderDetails>;
  /** For recovery, get all unprocessed Broker Logs. Unprocessed logs are logs that are in the states `OPEN` or `LOCKED`. */
  getAllUnprocessed: handleUnaryCall<InstanceID, BrokerOrderDetailsList>;
  /** Starting point for rescanner */
  getLatest: handleUnaryCall<Empty, BrokerOrderDetails>;
}

export interface BrokerLogServiceClient extends Client {
  create(request: BrokerOrderDetails, callback: (error: ServiceError | null, response: Key) => void): ClientUnaryCall;
  create(
    request: BrokerOrderDetails,
    metadata: Metadata,
    callback: (error: ServiceError | null, response: Key) => void,
  ): ClientUnaryCall;
  create(
    request: BrokerOrderDetails,
    metadata: Metadata,
    options: Partial<CallOptions>,
    callback: (error: ServiceError | null, response: Key) => void,
  ): ClientUnaryCall;
  /** Transaction */
  setLock(
    request: LockLogRecord,
    callback: (error: ServiceError | null, response: BrokerOrderDetails) => void,
  ): ClientUnaryCall;
  setLock(
    request: LockLogRecord,
    metadata: Metadata,
    callback: (error: ServiceError | null, response: BrokerOrderDetails) => void,
  ): ClientUnaryCall;
  setLock(
    request: LockLogRecord,
    metadata: Metadata,
    options: Partial<CallOptions>,
    callback: (error: ServiceError | null, response: BrokerOrderDetails) => void,
  ): ClientUnaryCall;
  /** For recovery, get all unprocessed Broker Logs. Unprocessed logs are logs that are in the states `OPEN` or `LOCKED`. */
  getAllUnprocessed(
    request: InstanceID,
    callback: (error: ServiceError | null, response: BrokerOrderDetailsList) => void,
  ): ClientUnaryCall;
  getAllUnprocessed(
    request: InstanceID,
    metadata: Metadata,
    callback: (error: ServiceError | null, response: BrokerOrderDetailsList) => void,
  ): ClientUnaryCall;
  getAllUnprocessed(
    request: InstanceID,
    metadata: Metadata,
    options: Partial<CallOptions>,
    callback: (error: ServiceError | null, response: BrokerOrderDetailsList) => void,
  ): ClientUnaryCall;
  /** Starting point for rescanner */
  getLatest(
    request: Empty,
    callback: (error: ServiceError | null, response: BrokerOrderDetails) => void,
  ): ClientUnaryCall;
  getLatest(
    request: Empty,
    metadata: Metadata,
    callback: (error: ServiceError | null, response: BrokerOrderDetails) => void,
  ): ClientUnaryCall;
  getLatest(
    request: Empty,
    metadata: Metadata,
    options: Partial<CallOptions>,
    callback: (error: ServiceError | null, response: BrokerOrderDetails) => void,
  ): ClientUnaryCall;
}

export const BrokerLogServiceClient = makeGenericClientConstructor(
  BrokerLogServiceService,
  "order.BrokerLogService",
) as unknown as {
  new (address: string, credentials: ChannelCredentials, options?: Partial<ClientOptions>): BrokerLogServiceClient;
  service: typeof BrokerLogServiceService;
  serviceName: string;
};
