// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: broker-grpc.proto

package order

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

var File_broker_grpc_proto protoreflect.FileDescriptor

const file_broker_grpc_proto_rawDesc = "" +
	"\n" +
	"\x11broker-grpc.proto\x12\x05order\x1a\x1bgoogle/protobuf/empty.proto\x1a\fbroker.proto\x1a\n" +
	"util.proto2\x8e\x02\n" +
	"\x10BrokerLogService\x121\n" +
	"\x06Create\x12\x19.order.BrokerOrderDetails\x1a\n" +
	".order.Key\"\x00\x12<\n" +
	"\aSetLock\x12\x14.order.LockLogRecord\x1a\x19.order.BrokerOrderDetails\"\x00\x12G\n" +
	"\x11GetAllUnprocessed\x12\x11.order.InstanceID\x1a\x1d.order.BrokerOrderDetailsList\"\x00\x12@\n" +
	"\tGetLatest\x12\x16.google.protobuf.Empty\x1a\x19.order.BrokerOrderDetails\"\x00B/Z-github.com/sologenic/com-fs-order-model;orderb\x06proto3"

var file_broker_grpc_proto_goTypes = []any{
	(*BrokerOrderDetails)(nil),     // 0: order.BrokerOrderDetails
	(*LockLogRecord)(nil),          // 1: order.LockLogRecord
	(*InstanceID)(nil),             // 2: order.InstanceID
	(*emptypb.Empty)(nil),          // 3: google.protobuf.Empty
	(*Key)(nil),                    // 4: order.Key
	(*BrokerOrderDetailsList)(nil), // 5: order.BrokerOrderDetailsList
}
var file_broker_grpc_proto_depIdxs = []int32{
	0, // 0: order.BrokerLogService.Create:input_type -> order.BrokerOrderDetails
	1, // 1: order.BrokerLogService.SetLock:input_type -> order.LockLogRecord
	2, // 2: order.BrokerLogService.GetAllUnprocessed:input_type -> order.InstanceID
	3, // 3: order.BrokerLogService.GetLatest:input_type -> google.protobuf.Empty
	4, // 4: order.BrokerLogService.Create:output_type -> order.Key
	0, // 5: order.BrokerLogService.SetLock:output_type -> order.BrokerOrderDetails
	5, // 6: order.BrokerLogService.GetAllUnprocessed:output_type -> order.BrokerOrderDetailsList
	0, // 7: order.BrokerLogService.GetLatest:output_type -> order.BrokerOrderDetails
	4, // [4:8] is the sub-list for method output_type
	0, // [0:4] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_broker_grpc_proto_init() }
func file_broker_grpc_proto_init() {
	if File_broker_grpc_proto != nil {
		return
	}
	file_broker_proto_init()
	file_util_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_broker_grpc_proto_rawDesc), len(file_broker_grpc_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_broker_grpc_proto_goTypes,
		DependencyIndexes: file_broker_grpc_proto_depIdxs,
	}.Build()
	File_broker_grpc_proto = out.File
	file_broker_grpc_proto_goTypes = nil
	file_broker_grpc_proto_depIdxs = nil
}
