// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             v5.29.1
// source: broker-grpc.proto

package order

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	BrokerLogService_Create_FullMethodName            = "/order.BrokerLogService/Create"
	BrokerLogService_SetLock_FullMethodName           = "/order.BrokerLogService/SetLock"
	BrokerLogService_GetAllUnprocessed_FullMethodName = "/order.BrokerLogService/GetAllUnprocessed"
	BrokerLogService_GetLatest_FullMethodName         = "/order.BrokerLogService/GetLatest"
)

// BrokerLogServiceClient is the client API for BrokerLogService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type BrokerLogServiceClient interface {
	Create(ctx context.Context, in *BrokerOrderDetails, opts ...grpc.CallOption) (*Key, error)
	// Transaction
	SetLock(ctx context.Context, in *LockLogRecord, opts ...grpc.CallOption) (*BrokerOrderDetails, error)
	// For recovery, get all unprocessed Broker Logs. Unprocessed logs are logs that are in the states `OPEN` or `LOCKED`.
	GetAllUnprocessed(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*BrokerOrderDetailsList, error)
	// Starting point for rescanner
	GetLatest(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*BrokerOrderDetails, error)
}

type brokerLogServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewBrokerLogServiceClient(cc grpc.ClientConnInterface) BrokerLogServiceClient {
	return &brokerLogServiceClient{cc}
}

func (c *brokerLogServiceClient) Create(ctx context.Context, in *BrokerOrderDetails, opts ...grpc.CallOption) (*Key, error) {
	out := new(Key)
	err := c.cc.Invoke(ctx, BrokerLogService_Create_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *brokerLogServiceClient) SetLock(ctx context.Context, in *LockLogRecord, opts ...grpc.CallOption) (*BrokerOrderDetails, error) {
	out := new(BrokerOrderDetails)
	err := c.cc.Invoke(ctx, BrokerLogService_SetLock_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *brokerLogServiceClient) GetAllUnprocessed(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*BrokerOrderDetailsList, error) {
	out := new(BrokerOrderDetailsList)
	err := c.cc.Invoke(ctx, BrokerLogService_GetAllUnprocessed_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *brokerLogServiceClient) GetLatest(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*BrokerOrderDetails, error) {
	out := new(BrokerOrderDetails)
	err := c.cc.Invoke(ctx, BrokerLogService_GetLatest_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// BrokerLogServiceServer is the server API for BrokerLogService service.
// All implementations should embed UnimplementedBrokerLogServiceServer
// for forward compatibility
type BrokerLogServiceServer interface {
	Create(context.Context, *BrokerOrderDetails) (*Key, error)
	// Transaction
	SetLock(context.Context, *LockLogRecord) (*BrokerOrderDetails, error)
	// For recovery, get all unprocessed Broker Logs. Unprocessed logs are logs that are in the states `OPEN` or `LOCKED`.
	GetAllUnprocessed(context.Context, *emptypb.Empty) (*BrokerOrderDetailsList, error)
	// Starting point for rescanner
	GetLatest(context.Context, *emptypb.Empty) (*BrokerOrderDetails, error)
}

// UnimplementedBrokerLogServiceServer should be embedded to have forward compatible implementations.
type UnimplementedBrokerLogServiceServer struct {
}

func (UnimplementedBrokerLogServiceServer) Create(context.Context, *BrokerOrderDetails) (*Key, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Create not implemented")
}
func (UnimplementedBrokerLogServiceServer) SetLock(context.Context, *LockLogRecord) (*BrokerOrderDetails, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SetLock not implemented")
}
func (UnimplementedBrokerLogServiceServer) GetAllUnprocessed(context.Context, *emptypb.Empty) (*BrokerOrderDetailsList, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetAllUnprocessed not implemented")
}
func (UnimplementedBrokerLogServiceServer) GetLatest(context.Context, *emptypb.Empty) (*BrokerOrderDetails, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetLatest not implemented")
}

// UnsafeBrokerLogServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to BrokerLogServiceServer will
// result in compilation errors.
type UnsafeBrokerLogServiceServer interface {
	mustEmbedUnimplementedBrokerLogServiceServer()
}

func RegisterBrokerLogServiceServer(s grpc.ServiceRegistrar, srv BrokerLogServiceServer) {
	s.RegisterService(&BrokerLogService_ServiceDesc, srv)
}

func _BrokerLogService_Create_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BrokerOrderDetails)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BrokerLogServiceServer).Create(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BrokerLogService_Create_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BrokerLogServiceServer).Create(ctx, req.(*BrokerOrderDetails))
	}
	return interceptor(ctx, in, info, handler)
}

func _BrokerLogService_SetLock_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LockLogRecord)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BrokerLogServiceServer).SetLock(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BrokerLogService_SetLock_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BrokerLogServiceServer).SetLock(ctx, req.(*LockLogRecord))
	}
	return interceptor(ctx, in, info, handler)
}

func _BrokerLogService_GetAllUnprocessed_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(emptypb.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BrokerLogServiceServer).GetAllUnprocessed(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BrokerLogService_GetAllUnprocessed_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BrokerLogServiceServer).GetAllUnprocessed(ctx, req.(*emptypb.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _BrokerLogService_GetLatest_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(emptypb.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BrokerLogServiceServer).GetLatest(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BrokerLogService_GetLatest_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BrokerLogServiceServer).GetLatest(ctx, req.(*emptypb.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

// BrokerLogService_ServiceDesc is the grpc.ServiceDesc for BrokerLogService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var BrokerLogService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "order.BrokerLogService",
	HandlerType: (*BrokerLogServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Create",
			Handler:    _BrokerLogService_Create_Handler,
		},
		{
			MethodName: "SetLock",
			Handler:    _BrokerLogService_SetLock_Handler,
		},
		{
			MethodName: "GetAllUnprocessed",
			Handler:    _BrokerLogService_GetAllUnprocessed_Handler,
		},
		{
			MethodName: "GetLatest",
			Handler:    _BrokerLogService_GetLatest_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "broker-grpc.proto",
}
