// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.30.2
// source: order.proto

package order

import (
	metadata "github.com/sologenic/com-fs-utils-lib/models/metadata"
	order_properties "github.com/sologenic/com-fs-utils-lib/models/order-properties"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Execution type(action) of the transaction against the smart contract
type TransactionType int32

const (
	TransactionType_NOT_USED_TRANSACTION_TYPE TransactionType = 0
	TransactionType_PURCHASE                  TransactionType = 1
	TransactionType_SELL                      TransactionType = 2
	TransactionType_REQUEST_ORDER_CANCEL      TransactionType = 3
	TransactionType_EXECUTE_ORDER             TransactionType = 4
	TransactionType_PAY_ORDER                 TransactionType = 5
	TransactionType_REQUEST_REATTESTATION     TransactionType = 6
	// Added for withdraw/deposit orders
	TransactionType_DEPOSIT             TransactionType = 7
	TransactionType_WITHDRAWAL          TransactionType = 8
	TransactionType_USDC_USD_CONVERSION TransactionType = 9 // Conversion of USDC to USD for deposit/withdrawal orders
)

// Enum value maps for TransactionType.
var (
	TransactionType_name = map[int32]string{
		0: "NOT_USED_TRANSACTION_TYPE",
		1: "PURCHASE",
		2: "SELL",
		3: "REQUEST_ORDER_CANCEL",
		4: "EXECUTE_ORDER",
		5: "PAY_ORDER",
		6: "REQUEST_REATTESTATION",
		7: "DEPOSIT",
		8: "WITHDRAWAL",
		9: "USDC_USD_CONVERSION",
	}
	TransactionType_value = map[string]int32{
		"NOT_USED_TRANSACTION_TYPE": 0,
		"PURCHASE":                  1,
		"SELL":                      2,
		"REQUEST_ORDER_CANCEL":      3,
		"EXECUTE_ORDER":             4,
		"PAY_ORDER":                 5,
		"REQUEST_REATTESTATION":     6,
		"DEPOSIT":                   7,
		"WITHDRAWAL":                8,
		"USDC_USD_CONVERSION":       9,
	}
)

func (x TransactionType) Enum() *TransactionType {
	p := new(TransactionType)
	*p = x
	return p
}

func (x TransactionType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (TransactionType) Descriptor() protoreflect.EnumDescriptor {
	return file_order_proto_enumTypes[0].Descriptor()
}

func (TransactionType) Type() protoreflect.EnumType {
	return &file_order_proto_enumTypes[0]
}

func (x TransactionType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use TransactionType.Descriptor instead.
func (TransactionType) EnumDescriptor() ([]byte, []int) {
	return file_order_proto_rawDescGZIP(), []int{0}
}

type OrderStateType int32

const (
	OrderStateType_NOT_USED_ORDER_STATE_TYPE OrderStateType = 0
	OrderStateType_OPEN                      OrderStateType = 1
	OrderStateType_PLACED                    OrderStateType = 2
	OrderStateType_PARTIALLY_EXECUTED        OrderStateType = 3
	OrderStateType_EXECUTED                  OrderStateType = 4
	OrderStateType_CANCELLATION_REQUESTED    OrderStateType = 5
	OrderStateType_CANCELLED                 OrderStateType = 6
	OrderStateType_FAILED                    OrderStateType = 7
)

// Enum value maps for OrderStateType.
var (
	OrderStateType_name = map[int32]string{
		0: "NOT_USED_ORDER_STATE_TYPE",
		1: "OPEN",
		2: "PLACED",
		3: "PARTIALLY_EXECUTED",
		4: "EXECUTED",
		5: "CANCELLATION_REQUESTED",
		6: "CANCELLED",
		7: "FAILED",
	}
	OrderStateType_value = map[string]int32{
		"NOT_USED_ORDER_STATE_TYPE": 0,
		"OPEN":                      1,
		"PLACED":                    2,
		"PARTIALLY_EXECUTED":        3,
		"EXECUTED":                  4,
		"CANCELLATION_REQUESTED":    5,
		"CANCELLED":                 6,
		"FAILED":                    7,
	}
)

func (x OrderStateType) Enum() *OrderStateType {
	p := new(OrderStateType)
	*p = x
	return p
}

func (x OrderStateType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (OrderStateType) Descriptor() protoreflect.EnumDescriptor {
	return file_order_proto_enumTypes[1].Descriptor()
}

func (OrderStateType) Type() protoreflect.EnumType {
	return &file_order_proto_enumTypes[1]
}

func (x OrderStateType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use OrderStateType.Descriptor instead.
func (OrderStateType) EnumDescriptor() ([]byte, []int) {
	return file_order_proto_rawDescGZIP(), []int{1}
}

type OrderCancelledBy int32

const (
	OrderCancelledBy_NOT_USED_ORDER_CANCEL_BY OrderCancelledBy = 0
	OrderCancelledBy_SMART_CONTRACT_OWNER     OrderCancelledBy = 1
	OrderCancelledBy_USER                     OrderCancelledBy = 2
	OrderCancelledBy_BROKER_ORACLE            OrderCancelledBy = 3
)

// Enum value maps for OrderCancelledBy.
var (
	OrderCancelledBy_name = map[int32]string{
		0: "NOT_USED_ORDER_CANCEL_BY",
		1: "SMART_CONTRACT_OWNER",
		2: "USER",
		3: "BROKER_ORACLE",
	}
	OrderCancelledBy_value = map[string]int32{
		"NOT_USED_ORDER_CANCEL_BY": 0,
		"SMART_CONTRACT_OWNER":     1,
		"USER":                     2,
		"BROKER_ORACLE":            3,
	}
)

func (x OrderCancelledBy) Enum() *OrderCancelledBy {
	p := new(OrderCancelledBy)
	*p = x
	return p
}

func (x OrderCancelledBy) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (OrderCancelledBy) Descriptor() protoreflect.EnumDescriptor {
	return file_order_proto_enumTypes[2].Descriptor()
}

func (OrderCancelledBy) Type() protoreflect.EnumType {
	return &file_order_proto_enumTypes[2]
}

func (x OrderCancelledBy) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use OrderCancelledBy.Descriptor instead.
func (OrderCancelledBy) EnumDescriptor() ([]byte, []int) {
	return file_order_proto_rawDescGZIP(), []int{2}
}

type PaymentState int32

const (
	PaymentState_NOT_USED_PAYMENT_STATE PaymentState = 0
	PaymentState_NOT_PAID               PaymentState = 1
	PaymentState_PAID                   PaymentState = 2
)

// Enum value maps for PaymentState.
var (
	PaymentState_name = map[int32]string{
		0: "NOT_USED_PAYMENT_STATE",
		1: "NOT_PAID",
		2: "PAID",
	}
	PaymentState_value = map[string]int32{
		"NOT_USED_PAYMENT_STATE": 0,
		"NOT_PAID":               1,
		"PAID":                   2,
	}
)

func (x PaymentState) Enum() *PaymentState {
	p := new(PaymentState)
	*p = x
	return p
}

func (x PaymentState) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (PaymentState) Descriptor() protoreflect.EnumDescriptor {
	return file_order_proto_enumTypes[3].Descriptor()
}

func (PaymentState) Type() protoreflect.EnumType {
	return &file_order_proto_enumTypes[3]
}

func (x PaymentState) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use PaymentState.Descriptor instead.
func (PaymentState) EnumDescriptor() ([]byte, []int) {
	return file_order_proto_rawDescGZIP(), []int{3}
}

type InternalOrderState int32

const (
	// Changed not used to NOT_APPLICABLE_INTERNAL_ORDER_STATE to accomodate for withdraw/deposit orders
	InternalOrderState_NOT_APPLICABLE_INTERNAL_ORDER_STATE InternalOrderState = 0
	// Initial state: Order is just created in the smart contract
	InternalOrderState_SMART_CONTRACT_NEW_ORDER_CREATED InternalOrderState = 1 // initial status when the order(BUY/SELL) is just created in the smart contract, OrderState in SC: `open``
	// Order place states
	InternalOrderState_BROKER_ORDER_PRE_SUBMITTED                      InternalOrderState = 2  // order is pre-submitted to the broker for further processing
	InternalOrderState_BROKER_ORDER_SUBMITTED                          InternalOrderState = 3  // order is submitted to the broker for further processing
	InternalOrderState_BROKER_ORDER_ACCEPTED                           InternalOrderState = 4  // (afterhours) order has been received by the broker, but hasn’t yet been routed to the execution venue, OrderState in Broker: `accepted`
	InternalOrderState_BROKER_ORDER_PENDING_NEW                        InternalOrderState = 5  // order has been routed to the exchange and it hasn't yet been confirmed by the exchange, OrderState in Broker: `pending_new`
	InternalOrderState_BROKER_ORDER_NEW                                InternalOrderState = 6  // order has been confirmed by the exchange and is active, OrderState in Broker: `new`
	InternalOrderState_SMART_CONTRACT_ORDER_PLACED                     InternalOrderState = 7  // order has been placed in the smart contract, OrderState in SC: `placed`
	InternalOrderState_BROKER_ORDER_PARTIALLY_FILLED                   InternalOrderState = 8  // order has been partially filled, OrderState in Broker: `partially_filled`
	InternalOrderState_SMART_CONTRACT_ORDER_PARTIALLY_FILLED_SUBMITTED InternalOrderState = 9  // order has been partially executed in the smart contract, OrderState in SC: `partially_executed`
	InternalOrderState_BROKER_ORDER_FILLED                             InternalOrderState = 10 // order has been completely filled, OrderState in Broker: `filled`
	InternalOrderState_SMART_CONTRACT_ORDER_EXECUTED                   InternalOrderState = 11 // order has been executed in the smart contract, OrderState in SC: `executed`
	InternalOrderState_BROKER_ORDER_PRE_CANCEL_REQUESTED               InternalOrderState = 12
	InternalOrderState_BROKER_ORDER_CANCEL_REQUESTED                   InternalOrderState = 13 // order cancellation request has been submitted to the broker
	InternalOrderState_BROKER_ORDER_CANCELED                           InternalOrderState = 14 // order has been canceled by the broker, OrderState in Broker: `canceled`
	InternalOrderState_BROKER_ORDER_REFUSED                            InternalOrderState = 15 // order sent to the broker, but the broker refused to accept it
	InternalOrderState_BROKER_ORDER_EXPIRED                            InternalOrderState = 16 // order has expired, OrderState in Broker: `expired`
	InternalOrderState_SMART_CONTRACT_PRE_ORDER_CANCELLED              InternalOrderState = 17
	InternalOrderState_SMART_CONTRACT_ORDER_CANCELLED                  InternalOrderState = 18 // order has been cancelled in the smart contract, OrderState in SC: `cancelled`
	InternalOrderState_PROCESS_FINISHED                                InternalOrderState = 19 // order has been processed and finished
	// Alternative scenarios
	InternalOrderState_SMART_CONTRACT_CANCEL_ORDER_REQUESTED InternalOrderState = 20 // order cancellation request has been submitted to the smart contract, OrderState in SC: `cancellation_requested`
)

// Enum value maps for InternalOrderState.
var (
	InternalOrderState_name = map[int32]string{
		0:  "NOT_APPLICABLE_INTERNAL_ORDER_STATE",
		1:  "SMART_CONTRACT_NEW_ORDER_CREATED",
		2:  "BROKER_ORDER_PRE_SUBMITTED",
		3:  "BROKER_ORDER_SUBMITTED",
		4:  "BROKER_ORDER_ACCEPTED",
		5:  "BROKER_ORDER_PENDING_NEW",
		6:  "BROKER_ORDER_NEW",
		7:  "SMART_CONTRACT_ORDER_PLACED",
		8:  "BROKER_ORDER_PARTIALLY_FILLED",
		9:  "SMART_CONTRACT_ORDER_PARTIALLY_FILLED_SUBMITTED",
		10: "BROKER_ORDER_FILLED",
		11: "SMART_CONTRACT_ORDER_EXECUTED",
		12: "BROKER_ORDER_PRE_CANCEL_REQUESTED",
		13: "BROKER_ORDER_CANCEL_REQUESTED",
		14: "BROKER_ORDER_CANCELED",
		15: "BROKER_ORDER_REFUSED",
		16: "BROKER_ORDER_EXPIRED",
		17: "SMART_CONTRACT_PRE_ORDER_CANCELLED",
		18: "SMART_CONTRACT_ORDER_CANCELLED",
		19: "PROCESS_FINISHED",
		20: "SMART_CONTRACT_CANCEL_ORDER_REQUESTED",
	}
	InternalOrderState_value = map[string]int32{
		"NOT_APPLICABLE_INTERNAL_ORDER_STATE":             0,
		"SMART_CONTRACT_NEW_ORDER_CREATED":                1,
		"BROKER_ORDER_PRE_SUBMITTED":                      2,
		"BROKER_ORDER_SUBMITTED":                          3,
		"BROKER_ORDER_ACCEPTED":                           4,
		"BROKER_ORDER_PENDING_NEW":                        5,
		"BROKER_ORDER_NEW":                                6,
		"SMART_CONTRACT_ORDER_PLACED":                     7,
		"BROKER_ORDER_PARTIALLY_FILLED":                   8,
		"SMART_CONTRACT_ORDER_PARTIALLY_FILLED_SUBMITTED": 9,
		"BROKER_ORDER_FILLED":                             10,
		"SMART_CONTRACT_ORDER_EXECUTED":                   11,
		"BROKER_ORDER_PRE_CANCEL_REQUESTED":               12,
		"BROKER_ORDER_CANCEL_REQUESTED":                   13,
		"BROKER_ORDER_CANCELED":                           14,
		"BROKER_ORDER_REFUSED":                            15,
		"BROKER_ORDER_EXPIRED":                            16,
		"SMART_CONTRACT_PRE_ORDER_CANCELLED":              17,
		"SMART_CONTRACT_ORDER_CANCELLED":                  18,
		"PROCESS_FINISHED":                                19,
		"SMART_CONTRACT_CANCEL_ORDER_REQUESTED":           20,
	}
)

func (x InternalOrderState) Enum() *InternalOrderState {
	p := new(InternalOrderState)
	*p = x
	return p
}

func (x InternalOrderState) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (InternalOrderState) Descriptor() protoreflect.EnumDescriptor {
	return file_order_proto_enumTypes[4].Descriptor()
}

func (InternalOrderState) Type() protoreflect.EnumType {
	return &file_order_proto_enumTypes[4]
}

func (x InternalOrderState) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use InternalOrderState.Descriptor instead.
func (InternalOrderState) EnumDescriptor() ([]byte, []int) {
	return file_order_proto_rawDescGZIP(), []int{4}
}

type OrderDetailType int32

const (
	// Changed not used to NOT_APPLICABLE_ORDER_DETAIL_TYPE to accomodate for withdraw/deposit orders
	OrderDetailType_NOT_APPLICABLE_ORDER_DETAIL_TYPE OrderDetailType = 0
	OrderDetailType_ORDER_DETAIL_LIMIT               OrderDetailType = 1
	OrderDetailType_ORDER_DETAIL_MARKET              OrderDetailType = 2 // Ignores LimitPrice, executes at market price
	OrderDetailType_ORDER_DETAIL_STOP_LOSS           OrderDetailType = 3 // Uses LimitPrice as the stop loss threshold
)

// Enum value maps for OrderDetailType.
var (
	OrderDetailType_name = map[int32]string{
		0: "NOT_APPLICABLE_ORDER_DETAIL_TYPE",
		1: "ORDER_DETAIL_LIMIT",
		2: "ORDER_DETAIL_MARKET",
		3: "ORDER_DETAIL_STOP_LOSS",
	}
	OrderDetailType_value = map[string]int32{
		"NOT_APPLICABLE_ORDER_DETAIL_TYPE": 0,
		"ORDER_DETAIL_LIMIT":               1,
		"ORDER_DETAIL_MARKET":              2,
		"ORDER_DETAIL_STOP_LOSS":           3,
	}
)

func (x OrderDetailType) Enum() *OrderDetailType {
	p := new(OrderDetailType)
	*p = x
	return p
}

func (x OrderDetailType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (OrderDetailType) Descriptor() protoreflect.EnumDescriptor {
	return file_order_proto_enumTypes[5].Descriptor()
}

func (OrderDetailType) Type() protoreflect.EnumType {
	return &file_order_proto_enumTypes[5]
}

func (x OrderDetailType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use OrderDetailType.Descriptor instead.
func (OrderDetailType) EnumDescriptor() ([]byte, []int) {
	return file_order_proto_rawDescGZIP(), []int{5}
}

type ReceiverType int32

const (
	ReceiverType_EMAIL    ReceiverType = 0
	ReceiverType_TX       ReceiverType = 1
	ReceiverType_ETHEREUM ReceiverType = 2
	ReceiverType_SOLANA   ReceiverType = 3
)

// Enum value maps for ReceiverType.
var (
	ReceiverType_name = map[int32]string{
		0: "EMAIL",
		1: "TX",
		2: "ETHEREUM",
		3: "SOLANA",
	}
	ReceiverType_value = map[string]int32{
		"EMAIL":    0,
		"TX":       1,
		"ETHEREUM": 2,
		"SOLANA":   3,
	}
)

func (x ReceiverType) Enum() *ReceiverType {
	p := new(ReceiverType)
	*p = x
	return p
}

func (x ReceiverType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ReceiverType) Descriptor() protoreflect.EnumDescriptor {
	return file_order_proto_enumTypes[6].Descriptor()
}

func (ReceiverType) Type() protoreflect.EnumType {
	return &file_order_proto_enumTypes[6]
}

func (x ReceiverType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ReceiverType.Descriptor instead.
func (ReceiverType) EnumDescriptor() ([]byte, []int) {
	return file_order_proto_rawDescGZIP(), []int{6}
}

// Order key: OrderID-SmartContractAddr-Network (1 entry per order)
// Order history key(id): numeric ID auto-generated by datastore (M entries per order)
type Order struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	Network            metadata.Network       `protobuf:"varint,1,opt,name=Network,proto3,enum=metadata.Network" json:"Network,omitempty"`
	SmartContractAddr  string                 `protobuf:"bytes,2,opt,name=SmartContractAddr,proto3" json:"SmartContractAddr,omitempty"`
	Instruction        *OrderInstruction      `protobuf:"bytes,3,opt,name=Instruction,proto3" json:"Instruction,omitempty"` // Snapshot of the order in the smart contract
	CreatedAt          *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=CreatedAt,proto3" json:"CreatedAt,omitempty"`
	UpdatedAt          *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=UpdatedAt,proto3" json:"UpdatedAt,omitempty"`
	TransactionType    TransactionType        `protobuf:"varint,6,opt,name=TransactionType,proto3,enum=order.TransactionType" json:"TransactionType,omitempty"`
	TXID               string                 `protobuf:"bytes,7,opt,name=TXID,proto3" json:"TXID,omitempty"` // Unique Key in the datastore
	GasFee             int64                  `protobuf:"varint,8,opt,name=GasFee,proto3" json:"GasFee,omitempty"`
	GasFeeUSD          *float64               `protobuf:"fixed64,9,opt,name=GasFeeUSD,proto3,oneof" json:"GasFeeUSD,omitempty"`
	DetectedAt         *timestamppb.Timestamp `protobuf:"bytes,10,opt,name=DetectedAt,proto3" json:"DetectedAt,omitempty"`
	Height             int64                  `protobuf:"varint,11,opt,name=Height,proto3" json:"Height,omitempty"`
	InternalOrderState InternalOrderState     `protobuf:"varint,12,opt,name=InternalOrderState,proto3,enum=order.InternalOrderState" json:"InternalOrderState,omitempty"`
	BrokerOrderDetails *BrokerOrderDetails    `protobuf:"bytes,13,opt,name=BrokerOrderDetails,proto3,oneof" json:"BrokerOrderDetails,omitempty"` // Matches data on SmartContractAddr, orderdetails.OrderID and network
	// Bookkeeping: did we process this event from broker smart contract order log?
	ProcessInfo    *order_properties.ProcessInfo `protobuf:"bytes,14,opt,name=ProcessInfo,proto3,oneof" json:"ProcessInfo,omitempty"`
	InstanceID     *string                       `protobuf:"bytes,15,opt,name=InstanceID,proto3,oneof" json:"InstanceID,omitempty"` // ID used by logs to identify the instance where the log was created/ processed
	BlockTime      *timestamppb.Timestamp        `protobuf:"bytes,16,opt,name=BlockTime,proto3" json:"BlockTime,omitempty"`
	Sequence       int64                         `protobuf:"varint,17,opt,name=Sequence,proto3" json:"Sequence,omitempty"` // Sequence
	OrganizationID string                        `protobuf:"bytes,18,opt,name=OrganizationID,proto3" json:"OrganizationID,omitempty"`
	UserID         string                        `protobuf:"bytes,19,opt,name=UserID,proto3" json:"UserID,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *Order) Reset() {
	*x = Order{}
	mi := &file_order_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Order) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Order) ProtoMessage() {}

func (x *Order) ProtoReflect() protoreflect.Message {
	mi := &file_order_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Order.ProtoReflect.Descriptor instead.
func (*Order) Descriptor() ([]byte, []int) {
	return file_order_proto_rawDescGZIP(), []int{0}
}

func (x *Order) GetNetwork() metadata.Network {
	if x != nil {
		return x.Network
	}
	return metadata.Network(0)
}

func (x *Order) GetSmartContractAddr() string {
	if x != nil {
		return x.SmartContractAddr
	}
	return ""
}

func (x *Order) GetInstruction() *OrderInstruction {
	if x != nil {
		return x.Instruction
	}
	return nil
}

func (x *Order) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *Order) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

func (x *Order) GetTransactionType() TransactionType {
	if x != nil {
		return x.TransactionType
	}
	return TransactionType_NOT_USED_TRANSACTION_TYPE
}

func (x *Order) GetTXID() string {
	if x != nil {
		return x.TXID
	}
	return ""
}

func (x *Order) GetGasFee() int64 {
	if x != nil {
		return x.GasFee
	}
	return 0
}

func (x *Order) GetGasFeeUSD() float64 {
	if x != nil && x.GasFeeUSD != nil {
		return *x.GasFeeUSD
	}
	return 0
}

func (x *Order) GetDetectedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.DetectedAt
	}
	return nil
}

func (x *Order) GetHeight() int64 {
	if x != nil {
		return x.Height
	}
	return 0
}

func (x *Order) GetInternalOrderState() InternalOrderState {
	if x != nil {
		return x.InternalOrderState
	}
	return InternalOrderState_NOT_APPLICABLE_INTERNAL_ORDER_STATE
}

func (x *Order) GetBrokerOrderDetails() *BrokerOrderDetails {
	if x != nil {
		return x.BrokerOrderDetails
	}
	return nil
}

func (x *Order) GetProcessInfo() *order_properties.ProcessInfo {
	if x != nil {
		return x.ProcessInfo
	}
	return nil
}

func (x *Order) GetInstanceID() string {
	if x != nil && x.InstanceID != nil {
		return *x.InstanceID
	}
	return ""
}

func (x *Order) GetBlockTime() *timestamppb.Timestamp {
	if x != nil {
		return x.BlockTime
	}
	return nil
}

func (x *Order) GetSequence() int64 {
	if x != nil {
		return x.Sequence
	}
	return 0
}

func (x *Order) GetOrganizationID() string {
	if x != nil {
		return x.OrganizationID
	}
	return ""
}

func (x *Order) GetUserID() string {
	if x != nil {
		return x.UserID
	}
	return ""
}

// Same structure as Order in the Smart Contract
type OrderInstruction struct {
	state              protoimpl.MessageState        `protogen:"open.v1"`
	OrderID            int64                         `protobuf:"varint,1,opt,name=OrderID,proto3" json:"OrderID,omitempty"` // Google datastore supports int64, not uint64, which is the used in the smart contract
	Creator            string                        `protobuf:"bytes,2,opt,name=Creator,proto3" json:"Creator,omitempty"`  // Sender in the message from Coreum
	Denom              string                        `protobuf:"bytes,3,opt,name=Denom,proto3" json:"Denom,omitempty"`
	Amount             int64                         `protobuf:"varint,4,opt,name=Amount,proto3" json:"Amount,omitempty"`
	AmountExp          int32                         `protobuf:"varint,5,opt,name=AmountExp,proto3" json:"AmountExp,omitempty"`
	LimitPrice         int64                         `protobuf:"varint,6,opt,name=LimitPrice,proto3" json:"LimitPrice,omitempty"`       // DEPRECATED: Use LimitPriceFloat instead for new smart contract format
	LimitPriceExp      int32                         `protobuf:"varint,7,opt,name=LimitPriceExp,proto3" json:"LimitPriceExp,omitempty"` // DEPRECATED: Use LimitPriceFloat instead for new smart contract format
	FillOrKill         bool                          `protobuf:"varint,8,opt,name=FillOrKill,proto3" json:"FillOrKill,omitempty"`       // DEPRECATED: Use TimeInForce instead as it's more flexible and RQD does not support it (2025-08-18)
	ExpiresAt          *string                       `protobuf:"bytes,9,opt,name=ExpiresAt,proto3,oneof" json:"ExpiresAt,omitempty"`    // In ISO-8601 Zulu format (e.g., "2024-02-29T23:59:59Z")
	OrderDetailType    OrderDetailType               `protobuf:"varint,10,opt,name=OrderDetailType,proto3,enum=order.OrderDetailType" json:"OrderDetailType,omitempty"`
	Hold               *Hold                         `protobuf:"bytes,11,opt,name=Hold,proto3,oneof" json:"Hold,omitempty"`
	FundsSent          *Coin                         `protobuf:"bytes,12,opt,name=FundsSent,proto3" json:"FundsSent,omitempty"`
	OrderType          order_properties.OrderType    `protobuf:"varint,13,opt,name=OrderType,proto3,enum=orderproperties.OrderType" json:"OrderType,omitempty"`
	OrderState         *OrderState                   `protobuf:"bytes,14,opt,name=OrderState,proto3" json:"OrderState,omitempty"`
	PaymentState       *PaymentState                 `protobuf:"varint,15,opt,name=PaymentState,proto3,enum=order.PaymentState,oneof" json:"PaymentState,omitempty"`
	AmountExecuted     *int64                        `protobuf:"varint,16,opt,name=AmountExecuted,proto3,oneof" json:"AmountExecuted,omitempty"`
	AmountExecutedExp  *int32                        `protobuf:"varint,17,opt,name=AmountExecutedExp,proto3,oneof" json:"AmountExecutedExp,omitempty"`
	UsedFundsAmount    *int64                        `protobuf:"varint,18,opt,name=UsedFundsAmount,proto3,oneof" json:"UsedFundsAmount,omitempty"`
	UsedFundsAmountExp *int32                        `protobuf:"varint,19,opt,name=UsedFundsAmountExp,proto3,oneof" json:"UsedFundsAmountExp,omitempty"`
	Costs              *int64                        `protobuf:"varint,20,opt,name=Costs,proto3,oneof" json:"Costs,omitempty"`
	CostsExp           *int32                        `protobuf:"varint,21,opt,name=CostsExp,proto3,oneof" json:"CostsExp,omitempty"`
	TimeInForce        *order_properties.TimeInForce `protobuf:"varint,22,opt,name=TimeInForce,proto3,enum=orderproperties.TimeInForce,oneof" json:"TimeInForce,omitempty"`
	LimitPriceFloat    *float64                      `protobuf:"fixed64,23,opt,name=LimitPriceFloat,proto3,oneof" json:"LimitPriceFloat,omitempty"` // Direct float price from smart contract (e.g., 26.25)
	Receiver           *Receiver                     `protobuf:"bytes,24,opt,name=Receiver,proto3,oneof" json:"Receiver,omitempty"`                 // The address of the receiver, used for sending of funds. Receiver can also be an email address, tx address or blockchain addres from another blockchain.
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *OrderInstruction) Reset() {
	*x = OrderInstruction{}
	mi := &file_order_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OrderInstruction) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OrderInstruction) ProtoMessage() {}

func (x *OrderInstruction) ProtoReflect() protoreflect.Message {
	mi := &file_order_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OrderInstruction.ProtoReflect.Descriptor instead.
func (*OrderInstruction) Descriptor() ([]byte, []int) {
	return file_order_proto_rawDescGZIP(), []int{1}
}

func (x *OrderInstruction) GetOrderID() int64 {
	if x != nil {
		return x.OrderID
	}
	return 0
}

func (x *OrderInstruction) GetCreator() string {
	if x != nil {
		return x.Creator
	}
	return ""
}

func (x *OrderInstruction) GetDenom() string {
	if x != nil {
		return x.Denom
	}
	return ""
}

func (x *OrderInstruction) GetAmount() int64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

func (x *OrderInstruction) GetAmountExp() int32 {
	if x != nil {
		return x.AmountExp
	}
	return 0
}

func (x *OrderInstruction) GetLimitPrice() int64 {
	if x != nil {
		return x.LimitPrice
	}
	return 0
}

func (x *OrderInstruction) GetLimitPriceExp() int32 {
	if x != nil {
		return x.LimitPriceExp
	}
	return 0
}

func (x *OrderInstruction) GetFillOrKill() bool {
	if x != nil {
		return x.FillOrKill
	}
	return false
}

func (x *OrderInstruction) GetExpiresAt() string {
	if x != nil && x.ExpiresAt != nil {
		return *x.ExpiresAt
	}
	return ""
}

func (x *OrderInstruction) GetOrderDetailType() OrderDetailType {
	if x != nil {
		return x.OrderDetailType
	}
	return OrderDetailType_NOT_APPLICABLE_ORDER_DETAIL_TYPE
}

func (x *OrderInstruction) GetHold() *Hold {
	if x != nil {
		return x.Hold
	}
	return nil
}

func (x *OrderInstruction) GetFundsSent() *Coin {
	if x != nil {
		return x.FundsSent
	}
	return nil
}

func (x *OrderInstruction) GetOrderType() order_properties.OrderType {
	if x != nil {
		return x.OrderType
	}
	return order_properties.OrderType(0)
}

func (x *OrderInstruction) GetOrderState() *OrderState {
	if x != nil {
		return x.OrderState
	}
	return nil
}

func (x *OrderInstruction) GetPaymentState() PaymentState {
	if x != nil && x.PaymentState != nil {
		return *x.PaymentState
	}
	return PaymentState_NOT_USED_PAYMENT_STATE
}

func (x *OrderInstruction) GetAmountExecuted() int64 {
	if x != nil && x.AmountExecuted != nil {
		return *x.AmountExecuted
	}
	return 0
}

func (x *OrderInstruction) GetAmountExecutedExp() int32 {
	if x != nil && x.AmountExecutedExp != nil {
		return *x.AmountExecutedExp
	}
	return 0
}

func (x *OrderInstruction) GetUsedFundsAmount() int64 {
	if x != nil && x.UsedFundsAmount != nil {
		return *x.UsedFundsAmount
	}
	return 0
}

func (x *OrderInstruction) GetUsedFundsAmountExp() int32 {
	if x != nil && x.UsedFundsAmountExp != nil {
		return *x.UsedFundsAmountExp
	}
	return 0
}

func (x *OrderInstruction) GetCosts() int64 {
	if x != nil && x.Costs != nil {
		return *x.Costs
	}
	return 0
}

func (x *OrderInstruction) GetCostsExp() int32 {
	if x != nil && x.CostsExp != nil {
		return *x.CostsExp
	}
	return 0
}

func (x *OrderInstruction) GetTimeInForce() order_properties.TimeInForce {
	if x != nil && x.TimeInForce != nil {
		return *x.TimeInForce
	}
	return order_properties.TimeInForce(0)
}

func (x *OrderInstruction) GetLimitPriceFloat() float64 {
	if x != nil && x.LimitPriceFloat != nil {
		return *x.LimitPriceFloat
	}
	return 0
}

func (x *OrderInstruction) GetReceiver() *Receiver {
	if x != nil {
		return x.Receiver
	}
	return nil
}

type Orders struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Orders        []*Order               `protobuf:"bytes,1,rep,name=Orders,proto3" json:"Orders,omitempty"`
	Offset        *int32                 `protobuf:"varint,2,opt,name=Offset,proto3,oneof" json:"Offset,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Orders) Reset() {
	*x = Orders{}
	mi := &file_order_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Orders) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Orders) ProtoMessage() {}

func (x *Orders) ProtoReflect() protoreflect.Message {
	mi := &file_order_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Orders.ProtoReflect.Descriptor instead.
func (*Orders) Descriptor() ([]byte, []int) {
	return file_order_proto_rawDescGZIP(), []int{2}
}

func (x *Orders) GetOrders() []*Order {
	if x != nil {
		return x.Orders
	}
	return nil
}

func (x *Orders) GetOffset() int32 {
	if x != nil && x.Offset != nil {
		return *x.Offset
	}
	return 0
}

type Hold struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Denom         string                 `protobuf:"bytes,1,opt,name=Denom,proto3" json:"Denom,omitempty"`
	Amount        int64                  `protobuf:"varint,2,opt,name=Amount,proto3" json:"Amount,omitempty"`
	AmountExp     int32                  `protobuf:"varint,3,opt,name=AmountExp,proto3" json:"AmountExp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Hold) Reset() {
	*x = Hold{}
	mi := &file_order_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Hold) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Hold) ProtoMessage() {}

func (x *Hold) ProtoReflect() protoreflect.Message {
	mi := &file_order_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Hold.ProtoReflect.Descriptor instead.
func (*Hold) Descriptor() ([]byte, []int) {
	return file_order_proto_rawDescGZIP(), []int{3}
}

func (x *Hold) GetDenom() string {
	if x != nil {
		return x.Denom
	}
	return ""
}

func (x *Hold) GetAmount() int64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

func (x *Hold) GetAmountExp() int32 {
	if x != nil {
		return x.AmountExp
	}
	return 0
}

type Coin struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Denom         string                 `protobuf:"bytes,1,opt,name=Denom,proto3" json:"Denom,omitempty"`
	Amount        int64                  `protobuf:"varint,2,opt,name=Amount,proto3" json:"Amount,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Coin) Reset() {
	*x = Coin{}
	mi := &file_order_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Coin) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Coin) ProtoMessage() {}

func (x *Coin) ProtoReflect() protoreflect.Message {
	mi := &file_order_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Coin.ProtoReflect.Descriptor instead.
func (*Coin) Descriptor() ([]byte, []int) {
	return file_order_proto_rawDescGZIP(), []int{4}
}

func (x *Coin) GetDenom() string {
	if x != nil {
		return x.Denom
	}
	return ""
}

func (x *Coin) GetAmount() int64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

type OrderState struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	OrderStateType   OrderStateType         `protobuf:"varint,1,opt,name=OrderStateType,proto3,enum=order.OrderStateType" json:"OrderStateType,omitempty"`
	OrderCancelledBy *OrderCancelledBy      `protobuf:"varint,2,opt,name=OrderCancelledBy,proto3,enum=order.OrderCancelledBy,oneof" json:"OrderCancelledBy,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *OrderState) Reset() {
	*x = OrderState{}
	mi := &file_order_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OrderState) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OrderState) ProtoMessage() {}

func (x *OrderState) ProtoReflect() protoreflect.Message {
	mi := &file_order_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OrderState.ProtoReflect.Descriptor instead.
func (*OrderState) Descriptor() ([]byte, []int) {
	return file_order_proto_rawDescGZIP(), []int{5}
}

func (x *OrderState) GetOrderStateType() OrderStateType {
	if x != nil {
		return x.OrderStateType
	}
	return OrderStateType_NOT_USED_ORDER_STATE_TYPE
}

func (x *OrderState) GetOrderCancelledBy() OrderCancelledBy {
	if x != nil && x.OrderCancelledBy != nil {
		return *x.OrderCancelledBy
	}
	return OrderCancelledBy_NOT_USED_ORDER_CANCEL_BY
}

type Receiver struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Address       string                 `protobuf:"bytes,1,opt,name=Address,proto3" json:"Address,omitempty"`                    // The address of the receiver, used for sending of funds.
	Type          ReceiverType           `protobuf:"varint,2,opt,name=Type,proto3,enum=order.ReceiverType" json:"Type,omitempty"` // The type of the receiver, e.g. email, tx address, blockchain address from another blockchain.
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Receiver) Reset() {
	*x = Receiver{}
	mi := &file_order_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Receiver) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Receiver) ProtoMessage() {}

func (x *Receiver) ProtoReflect() protoreflect.Message {
	mi := &file_order_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Receiver.ProtoReflect.Descriptor instead.
func (*Receiver) Descriptor() ([]byte, []int) {
	return file_order_proto_rawDescGZIP(), []int{6}
}

func (x *Receiver) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

func (x *Receiver) GetType() ReceiverType {
	if x != nil {
		return x.Type
	}
	return ReceiverType_EMAIL
}

var File_order_proto protoreflect.FileDescriptor

const file_order_proto_rawDesc = "" +
	"\n" +
	"\vorder.proto\x12\x05order\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\fbroker.proto\x1a9sologenic/com-fs-utils-lib/models/metadata/metadata.proto\x1aIsologenic/com-fs-utils-lib/models/order-properties/order-properties.proto\"\xd5\a\n" +
	"\x05Order\x12+\n" +
	"\aNetwork\x18\x01 \x01(\x0e2\x11.metadata.NetworkR\aNetwork\x12,\n" +
	"\x11SmartContractAddr\x18\x02 \x01(\tR\x11SmartContractAddr\x129\n" +
	"\vInstruction\x18\x03 \x01(\v2\x17.order.OrderInstructionR\vInstruction\x128\n" +
	"\tCreatedAt\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\tCreatedAt\x128\n" +
	"\tUpdatedAt\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\tUpdatedAt\x12@\n" +
	"\x0fTransactionType\x18\x06 \x01(\x0e2\x16.order.TransactionTypeR\x0fTransactionType\x12\x12\n" +
	"\x04TXID\x18\a \x01(\tR\x04TXID\x12\x16\n" +
	"\x06GasFee\x18\b \x01(\x03R\x06GasFee\x12!\n" +
	"\tGasFeeUSD\x18\t \x01(\x01H\x00R\tGasFeeUSD\x88\x01\x01\x12:\n" +
	"\n" +
	"DetectedAt\x18\n" +
	" \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"DetectedAt\x12\x16\n" +
	"\x06Height\x18\v \x01(\x03R\x06Height\x12I\n" +
	"\x12InternalOrderState\x18\f \x01(\x0e2\x19.order.InternalOrderStateR\x12InternalOrderState\x12N\n" +
	"\x12BrokerOrderDetails\x18\r \x01(\v2\x19.order.BrokerOrderDetailsH\x01R\x12BrokerOrderDetails\x88\x01\x01\x12C\n" +
	"\vProcessInfo\x18\x0e \x01(\v2\x1c.orderproperties.ProcessInfoH\x02R\vProcessInfo\x88\x01\x01\x12#\n" +
	"\n" +
	"InstanceID\x18\x0f \x01(\tH\x03R\n" +
	"InstanceID\x88\x01\x01\x128\n" +
	"\tBlockTime\x18\x10 \x01(\v2\x1a.google.protobuf.TimestampR\tBlockTime\x12\x1a\n" +
	"\bSequence\x18\x11 \x01(\x03R\bSequence\x12&\n" +
	"\x0eOrganizationID\x18\x12 \x01(\tR\x0eOrganizationID\x12\x16\n" +
	"\x06UserID\x18\x13 \x01(\tR\x06UserIDB\f\n" +
	"\n" +
	"_GasFeeUSDB\x15\n" +
	"\x13_BrokerOrderDetailsB\x0e\n" +
	"\f_ProcessInfoB\r\n" +
	"\v_InstanceID\"\xc3\t\n" +
	"\x10OrderInstruction\x12\x18\n" +
	"\aOrderID\x18\x01 \x01(\x03R\aOrderID\x12\x18\n" +
	"\aCreator\x18\x02 \x01(\tR\aCreator\x12\x14\n" +
	"\x05Denom\x18\x03 \x01(\tR\x05Denom\x12\x16\n" +
	"\x06Amount\x18\x04 \x01(\x03R\x06Amount\x12\x1c\n" +
	"\tAmountExp\x18\x05 \x01(\x05R\tAmountExp\x12\x1e\n" +
	"\n" +
	"LimitPrice\x18\x06 \x01(\x03R\n" +
	"LimitPrice\x12$\n" +
	"\rLimitPriceExp\x18\a \x01(\x05R\rLimitPriceExp\x12\x1e\n" +
	"\n" +
	"FillOrKill\x18\b \x01(\bR\n" +
	"FillOrKill\x12!\n" +
	"\tExpiresAt\x18\t \x01(\tH\x00R\tExpiresAt\x88\x01\x01\x12@\n" +
	"\x0fOrderDetailType\x18\n" +
	" \x01(\x0e2\x16.order.OrderDetailTypeR\x0fOrderDetailType\x12$\n" +
	"\x04Hold\x18\v \x01(\v2\v.order.HoldH\x01R\x04Hold\x88\x01\x01\x12)\n" +
	"\tFundsSent\x18\f \x01(\v2\v.order.CoinR\tFundsSent\x128\n" +
	"\tOrderType\x18\r \x01(\x0e2\x1a.orderproperties.OrderTypeR\tOrderType\x121\n" +
	"\n" +
	"OrderState\x18\x0e \x01(\v2\x11.order.OrderStateR\n" +
	"OrderState\x12<\n" +
	"\fPaymentState\x18\x0f \x01(\x0e2\x13.order.PaymentStateH\x02R\fPaymentState\x88\x01\x01\x12+\n" +
	"\x0eAmountExecuted\x18\x10 \x01(\x03H\x03R\x0eAmountExecuted\x88\x01\x01\x121\n" +
	"\x11AmountExecutedExp\x18\x11 \x01(\x05H\x04R\x11AmountExecutedExp\x88\x01\x01\x12-\n" +
	"\x0fUsedFundsAmount\x18\x12 \x01(\x03H\x05R\x0fUsedFundsAmount\x88\x01\x01\x123\n" +
	"\x12UsedFundsAmountExp\x18\x13 \x01(\x05H\x06R\x12UsedFundsAmountExp\x88\x01\x01\x12\x19\n" +
	"\x05Costs\x18\x14 \x01(\x03H\aR\x05Costs\x88\x01\x01\x12\x1f\n" +
	"\bCostsExp\x18\x15 \x01(\x05H\bR\bCostsExp\x88\x01\x01\x12C\n" +
	"\vTimeInForce\x18\x16 \x01(\x0e2\x1c.orderproperties.TimeInForceH\tR\vTimeInForce\x88\x01\x01\x12-\n" +
	"\x0fLimitPriceFloat\x18\x17 \x01(\x01H\n" +
	"R\x0fLimitPriceFloat\x88\x01\x01\x120\n" +
	"\bReceiver\x18\x18 \x01(\v2\x0f.order.ReceiverH\vR\bReceiver\x88\x01\x01B\f\n" +
	"\n" +
	"_ExpiresAtB\a\n" +
	"\x05_HoldB\x0f\n" +
	"\r_PaymentStateB\x11\n" +
	"\x0f_AmountExecutedB\x14\n" +
	"\x12_AmountExecutedExpB\x12\n" +
	"\x10_UsedFundsAmountB\x15\n" +
	"\x13_UsedFundsAmountExpB\b\n" +
	"\x06_CostsB\v\n" +
	"\t_CostsExpB\x0e\n" +
	"\f_TimeInForceB\x12\n" +
	"\x10_LimitPriceFloatB\v\n" +
	"\t_Receiver\"V\n" +
	"\x06Orders\x12$\n" +
	"\x06Orders\x18\x01 \x03(\v2\f.order.OrderR\x06Orders\x12\x1b\n" +
	"\x06Offset\x18\x02 \x01(\x05H\x00R\x06Offset\x88\x01\x01B\t\n" +
	"\a_Offset\"R\n" +
	"\x04Hold\x12\x14\n" +
	"\x05Denom\x18\x01 \x01(\tR\x05Denom\x12\x16\n" +
	"\x06Amount\x18\x02 \x01(\x03R\x06Amount\x12\x1c\n" +
	"\tAmountExp\x18\x03 \x01(\x05R\tAmountExp\"4\n" +
	"\x04Coin\x12\x14\n" +
	"\x05Denom\x18\x01 \x01(\tR\x05Denom\x12\x16\n" +
	"\x06Amount\x18\x02 \x01(\x03R\x06Amount\"\xaa\x01\n" +
	"\n" +
	"OrderState\x12=\n" +
	"\x0eOrderStateType\x18\x01 \x01(\x0e2\x15.order.OrderStateTypeR\x0eOrderStateType\x12H\n" +
	"\x10OrderCancelledBy\x18\x02 \x01(\x0e2\x17.order.OrderCancelledByH\x00R\x10OrderCancelledBy\x88\x01\x01B\x13\n" +
	"\x11_OrderCancelledBy\"M\n" +
	"\bReceiver\x12\x18\n" +
	"\aAddress\x18\x01 \x01(\tR\aAddress\x12'\n" +
	"\x04Type\x18\x02 \x01(\x0e2\x13.order.ReceiverTypeR\x04Type*\xd5\x01\n" +
	"\x0fTransactionType\x12\x1d\n" +
	"\x19NOT_USED_TRANSACTION_TYPE\x10\x00\x12\f\n" +
	"\bPURCHASE\x10\x01\x12\b\n" +
	"\x04SELL\x10\x02\x12\x18\n" +
	"\x14REQUEST_ORDER_CANCEL\x10\x03\x12\x11\n" +
	"\rEXECUTE_ORDER\x10\x04\x12\r\n" +
	"\tPAY_ORDER\x10\x05\x12\x19\n" +
	"\x15REQUEST_REATTESTATION\x10\x06\x12\v\n" +
	"\aDEPOSIT\x10\a\x12\x0e\n" +
	"\n" +
	"WITHDRAWAL\x10\b\x12\x17\n" +
	"\x13USDC_USD_CONVERSION\x10\t*\xa2\x01\n" +
	"\x0eOrderStateType\x12\x1d\n" +
	"\x19NOT_USED_ORDER_STATE_TYPE\x10\x00\x12\b\n" +
	"\x04OPEN\x10\x01\x12\n" +
	"\n" +
	"\x06PLACED\x10\x02\x12\x16\n" +
	"\x12PARTIALLY_EXECUTED\x10\x03\x12\f\n" +
	"\bEXECUTED\x10\x04\x12\x1a\n" +
	"\x16CANCELLATION_REQUESTED\x10\x05\x12\r\n" +
	"\tCANCELLED\x10\x06\x12\n" +
	"\n" +
	"\x06FAILED\x10\a*g\n" +
	"\x10OrderCancelledBy\x12\x1c\n" +
	"\x18NOT_USED_ORDER_CANCEL_BY\x10\x00\x12\x18\n" +
	"\x14SMART_CONTRACT_OWNER\x10\x01\x12\b\n" +
	"\x04USER\x10\x02\x12\x11\n" +
	"\rBROKER_ORACLE\x10\x03*B\n" +
	"\fPaymentState\x12\x1a\n" +
	"\x16NOT_USED_PAYMENT_STATE\x10\x00\x12\f\n" +
	"\bNOT_PAID\x10\x01\x12\b\n" +
	"\x04PAID\x10\x02*\xc9\x05\n" +
	"\x12InternalOrderState\x12'\n" +
	"#NOT_APPLICABLE_INTERNAL_ORDER_STATE\x10\x00\x12$\n" +
	" SMART_CONTRACT_NEW_ORDER_CREATED\x10\x01\x12\x1e\n" +
	"\x1aBROKER_ORDER_PRE_SUBMITTED\x10\x02\x12\x1a\n" +
	"\x16BROKER_ORDER_SUBMITTED\x10\x03\x12\x19\n" +
	"\x15BROKER_ORDER_ACCEPTED\x10\x04\x12\x1c\n" +
	"\x18BROKER_ORDER_PENDING_NEW\x10\x05\x12\x14\n" +
	"\x10BROKER_ORDER_NEW\x10\x06\x12\x1f\n" +
	"\x1bSMART_CONTRACT_ORDER_PLACED\x10\a\x12!\n" +
	"\x1dBROKER_ORDER_PARTIALLY_FILLED\x10\b\x123\n" +
	"/SMART_CONTRACT_ORDER_PARTIALLY_FILLED_SUBMITTED\x10\t\x12\x17\n" +
	"\x13BROKER_ORDER_FILLED\x10\n" +
	"\x12!\n" +
	"\x1dSMART_CONTRACT_ORDER_EXECUTED\x10\v\x12%\n" +
	"!BROKER_ORDER_PRE_CANCEL_REQUESTED\x10\f\x12!\n" +
	"\x1dBROKER_ORDER_CANCEL_REQUESTED\x10\r\x12\x19\n" +
	"\x15BROKER_ORDER_CANCELED\x10\x0e\x12\x18\n" +
	"\x14BROKER_ORDER_REFUSED\x10\x0f\x12\x18\n" +
	"\x14BROKER_ORDER_EXPIRED\x10\x10\x12&\n" +
	"\"SMART_CONTRACT_PRE_ORDER_CANCELLED\x10\x11\x12\"\n" +
	"\x1eSMART_CONTRACT_ORDER_CANCELLED\x10\x12\x12\x14\n" +
	"\x10PROCESS_FINISHED\x10\x13\x12)\n" +
	"%SMART_CONTRACT_CANCEL_ORDER_REQUESTED\x10\x14*\x84\x01\n" +
	"\x0fOrderDetailType\x12$\n" +
	" NOT_APPLICABLE_ORDER_DETAIL_TYPE\x10\x00\x12\x16\n" +
	"\x12ORDER_DETAIL_LIMIT\x10\x01\x12\x17\n" +
	"\x13ORDER_DETAIL_MARKET\x10\x02\x12\x1a\n" +
	"\x16ORDER_DETAIL_STOP_LOSS\x10\x03*;\n" +
	"\fReceiverType\x12\t\n" +
	"\x05EMAIL\x10\x00\x12\x06\n" +
	"\x02TX\x10\x01\x12\f\n" +
	"\bETHEREUM\x10\x02\x12\n" +
	"\n" +
	"\x06SOLANA\x10\x03B/Z-github.com/sologenic/com-fs-order-model;orderb\x06proto3"

var (
	file_order_proto_rawDescOnce sync.Once
	file_order_proto_rawDescData []byte
)

func file_order_proto_rawDescGZIP() []byte {
	file_order_proto_rawDescOnce.Do(func() {
		file_order_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_order_proto_rawDesc), len(file_order_proto_rawDesc)))
	})
	return file_order_proto_rawDescData
}

var file_order_proto_enumTypes = make([]protoimpl.EnumInfo, 7)
var file_order_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_order_proto_goTypes = []any{
	(TransactionType)(0),                 // 0: order.TransactionType
	(OrderStateType)(0),                  // 1: order.OrderStateType
	(OrderCancelledBy)(0),                // 2: order.OrderCancelledBy
	(PaymentState)(0),                    // 3: order.PaymentState
	(InternalOrderState)(0),              // 4: order.InternalOrderState
	(OrderDetailType)(0),                 // 5: order.OrderDetailType
	(ReceiverType)(0),                    // 6: order.ReceiverType
	(*Order)(nil),                        // 7: order.Order
	(*OrderInstruction)(nil),             // 8: order.OrderInstruction
	(*Orders)(nil),                       // 9: order.Orders
	(*Hold)(nil),                         // 10: order.Hold
	(*Coin)(nil),                         // 11: order.Coin
	(*OrderState)(nil),                   // 12: order.OrderState
	(*Receiver)(nil),                     // 13: order.Receiver
	(metadata.Network)(0),                // 14: metadata.Network
	(*timestamppb.Timestamp)(nil),        // 15: google.protobuf.Timestamp
	(*BrokerOrderDetails)(nil),           // 16: order.BrokerOrderDetails
	(*order_properties.ProcessInfo)(nil), // 17: orderproperties.ProcessInfo
	(order_properties.OrderType)(0),      // 18: orderproperties.OrderType
	(order_properties.TimeInForce)(0),    // 19: orderproperties.TimeInForce
}
var file_order_proto_depIdxs = []int32{
	14, // 0: order.Order.Network:type_name -> metadata.Network
	8,  // 1: order.Order.Instruction:type_name -> order.OrderInstruction
	15, // 2: order.Order.CreatedAt:type_name -> google.protobuf.Timestamp
	15, // 3: order.Order.UpdatedAt:type_name -> google.protobuf.Timestamp
	0,  // 4: order.Order.TransactionType:type_name -> order.TransactionType
	15, // 5: order.Order.DetectedAt:type_name -> google.protobuf.Timestamp
	4,  // 6: order.Order.InternalOrderState:type_name -> order.InternalOrderState
	16, // 7: order.Order.BrokerOrderDetails:type_name -> order.BrokerOrderDetails
	17, // 8: order.Order.ProcessInfo:type_name -> orderproperties.ProcessInfo
	15, // 9: order.Order.BlockTime:type_name -> google.protobuf.Timestamp
	5,  // 10: order.OrderInstruction.OrderDetailType:type_name -> order.OrderDetailType
	10, // 11: order.OrderInstruction.Hold:type_name -> order.Hold
	11, // 12: order.OrderInstruction.FundsSent:type_name -> order.Coin
	18, // 13: order.OrderInstruction.OrderType:type_name -> orderproperties.OrderType
	12, // 14: order.OrderInstruction.OrderState:type_name -> order.OrderState
	3,  // 15: order.OrderInstruction.PaymentState:type_name -> order.PaymentState
	19, // 16: order.OrderInstruction.TimeInForce:type_name -> orderproperties.TimeInForce
	13, // 17: order.OrderInstruction.Receiver:type_name -> order.Receiver
	7,  // 18: order.Orders.Orders:type_name -> order.Order
	1,  // 19: order.OrderState.OrderStateType:type_name -> order.OrderStateType
	2,  // 20: order.OrderState.OrderCancelledBy:type_name -> order.OrderCancelledBy
	6,  // 21: order.Receiver.Type:type_name -> order.ReceiverType
	22, // [22:22] is the sub-list for method output_type
	22, // [22:22] is the sub-list for method input_type
	22, // [22:22] is the sub-list for extension type_name
	22, // [22:22] is the sub-list for extension extendee
	0,  // [0:22] is the sub-list for field type_name
}

func init() { file_order_proto_init() }
func file_order_proto_init() {
	if File_order_proto != nil {
		return
	}
	file_broker_proto_init()
	file_order_proto_msgTypes[0].OneofWrappers = []any{}
	file_order_proto_msgTypes[1].OneofWrappers = []any{}
	file_order_proto_msgTypes[2].OneofWrappers = []any{}
	file_order_proto_msgTypes[5].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_order_proto_rawDesc), len(file_order_proto_rawDesc)),
			NumEnums:      7,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_order_proto_goTypes,
		DependencyIndexes: file_order_proto_depIdxs,
		EnumInfos:         file_order_proto_enumTypes,
		MessageInfos:      file_order_proto_msgTypes,
	}.Build()
	File_order_proto = out.File
	file_order_proto_goTypes = nil
	file_order_proto_depIdxs = nil
}
