syntax = "proto3";

package order;

option go_package = "github.com/sologenic/com-fs-order-model;order";

import "google/protobuf/empty.proto";
import "order.proto";
import "util.proto";
import "sologenic/com-fs-utils-lib/models/metadata/metadata.proto";

service OrderService {
    // Order
    rpc UpsertWithState(UpsertMessage) returns (OrderID) {}
    rpc GetByID(OrderID) returns (Order) {}
    rpc GetByKey(Key) returns (Order) {}
    rpc GetAll(OrderQuery) returns (Orders) {}
    rpc UpdateStep(OrderStepInstruction) returns (Order) {} // Transaction to lock and update order state
    // Disaster Recovery
    rpc GetAllUnfinished(google.protobuf.Empty) returns (Orders) {}
}

message UpsertMessage {
    Order Order = 1;
    OrderStepInstruction OrderStepInstruction = 2;
}

message OrderID {
    string TXID = 1;
    metadata.Network Network = 2;
}

message OrderQuery {
    metadata.Network Network = 1;
    optional int32 Offset = 2;
    optional string SmartContractAddr = 3;
    optional TransactionType TransactionType = 4;
    optional string TXID = 5;
    optional int64 Height = 6;
    optional InternalOrderState InternalOrderState = 7;
    optional ProcessInfo ProcessInfo = 8;
    // Fields in OrderInstruction
    optional string Creator = 9;
    optional int64 OrderID = 10;
    optional string Denom = 11;
    optional OrderType OrderType = 12;
    optional OrderStateType OrderStateType = 13;
    optional PaymentState PaymentState = 14;
}

message OrderStepInstruction {
    optional string Key = 1;
    optional Order Order = 2;
    repeated InternalOrderState MustHaveState = 3;
    InternalOrderState TargetState = 4;
}
