// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v1.181.2
//   protoc               v6.32.0
// source: order.proto

/* eslint-disable */
import Long from "long";
import _m0 from "protobufjs/minimal";
import { BrokerOrderDetails } from "./broker";
import { Timestamp } from "./google/protobuf/timestamp";
import { Network, networkFromJSON, networkToJSON } from "./sologenic/com-fs-utils-lib/models/metadata/metadata";
import {
  OrderType,
  orderTypeFromJSON,
  orderTypeToJSON,
  ProcessInfo,
  TimeInForce,
  timeInForceFromJSON,
  timeInForceToJSON,
} from "./sologenic/com-fs-utils-lib/models/order-properties/order-properties";

export const protobufPackage = "order";

/** Execution type(action) of the transactions */
export enum TransactionType {
  NOT_USED_TRANSACTION_TYPE = 0,
  /** PURCHASE - Specific type used for marking generic purchase orders, and for stock tokenization smart contract orders */
  PURCHASE = 1,
  /** SELL - Specific type used for marking generic sell orders, and for stock tokenization smart contract orders */
  SELL = 2,
  /** REQUEST_ORDER_CANCEL - Specific type used for marking generic request order cancel orders, and for stock tokenization smart contract orders */
  REQUEST_ORDER_CANCEL = 3,
  /** EXECUTE_ORDER - DEPRECATED */
  EXECUTE_ORDER = 4,
  /** PAY_ORDER - DEPRECATED */
  PAY_ORDER = 5,
  /** REQUEST_REATTESTATION - DEPRECATED */
  REQUEST_REATTESTATION = 6,
  /** DEPOSIT - Added for withdraw/deposit orders */
  DEPOSIT = 7,
  WITHDRAWAL = 8,
  /** USDC_USD_CONVERSION - Conversion of USDC to USD for deposit/withdrawal orders (by Alpaca) */
  USDC_USD_CONVERSION = 9,
  /** CROWDFUND_PURCHASE - Crowdfund transactions */
  CROWDFUND_PURCHASE = 20,
  /** CROWDFUND_BUYBACK - Buyback of a crowdfund */
  CROWDFUND_BUYBACK = 21,
  /** CROWDFUND_CANCEL - Cancel of a crowdfund */
  CROWDFUND_CANCEL = 22,
  /** CROWDFUND_DISTRIBUTION - Distribution of a crowdfund */
  CROWDFUND_DISTRIBUTION = 23,
  /** TOKEN_SALE_PURCHASE - Token-sale (e.g. price-supply) smart contract */
  TOKEN_SALE_PURCHASE = 30,
  /** TOKEN_SALE_BUYBACK - Buyback of a token-sale */
  TOKEN_SALE_BUYBACK = 31,
  UNRECOGNIZED = -1,
}

export function transactionTypeFromJSON(object: any): TransactionType {
  switch (object) {
    case 0:
    case "NOT_USED_TRANSACTION_TYPE":
      return TransactionType.NOT_USED_TRANSACTION_TYPE;
    case 1:
    case "PURCHASE":
      return TransactionType.PURCHASE;
    case 2:
    case "SELL":
      return TransactionType.SELL;
    case 3:
    case "REQUEST_ORDER_CANCEL":
      return TransactionType.REQUEST_ORDER_CANCEL;
    case 4:
    case "EXECUTE_ORDER":
      return TransactionType.EXECUTE_ORDER;
    case 5:
    case "PAY_ORDER":
      return TransactionType.PAY_ORDER;
    case 6:
    case "REQUEST_REATTESTATION":
      return TransactionType.REQUEST_REATTESTATION;
    case 7:
    case "DEPOSIT":
      return TransactionType.DEPOSIT;
    case 8:
    case "WITHDRAWAL":
      return TransactionType.WITHDRAWAL;
    case 9:
    case "USDC_USD_CONVERSION":
      return TransactionType.USDC_USD_CONVERSION;
    case 20:
    case "CROWDFUND_PURCHASE":
      return TransactionType.CROWDFUND_PURCHASE;
    case 21:
    case "CROWDFUND_BUYBACK":
      return TransactionType.CROWDFUND_BUYBACK;
    case 22:
    case "CROWDFUND_CANCEL":
      return TransactionType.CROWDFUND_CANCEL;
    case 23:
    case "CROWDFUND_DISTRIBUTION":
      return TransactionType.CROWDFUND_DISTRIBUTION;
    case 30:
    case "TOKEN_SALE_PURCHASE":
      return TransactionType.TOKEN_SALE_PURCHASE;
    case 31:
    case "TOKEN_SALE_BUYBACK":
      return TransactionType.TOKEN_SALE_BUYBACK;
    case -1:
    case "UNRECOGNIZED":
    default:
      return TransactionType.UNRECOGNIZED;
  }
}

export function transactionTypeToJSON(object: TransactionType): string {
  switch (object) {
    case TransactionType.NOT_USED_TRANSACTION_TYPE:
      return "NOT_USED_TRANSACTION_TYPE";
    case TransactionType.PURCHASE:
      return "PURCHASE";
    case TransactionType.SELL:
      return "SELL";
    case TransactionType.REQUEST_ORDER_CANCEL:
      return "REQUEST_ORDER_CANCEL";
    case TransactionType.EXECUTE_ORDER:
      return "EXECUTE_ORDER";
    case TransactionType.PAY_ORDER:
      return "PAY_ORDER";
    case TransactionType.REQUEST_REATTESTATION:
      return "REQUEST_REATTESTATION";
    case TransactionType.DEPOSIT:
      return "DEPOSIT";
    case TransactionType.WITHDRAWAL:
      return "WITHDRAWAL";
    case TransactionType.USDC_USD_CONVERSION:
      return "USDC_USD_CONVERSION";
    case TransactionType.CROWDFUND_PURCHASE:
      return "CROWDFUND_PURCHASE";
    case TransactionType.CROWDFUND_BUYBACK:
      return "CROWDFUND_BUYBACK";
    case TransactionType.CROWDFUND_CANCEL:
      return "CROWDFUND_CANCEL";
    case TransactionType.CROWDFUND_DISTRIBUTION:
      return "CROWDFUND_DISTRIBUTION";
    case TransactionType.TOKEN_SALE_PURCHASE:
      return "TOKEN_SALE_PURCHASE";
    case TransactionType.TOKEN_SALE_BUYBACK:
      return "TOKEN_SALE_BUYBACK";
    case TransactionType.UNRECOGNIZED:
    default:
      return "UNRECOGNIZED";
  }
}

export enum OrderStateType {
  NOT_USED_ORDER_STATE_TYPE = 0,
  OPEN = 1,
  PLACED = 2,
  PARTIALLY_EXECUTED = 3,
  EXECUTED = 4,
  CANCELLATION_REQUESTED = 5,
  CANCELLED = 6,
  FAILED = 7,
  UNRECOGNIZED = -1,
}

export function orderStateTypeFromJSON(object: any): OrderStateType {
  switch (object) {
    case 0:
    case "NOT_USED_ORDER_STATE_TYPE":
      return OrderStateType.NOT_USED_ORDER_STATE_TYPE;
    case 1:
    case "OPEN":
      return OrderStateType.OPEN;
    case 2:
    case "PLACED":
      return OrderStateType.PLACED;
    case 3:
    case "PARTIALLY_EXECUTED":
      return OrderStateType.PARTIALLY_EXECUTED;
    case 4:
    case "EXECUTED":
      return OrderStateType.EXECUTED;
    case 5:
    case "CANCELLATION_REQUESTED":
      return OrderStateType.CANCELLATION_REQUESTED;
    case 6:
    case "CANCELLED":
      return OrderStateType.CANCELLED;
    case 7:
    case "FAILED":
      return OrderStateType.FAILED;
    case -1:
    case "UNRECOGNIZED":
    default:
      return OrderStateType.UNRECOGNIZED;
  }
}

export function orderStateTypeToJSON(object: OrderStateType): string {
  switch (object) {
    case OrderStateType.NOT_USED_ORDER_STATE_TYPE:
      return "NOT_USED_ORDER_STATE_TYPE";
    case OrderStateType.OPEN:
      return "OPEN";
    case OrderStateType.PLACED:
      return "PLACED";
    case OrderStateType.PARTIALLY_EXECUTED:
      return "PARTIALLY_EXECUTED";
    case OrderStateType.EXECUTED:
      return "EXECUTED";
    case OrderStateType.CANCELLATION_REQUESTED:
      return "CANCELLATION_REQUESTED";
    case OrderStateType.CANCELLED:
      return "CANCELLED";
    case OrderStateType.FAILED:
      return "FAILED";
    case OrderStateType.UNRECOGNIZED:
    default:
      return "UNRECOGNIZED";
  }
}

export enum OrderCancelledBy {
  NOT_USED_ORDER_CANCEL_BY = 0,
  SMART_CONTRACT_OWNER = 1,
  USER = 2,
  BROKER_ORACLE = 3,
  UNRECOGNIZED = -1,
}

export function orderCancelledByFromJSON(object: any): OrderCancelledBy {
  switch (object) {
    case 0:
    case "NOT_USED_ORDER_CANCEL_BY":
      return OrderCancelledBy.NOT_USED_ORDER_CANCEL_BY;
    case 1:
    case "SMART_CONTRACT_OWNER":
      return OrderCancelledBy.SMART_CONTRACT_OWNER;
    case 2:
    case "USER":
      return OrderCancelledBy.USER;
    case 3:
    case "BROKER_ORACLE":
      return OrderCancelledBy.BROKER_ORACLE;
    case -1:
    case "UNRECOGNIZED":
    default:
      return OrderCancelledBy.UNRECOGNIZED;
  }
}

export function orderCancelledByToJSON(object: OrderCancelledBy): string {
  switch (object) {
    case OrderCancelledBy.NOT_USED_ORDER_CANCEL_BY:
      return "NOT_USED_ORDER_CANCEL_BY";
    case OrderCancelledBy.SMART_CONTRACT_OWNER:
      return "SMART_CONTRACT_OWNER";
    case OrderCancelledBy.USER:
      return "USER";
    case OrderCancelledBy.BROKER_ORACLE:
      return "BROKER_ORACLE";
    case OrderCancelledBy.UNRECOGNIZED:
    default:
      return "UNRECOGNIZED";
  }
}

export enum PaymentState {
  NOT_USED_PAYMENT_STATE = 0,
  NOT_PAID = 1,
  PAID = 2,
  UNRECOGNIZED = -1,
}

export function paymentStateFromJSON(object: any): PaymentState {
  switch (object) {
    case 0:
    case "NOT_USED_PAYMENT_STATE":
      return PaymentState.NOT_USED_PAYMENT_STATE;
    case 1:
    case "NOT_PAID":
      return PaymentState.NOT_PAID;
    case 2:
    case "PAID":
      return PaymentState.PAID;
    case -1:
    case "UNRECOGNIZED":
    default:
      return PaymentState.UNRECOGNIZED;
  }
}

export function paymentStateToJSON(object: PaymentState): string {
  switch (object) {
    case PaymentState.NOT_USED_PAYMENT_STATE:
      return "NOT_USED_PAYMENT_STATE";
    case PaymentState.NOT_PAID:
      return "NOT_PAID";
    case PaymentState.PAID:
      return "PAID";
    case PaymentState.UNRECOGNIZED:
    default:
      return "UNRECOGNIZED";
  }
}

export enum InternalOrderState {
  /** NOT_APPLICABLE_INTERNAL_ORDER_STATE - Changed not used to NOT_APPLICABLE_INTERNAL_ORDER_STATE to accomodate for withdraw/deposit orders */
  NOT_APPLICABLE_INTERNAL_ORDER_STATE = 0,
  /** SMART_CONTRACT_NEW_ORDER_CREATED - Initial state: Order is just created in the smart contract */
  SMART_CONTRACT_NEW_ORDER_CREATED = 1,
  /** BROKER_ORDER_PRE_SUBMITTED - Order place states */
  BROKER_ORDER_PRE_SUBMITTED = 2,
  /** BROKER_ORDER_SUBMITTED - order is submitted to the broker for further processing */
  BROKER_ORDER_SUBMITTED = 3,
  /** BROKER_ORDER_ACCEPTED - (afterhours) order has been received by the broker, but hasn’t yet been routed to the execution venue, OrderState in Broker: `accepted` */
  BROKER_ORDER_ACCEPTED = 4,
  /** BROKER_ORDER_PENDING_NEW - order has been routed to the exchange and it hasn't yet been confirmed by the exchange, OrderState in Broker: `pending_new` */
  BROKER_ORDER_PENDING_NEW = 5,
  /** BROKER_ORDER_NEW - order has been confirmed by the exchange and is active, OrderState in Broker: `new` */
  BROKER_ORDER_NEW = 6,
  /** SMART_CONTRACT_ORDER_PLACED - order has been placed in the smart contract, OrderState in SC: `placed` */
  SMART_CONTRACT_ORDER_PLACED = 7,
  /** BROKER_ORDER_PARTIALLY_FILLED - order has been partially filled, OrderState in Broker: `partially_filled` */
  BROKER_ORDER_PARTIALLY_FILLED = 8,
  /** SMART_CONTRACT_ORDER_PARTIALLY_FILLED_SUBMITTED - order has been partially executed in the smart contract, OrderState in SC: `partially_executed` */
  SMART_CONTRACT_ORDER_PARTIALLY_FILLED_SUBMITTED = 9,
  /** BROKER_ORDER_FILLED - order has been completely filled, OrderState in Broker: `filled` */
  BROKER_ORDER_FILLED = 10,
  /** SMART_CONTRACT_ORDER_EXECUTED - order has been executed in the smart contract, OrderState in SC: `executed` */
  SMART_CONTRACT_ORDER_EXECUTED = 11,
  BROKER_ORDER_PRE_CANCEL_REQUESTED = 12,
  /** BROKER_ORDER_CANCEL_REQUESTED - order cancellation request has been submitted to the broker */
  BROKER_ORDER_CANCEL_REQUESTED = 13,
  /** BROKER_ORDER_CANCELED - order has been canceled by the broker, OrderState in Broker: `canceled` */
  BROKER_ORDER_CANCELED = 14,
  /** BROKER_ORDER_REFUSED - order sent to the broker, but the broker refused to accept it */
  BROKER_ORDER_REFUSED = 15,
  /** BROKER_ORDER_EXPIRED - order has expired, OrderState in Broker: `expired` */
  BROKER_ORDER_EXPIRED = 16,
  SMART_CONTRACT_PRE_ORDER_CANCELLED = 17,
  /** SMART_CONTRACT_ORDER_CANCELLED - order has been cancelled in the smart contract, OrderState in SC: `cancelled` */
  SMART_CONTRACT_ORDER_CANCELLED = 18,
  SMART_CONTRACT_PRE_ORDER_EXPIRED = 21,
  /** SMART_CONTRACT_ORDER_EXPIRED - order has expired in the smart contract, OrderState in SC: `expired` */
  SMART_CONTRACT_ORDER_EXPIRED = 22,
  /** PROCESS_FINISHED - order has been processed and finished */
  PROCESS_FINISHED = 19,
  /** SMART_CONTRACT_CANCEL_ORDER_REQUESTED - Alternative scenarios */
  SMART_CONTRACT_CANCEL_ORDER_REQUESTED = 20,
  UNRECOGNIZED = -1,
}

export function internalOrderStateFromJSON(object: any): InternalOrderState {
  switch (object) {
    case 0:
    case "NOT_APPLICABLE_INTERNAL_ORDER_STATE":
      return InternalOrderState.NOT_APPLICABLE_INTERNAL_ORDER_STATE;
    case 1:
    case "SMART_CONTRACT_NEW_ORDER_CREATED":
      return InternalOrderState.SMART_CONTRACT_NEW_ORDER_CREATED;
    case 2:
    case "BROKER_ORDER_PRE_SUBMITTED":
      return InternalOrderState.BROKER_ORDER_PRE_SUBMITTED;
    case 3:
    case "BROKER_ORDER_SUBMITTED":
      return InternalOrderState.BROKER_ORDER_SUBMITTED;
    case 4:
    case "BROKER_ORDER_ACCEPTED":
      return InternalOrderState.BROKER_ORDER_ACCEPTED;
    case 5:
    case "BROKER_ORDER_PENDING_NEW":
      return InternalOrderState.BROKER_ORDER_PENDING_NEW;
    case 6:
    case "BROKER_ORDER_NEW":
      return InternalOrderState.BROKER_ORDER_NEW;
    case 7:
    case "SMART_CONTRACT_ORDER_PLACED":
      return InternalOrderState.SMART_CONTRACT_ORDER_PLACED;
    case 8:
    case "BROKER_ORDER_PARTIALLY_FILLED":
      return InternalOrderState.BROKER_ORDER_PARTIALLY_FILLED;
    case 9:
    case "SMART_CONTRACT_ORDER_PARTIALLY_FILLED_SUBMITTED":
      return InternalOrderState.SMART_CONTRACT_ORDER_PARTIALLY_FILLED_SUBMITTED;
    case 10:
    case "BROKER_ORDER_FILLED":
      return InternalOrderState.BROKER_ORDER_FILLED;
    case 11:
    case "SMART_CONTRACT_ORDER_EXECUTED":
      return InternalOrderState.SMART_CONTRACT_ORDER_EXECUTED;
    case 12:
    case "BROKER_ORDER_PRE_CANCEL_REQUESTED":
      return InternalOrderState.BROKER_ORDER_PRE_CANCEL_REQUESTED;
    case 13:
    case "BROKER_ORDER_CANCEL_REQUESTED":
      return InternalOrderState.BROKER_ORDER_CANCEL_REQUESTED;
    case 14:
    case "BROKER_ORDER_CANCELED":
      return InternalOrderState.BROKER_ORDER_CANCELED;
    case 15:
    case "BROKER_ORDER_REFUSED":
      return InternalOrderState.BROKER_ORDER_REFUSED;
    case 16:
    case "BROKER_ORDER_EXPIRED":
      return InternalOrderState.BROKER_ORDER_EXPIRED;
    case 17:
    case "SMART_CONTRACT_PRE_ORDER_CANCELLED":
      return InternalOrderState.SMART_CONTRACT_PRE_ORDER_CANCELLED;
    case 18:
    case "SMART_CONTRACT_ORDER_CANCELLED":
      return InternalOrderState.SMART_CONTRACT_ORDER_CANCELLED;
    case 21:
    case "SMART_CONTRACT_PRE_ORDER_EXPIRED":
      return InternalOrderState.SMART_CONTRACT_PRE_ORDER_EXPIRED;
    case 22:
    case "SMART_CONTRACT_ORDER_EXPIRED":
      return InternalOrderState.SMART_CONTRACT_ORDER_EXPIRED;
    case 19:
    case "PROCESS_FINISHED":
      return InternalOrderState.PROCESS_FINISHED;
    case 20:
    case "SMART_CONTRACT_CANCEL_ORDER_REQUESTED":
      return InternalOrderState.SMART_CONTRACT_CANCEL_ORDER_REQUESTED;
    case -1:
    case "UNRECOGNIZED":
    default:
      return InternalOrderState.UNRECOGNIZED;
  }
}

export function internalOrderStateToJSON(object: InternalOrderState): string {
  switch (object) {
    case InternalOrderState.NOT_APPLICABLE_INTERNAL_ORDER_STATE:
      return "NOT_APPLICABLE_INTERNAL_ORDER_STATE";
    case InternalOrderState.SMART_CONTRACT_NEW_ORDER_CREATED:
      return "SMART_CONTRACT_NEW_ORDER_CREATED";
    case InternalOrderState.BROKER_ORDER_PRE_SUBMITTED:
      return "BROKER_ORDER_PRE_SUBMITTED";
    case InternalOrderState.BROKER_ORDER_SUBMITTED:
      return "BROKER_ORDER_SUBMITTED";
    case InternalOrderState.BROKER_ORDER_ACCEPTED:
      return "BROKER_ORDER_ACCEPTED";
    case InternalOrderState.BROKER_ORDER_PENDING_NEW:
      return "BROKER_ORDER_PENDING_NEW";
    case InternalOrderState.BROKER_ORDER_NEW:
      return "BROKER_ORDER_NEW";
    case InternalOrderState.SMART_CONTRACT_ORDER_PLACED:
      return "SMART_CONTRACT_ORDER_PLACED";
    case InternalOrderState.BROKER_ORDER_PARTIALLY_FILLED:
      return "BROKER_ORDER_PARTIALLY_FILLED";
    case InternalOrderState.SMART_CONTRACT_ORDER_PARTIALLY_FILLED_SUBMITTED:
      return "SMART_CONTRACT_ORDER_PARTIALLY_FILLED_SUBMITTED";
    case InternalOrderState.BROKER_ORDER_FILLED:
      return "BROKER_ORDER_FILLED";
    case InternalOrderState.SMART_CONTRACT_ORDER_EXECUTED:
      return "SMART_CONTRACT_ORDER_EXECUTED";
    case InternalOrderState.BROKER_ORDER_PRE_CANCEL_REQUESTED:
      return "BROKER_ORDER_PRE_CANCEL_REQUESTED";
    case InternalOrderState.BROKER_ORDER_CANCEL_REQUESTED:
      return "BROKER_ORDER_CANCEL_REQUESTED";
    case InternalOrderState.BROKER_ORDER_CANCELED:
      return "BROKER_ORDER_CANCELED";
    case InternalOrderState.BROKER_ORDER_REFUSED:
      return "BROKER_ORDER_REFUSED";
    case InternalOrderState.BROKER_ORDER_EXPIRED:
      return "BROKER_ORDER_EXPIRED";
    case InternalOrderState.SMART_CONTRACT_PRE_ORDER_CANCELLED:
      return "SMART_CONTRACT_PRE_ORDER_CANCELLED";
    case InternalOrderState.SMART_CONTRACT_ORDER_CANCELLED:
      return "SMART_CONTRACT_ORDER_CANCELLED";
    case InternalOrderState.SMART_CONTRACT_PRE_ORDER_EXPIRED:
      return "SMART_CONTRACT_PRE_ORDER_EXPIRED";
    case InternalOrderState.SMART_CONTRACT_ORDER_EXPIRED:
      return "SMART_CONTRACT_ORDER_EXPIRED";
    case InternalOrderState.PROCESS_FINISHED:
      return "PROCESS_FINISHED";
    case InternalOrderState.SMART_CONTRACT_CANCEL_ORDER_REQUESTED:
      return "SMART_CONTRACT_CANCEL_ORDER_REQUESTED";
    case InternalOrderState.UNRECOGNIZED:
    default:
      return "UNRECOGNIZED";
  }
}

export enum OrderDetailType {
  /** NOT_APPLICABLE_ORDER_DETAIL_TYPE - Changed not used to NOT_APPLICABLE_ORDER_DETAIL_TYPE to accomodate for withdraw/deposit orders */
  NOT_APPLICABLE_ORDER_DETAIL_TYPE = 0,
  ORDER_DETAIL_LIMIT = 1,
  /** ORDER_DETAIL_MARKET - Ignores LimitPrice, executes at market price */
  ORDER_DETAIL_MARKET = 2,
  /** ORDER_DETAIL_STOP_LOSS - Uses LimitPrice as the stop loss threshold */
  ORDER_DETAIL_STOP_LOSS = 3,
  UNRECOGNIZED = -1,
}

export function orderDetailTypeFromJSON(object: any): OrderDetailType {
  switch (object) {
    case 0:
    case "NOT_APPLICABLE_ORDER_DETAIL_TYPE":
      return OrderDetailType.NOT_APPLICABLE_ORDER_DETAIL_TYPE;
    case 1:
    case "ORDER_DETAIL_LIMIT":
      return OrderDetailType.ORDER_DETAIL_LIMIT;
    case 2:
    case "ORDER_DETAIL_MARKET":
      return OrderDetailType.ORDER_DETAIL_MARKET;
    case 3:
    case "ORDER_DETAIL_STOP_LOSS":
      return OrderDetailType.ORDER_DETAIL_STOP_LOSS;
    case -1:
    case "UNRECOGNIZED":
    default:
      return OrderDetailType.UNRECOGNIZED;
  }
}

export function orderDetailTypeToJSON(object: OrderDetailType): string {
  switch (object) {
    case OrderDetailType.NOT_APPLICABLE_ORDER_DETAIL_TYPE:
      return "NOT_APPLICABLE_ORDER_DETAIL_TYPE";
    case OrderDetailType.ORDER_DETAIL_LIMIT:
      return "ORDER_DETAIL_LIMIT";
    case OrderDetailType.ORDER_DETAIL_MARKET:
      return "ORDER_DETAIL_MARKET";
    case OrderDetailType.ORDER_DETAIL_STOP_LOSS:
      return "ORDER_DETAIL_STOP_LOSS";
    case OrderDetailType.UNRECOGNIZED:
    default:
      return "UNRECOGNIZED";
  }
}

export enum ReceiverType {
  EMAIL = 0,
  TX = 1,
  ETHEREUM = 2,
  SOLANA = 3,
  UNRECOGNIZED = -1,
}

export function receiverTypeFromJSON(object: any): ReceiverType {
  switch (object) {
    case 0:
    case "EMAIL":
      return ReceiverType.EMAIL;
    case 1:
    case "TX":
      return ReceiverType.TX;
    case 2:
    case "ETHEREUM":
      return ReceiverType.ETHEREUM;
    case 3:
    case "SOLANA":
      return ReceiverType.SOLANA;
    case -1:
    case "UNRECOGNIZED":
    default:
      return ReceiverType.UNRECOGNIZED;
  }
}

export function receiverTypeToJSON(object: ReceiverType): string {
  switch (object) {
    case ReceiverType.EMAIL:
      return "EMAIL";
    case ReceiverType.TX:
      return "TX";
    case ReceiverType.ETHEREUM:
      return "ETHEREUM";
    case ReceiverType.SOLANA:
      return "SOLANA";
    case ReceiverType.UNRECOGNIZED:
    default:
      return "UNRECOGNIZED";
  }
}

/**
 * Order key: OrderID-SmartContractAddr-Network (1 entry per order)
 * Order history key(id): numeric ID auto-generated by datastore (M entries per order)
 */
export interface Order {
  Network: Network;
  SmartContractAddr: string;
  /** Snapshot of the order in the smart contract */
  Instruction: OrderInstruction | undefined;
  CreatedAt: Date | undefined;
  UpdatedAt: Date | undefined;
  TransactionType: TransactionType;
  /** Unique Key in the datastore */
  TXID: string;
  GasFee: number;
  GasFeeUSD?: number | undefined;
  DetectedAt: Date | undefined;
  Height: number;
  InternalOrderState: InternalOrderState;
  /** Matches data on SmartContractAddr, orderdetails.OrderID and network */
  BrokerOrderDetails?:
    | BrokerOrderDetails
    | undefined;
  /** Bookkeeping: did we process this event from broker smart contract order log? */
  ProcessInfo?:
    | ProcessInfo
    | undefined;
  /** ID used by logs to identify the instance where the log was created/ processed */
  InstanceID?: string | undefined;
  BlockTime:
    | Date
    | undefined;
  /** Sequence */
  Sequence: number;
  OrganizationID: string;
  UserID: string;
}

/** Same structure as Order in the Smart Contract */
export interface OrderInstruction {
  /** Google datastore supports int64, not uint64, which is the used in the smart contract */
  OrderID: number;
  /** Sender in the message from Coreum */
  Creator: string;
  Denom: string;
  Amount: number;
  AmountExp: number;
  /** DEPRECATED: Use LimitPriceFloat instead for new smart contract format */
  LimitPrice: number;
  /** DEPRECATED: Use LimitPriceFloat instead for new smart contract format */
  LimitPriceExp: number;
  /** DEPRECATED: Use TimeInForce instead as it's more flexible and RQD does not support it (2025-08-18) */
  FillOrKill: boolean;
  /** In ISO-8601 Zulu format (e.g., "2024-02-29T23:59:59Z") */
  ExpiresAt?: string | undefined;
  OrderDetailType: OrderDetailType;
  Hold?: Hold | undefined;
  FundsSent: Coin | undefined;
  OrderType: OrderType;
  OrderState: OrderState | undefined;
  PaymentState?: PaymentState | undefined;
  AmountExecuted?: number | undefined;
  AmountExecutedExp?: number | undefined;
  UsedFundsAmount?: number | undefined;
  UsedFundsAmountExp?: number | undefined;
  Costs?: number | undefined;
  CostsExp?: number | undefined;
  TimeInForce?:
    | TimeInForce
    | undefined;
  /** Direct float price from smart contract (e.g., 26.25) */
  LimitPriceFloat?:
    | number
    | undefined;
  /** The address of the receiver, used for sending of funds. Receiver can also be an email address, tx address or blockchain addres from another blockchain. */
  Receiver?: Receiver | undefined;
}

export interface Orders {
  Orders: Order[];
  Offset?: number | undefined;
}

export interface Hold {
  Denom: string;
  Amount: number;
  AmountExp: number;
}

export interface Coin {
  Denom: string;
  Amount: number;
}

export interface OrderState {
  OrderStateType: OrderStateType;
  OrderCancelledBy?: OrderCancelledBy | undefined;
}

export interface Receiver {
  /** The address of the receiver, used for sending of funds. */
  Address: string;
  /** The type of the receiver, e.g. email, tx address, blockchain address from another blockchain. */
  Type: ReceiverType;
}

function createBaseOrder(): Order {
  return {
    Network: 0,
    SmartContractAddr: "",
    Instruction: undefined,
    CreatedAt: undefined,
    UpdatedAt: undefined,
    TransactionType: 0,
    TXID: "",
    GasFee: 0,
    GasFeeUSD: undefined,
    DetectedAt: undefined,
    Height: 0,
    InternalOrderState: 0,
    BrokerOrderDetails: undefined,
    ProcessInfo: undefined,
    InstanceID: undefined,
    BlockTime: undefined,
    Sequence: 0,
    OrganizationID: "",
    UserID: "",
  };
}

export const Order = {
  encode(message: Order, writer: _m0.Writer = _m0.Writer.create()): _m0.Writer {
    if (message.Network !== 0) {
      writer.uint32(8).int32(message.Network);
    }
    if (message.SmartContractAddr !== "") {
      writer.uint32(18).string(message.SmartContractAddr);
    }
    if (message.Instruction !== undefined) {
      OrderInstruction.encode(message.Instruction, writer.uint32(26).fork()).ldelim();
    }
    if (message.CreatedAt !== undefined) {
      Timestamp.encode(toTimestamp(message.CreatedAt), writer.uint32(34).fork()).ldelim();
    }
    if (message.UpdatedAt !== undefined) {
      Timestamp.encode(toTimestamp(message.UpdatedAt), writer.uint32(42).fork()).ldelim();
    }
    if (message.TransactionType !== 0) {
      writer.uint32(48).int32(message.TransactionType);
    }
    if (message.TXID !== "") {
      writer.uint32(58).string(message.TXID);
    }
    if (message.GasFee !== 0) {
      writer.uint32(64).int64(message.GasFee);
    }
    if (message.GasFeeUSD !== undefined) {
      writer.uint32(73).double(message.GasFeeUSD);
    }
    if (message.DetectedAt !== undefined) {
      Timestamp.encode(toTimestamp(message.DetectedAt), writer.uint32(82).fork()).ldelim();
    }
    if (message.Height !== 0) {
      writer.uint32(88).int64(message.Height);
    }
    if (message.InternalOrderState !== 0) {
      writer.uint32(96).int32(message.InternalOrderState);
    }
    if (message.BrokerOrderDetails !== undefined) {
      BrokerOrderDetails.encode(message.BrokerOrderDetails, writer.uint32(106).fork()).ldelim();
    }
    if (message.ProcessInfo !== undefined) {
      ProcessInfo.encode(message.ProcessInfo, writer.uint32(114).fork()).ldelim();
    }
    if (message.InstanceID !== undefined) {
      writer.uint32(122).string(message.InstanceID);
    }
    if (message.BlockTime !== undefined) {
      Timestamp.encode(toTimestamp(message.BlockTime), writer.uint32(130).fork()).ldelim();
    }
    if (message.Sequence !== 0) {
      writer.uint32(136).int64(message.Sequence);
    }
    if (message.OrganizationID !== "") {
      writer.uint32(146).string(message.OrganizationID);
    }
    if (message.UserID !== "") {
      writer.uint32(154).string(message.UserID);
    }
    return writer;
  },

  decode(input: _m0.Reader | Uint8Array, length?: number): Order {
    const reader = input instanceof _m0.Reader ? input : _m0.Reader.create(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseOrder();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1:
          if (tag !== 8) {
            break;
          }

          message.Network = reader.int32() as any;
          continue;
        case 2:
          if (tag !== 18) {
            break;
          }

          message.SmartContractAddr = reader.string();
          continue;
        case 3:
          if (tag !== 26) {
            break;
          }

          message.Instruction = OrderInstruction.decode(reader, reader.uint32());
          continue;
        case 4:
          if (tag !== 34) {
            break;
          }

          message.CreatedAt = fromTimestamp(Timestamp.decode(reader, reader.uint32()));
          continue;
        case 5:
          if (tag !== 42) {
            break;
          }

          message.UpdatedAt = fromTimestamp(Timestamp.decode(reader, reader.uint32()));
          continue;
        case 6:
          if (tag !== 48) {
            break;
          }

          message.TransactionType = reader.int32() as any;
          continue;
        case 7:
          if (tag !== 58) {
            break;
          }

          message.TXID = reader.string();
          continue;
        case 8:
          if (tag !== 64) {
            break;
          }

          message.GasFee = longToNumber(reader.int64() as Long);
          continue;
        case 9:
          if (tag !== 73) {
            break;
          }

          message.GasFeeUSD = reader.double();
          continue;
        case 10:
          if (tag !== 82) {
            break;
          }

          message.DetectedAt = fromTimestamp(Timestamp.decode(reader, reader.uint32()));
          continue;
        case 11:
          if (tag !== 88) {
            break;
          }

          message.Height = longToNumber(reader.int64() as Long);
          continue;
        case 12:
          if (tag !== 96) {
            break;
          }

          message.InternalOrderState = reader.int32() as any;
          continue;
        case 13:
          if (tag !== 106) {
            break;
          }

          message.BrokerOrderDetails = BrokerOrderDetails.decode(reader, reader.uint32());
          continue;
        case 14:
          if (tag !== 114) {
            break;
          }

          message.ProcessInfo = ProcessInfo.decode(reader, reader.uint32());
          continue;
        case 15:
          if (tag !== 122) {
            break;
          }

          message.InstanceID = reader.string();
          continue;
        case 16:
          if (tag !== 130) {
            break;
          }

          message.BlockTime = fromTimestamp(Timestamp.decode(reader, reader.uint32()));
          continue;
        case 17:
          if (tag !== 136) {
            break;
          }

          message.Sequence = longToNumber(reader.int64() as Long);
          continue;
        case 18:
          if (tag !== 146) {
            break;
          }

          message.OrganizationID = reader.string();
          continue;
        case 19:
          if (tag !== 154) {
            break;
          }

          message.UserID = reader.string();
          continue;
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skipType(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): Order {
    return {
      Network: isSet(object.Network) ? networkFromJSON(object.Network) : 0,
      SmartContractAddr: isSet(object.SmartContractAddr) ? globalThis.String(object.SmartContractAddr) : "",
      Instruction: isSet(object.Instruction) ? OrderInstruction.fromJSON(object.Instruction) : undefined,
      CreatedAt: isSet(object.CreatedAt) ? fromJsonTimestamp(object.CreatedAt) : undefined,
      UpdatedAt: isSet(object.UpdatedAt) ? fromJsonTimestamp(object.UpdatedAt) : undefined,
      TransactionType: isSet(object.TransactionType) ? transactionTypeFromJSON(object.TransactionType) : 0,
      TXID: isSet(object.TXID) ? globalThis.String(object.TXID) : "",
      GasFee: isSet(object.GasFee) ? globalThis.Number(object.GasFee) : 0,
      GasFeeUSD: isSet(object.GasFeeUSD) ? globalThis.Number(object.GasFeeUSD) : undefined,
      DetectedAt: isSet(object.DetectedAt) ? fromJsonTimestamp(object.DetectedAt) : undefined,
      Height: isSet(object.Height) ? globalThis.Number(object.Height) : 0,
      InternalOrderState: isSet(object.InternalOrderState) ? internalOrderStateFromJSON(object.InternalOrderState) : 0,
      BrokerOrderDetails: isSet(object.BrokerOrderDetails)
        ? BrokerOrderDetails.fromJSON(object.BrokerOrderDetails)
        : undefined,
      ProcessInfo: isSet(object.ProcessInfo) ? ProcessInfo.fromJSON(object.ProcessInfo) : undefined,
      InstanceID: isSet(object.InstanceID) ? globalThis.String(object.InstanceID) : undefined,
      BlockTime: isSet(object.BlockTime) ? fromJsonTimestamp(object.BlockTime) : undefined,
      Sequence: isSet(object.Sequence) ? globalThis.Number(object.Sequence) : 0,
      OrganizationID: isSet(object.OrganizationID) ? globalThis.String(object.OrganizationID) : "",
      UserID: isSet(object.UserID) ? globalThis.String(object.UserID) : "",
    };
  },

  toJSON(message: Order): unknown {
    const obj: any = {};
    if (message.Network !== 0) {
      obj.Network = networkToJSON(message.Network);
    }
    if (message.SmartContractAddr !== "") {
      obj.SmartContractAddr = message.SmartContractAddr;
    }
    if (message.Instruction !== undefined) {
      obj.Instruction = OrderInstruction.toJSON(message.Instruction);
    }
    if (message.CreatedAt !== undefined) {
      obj.CreatedAt = message.CreatedAt.toISOString();
    }
    if (message.UpdatedAt !== undefined) {
      obj.UpdatedAt = message.UpdatedAt.toISOString();
    }
    if (message.TransactionType !== 0) {
      obj.TransactionType = transactionTypeToJSON(message.TransactionType);
    }
    if (message.TXID !== "") {
      obj.TXID = message.TXID;
    }
    if (message.GasFee !== 0) {
      obj.GasFee = Math.round(message.GasFee);
    }
    if (message.GasFeeUSD !== undefined) {
      obj.GasFeeUSD = message.GasFeeUSD;
    }
    if (message.DetectedAt !== undefined) {
      obj.DetectedAt = message.DetectedAt.toISOString();
    }
    if (message.Height !== 0) {
      obj.Height = Math.round(message.Height);
    }
    if (message.InternalOrderState !== 0) {
      obj.InternalOrderState = internalOrderStateToJSON(message.InternalOrderState);
    }
    if (message.BrokerOrderDetails !== undefined) {
      obj.BrokerOrderDetails = BrokerOrderDetails.toJSON(message.BrokerOrderDetails);
    }
    if (message.ProcessInfo !== undefined) {
      obj.ProcessInfo = ProcessInfo.toJSON(message.ProcessInfo);
    }
    if (message.InstanceID !== undefined) {
      obj.InstanceID = message.InstanceID;
    }
    if (message.BlockTime !== undefined) {
      obj.BlockTime = message.BlockTime.toISOString();
    }
    if (message.Sequence !== 0) {
      obj.Sequence = Math.round(message.Sequence);
    }
    if (message.OrganizationID !== "") {
      obj.OrganizationID = message.OrganizationID;
    }
    if (message.UserID !== "") {
      obj.UserID = message.UserID;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<Order>, I>>(base?: I): Order {
    return Order.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<Order>, I>>(object: I): Order {
    const message = createBaseOrder();
    message.Network = object.Network ?? 0;
    message.SmartContractAddr = object.SmartContractAddr ?? "";
    message.Instruction = (object.Instruction !== undefined && object.Instruction !== null)
      ? OrderInstruction.fromPartial(object.Instruction)
      : undefined;
    message.CreatedAt = object.CreatedAt ?? undefined;
    message.UpdatedAt = object.UpdatedAt ?? undefined;
    message.TransactionType = object.TransactionType ?? 0;
    message.TXID = object.TXID ?? "";
    message.GasFee = object.GasFee ?? 0;
    message.GasFeeUSD = object.GasFeeUSD ?? undefined;
    message.DetectedAt = object.DetectedAt ?? undefined;
    message.Height = object.Height ?? 0;
    message.InternalOrderState = object.InternalOrderState ?? 0;
    message.BrokerOrderDetails = (object.BrokerOrderDetails !== undefined && object.BrokerOrderDetails !== null)
      ? BrokerOrderDetails.fromPartial(object.BrokerOrderDetails)
      : undefined;
    message.ProcessInfo = (object.ProcessInfo !== undefined && object.ProcessInfo !== null)
      ? ProcessInfo.fromPartial(object.ProcessInfo)
      : undefined;
    message.InstanceID = object.InstanceID ?? undefined;
    message.BlockTime = object.BlockTime ?? undefined;
    message.Sequence = object.Sequence ?? 0;
    message.OrganizationID = object.OrganizationID ?? "";
    message.UserID = object.UserID ?? "";
    return message;
  },
};

function createBaseOrderInstruction(): OrderInstruction {
  return {
    OrderID: 0,
    Creator: "",
    Denom: "",
    Amount: 0,
    AmountExp: 0,
    LimitPrice: 0,
    LimitPriceExp: 0,
    FillOrKill: false,
    ExpiresAt: undefined,
    OrderDetailType: 0,
    Hold: undefined,
    FundsSent: undefined,
    OrderType: 0,
    OrderState: undefined,
    PaymentState: undefined,
    AmountExecuted: undefined,
    AmountExecutedExp: undefined,
    UsedFundsAmount: undefined,
    UsedFundsAmountExp: undefined,
    Costs: undefined,
    CostsExp: undefined,
    TimeInForce: undefined,
    LimitPriceFloat: undefined,
    Receiver: undefined,
  };
}

export const OrderInstruction = {
  encode(message: OrderInstruction, writer: _m0.Writer = _m0.Writer.create()): _m0.Writer {
    if (message.OrderID !== 0) {
      writer.uint32(8).int64(message.OrderID);
    }
    if (message.Creator !== "") {
      writer.uint32(18).string(message.Creator);
    }
    if (message.Denom !== "") {
      writer.uint32(26).string(message.Denom);
    }
    if (message.Amount !== 0) {
      writer.uint32(32).int64(message.Amount);
    }
    if (message.AmountExp !== 0) {
      writer.uint32(40).int32(message.AmountExp);
    }
    if (message.LimitPrice !== 0) {
      writer.uint32(48).int64(message.LimitPrice);
    }
    if (message.LimitPriceExp !== 0) {
      writer.uint32(56).int32(message.LimitPriceExp);
    }
    if (message.FillOrKill !== false) {
      writer.uint32(64).bool(message.FillOrKill);
    }
    if (message.ExpiresAt !== undefined) {
      writer.uint32(74).string(message.ExpiresAt);
    }
    if (message.OrderDetailType !== 0) {
      writer.uint32(80).int32(message.OrderDetailType);
    }
    if (message.Hold !== undefined) {
      Hold.encode(message.Hold, writer.uint32(90).fork()).ldelim();
    }
    if (message.FundsSent !== undefined) {
      Coin.encode(message.FundsSent, writer.uint32(98).fork()).ldelim();
    }
    if (message.OrderType !== 0) {
      writer.uint32(104).int32(message.OrderType);
    }
    if (message.OrderState !== undefined) {
      OrderState.encode(message.OrderState, writer.uint32(114).fork()).ldelim();
    }
    if (message.PaymentState !== undefined) {
      writer.uint32(120).int32(message.PaymentState);
    }
    if (message.AmountExecuted !== undefined) {
      writer.uint32(128).int64(message.AmountExecuted);
    }
    if (message.AmountExecutedExp !== undefined) {
      writer.uint32(136).int32(message.AmountExecutedExp);
    }
    if (message.UsedFundsAmount !== undefined) {
      writer.uint32(144).int64(message.UsedFundsAmount);
    }
    if (message.UsedFundsAmountExp !== undefined) {
      writer.uint32(152).int32(message.UsedFundsAmountExp);
    }
    if (message.Costs !== undefined) {
      writer.uint32(160).int64(message.Costs);
    }
    if (message.CostsExp !== undefined) {
      writer.uint32(168).int32(message.CostsExp);
    }
    if (message.TimeInForce !== undefined) {
      writer.uint32(176).int32(message.TimeInForce);
    }
    if (message.LimitPriceFloat !== undefined) {
      writer.uint32(185).double(message.LimitPriceFloat);
    }
    if (message.Receiver !== undefined) {
      Receiver.encode(message.Receiver, writer.uint32(194).fork()).ldelim();
    }
    return writer;
  },

  decode(input: _m0.Reader | Uint8Array, length?: number): OrderInstruction {
    const reader = input instanceof _m0.Reader ? input : _m0.Reader.create(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseOrderInstruction();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1:
          if (tag !== 8) {
            break;
          }

          message.OrderID = longToNumber(reader.int64() as Long);
          continue;
        case 2:
          if (tag !== 18) {
            break;
          }

          message.Creator = reader.string();
          continue;
        case 3:
          if (tag !== 26) {
            break;
          }

          message.Denom = reader.string();
          continue;
        case 4:
          if (tag !== 32) {
            break;
          }

          message.Amount = longToNumber(reader.int64() as Long);
          continue;
        case 5:
          if (tag !== 40) {
            break;
          }

          message.AmountExp = reader.int32();
          continue;
        case 6:
          if (tag !== 48) {
            break;
          }

          message.LimitPrice = longToNumber(reader.int64() as Long);
          continue;
        case 7:
          if (tag !== 56) {
            break;
          }

          message.LimitPriceExp = reader.int32();
          continue;
        case 8:
          if (tag !== 64) {
            break;
          }

          message.FillOrKill = reader.bool();
          continue;
        case 9:
          if (tag !== 74) {
            break;
          }

          message.ExpiresAt = reader.string();
          continue;
        case 10:
          if (tag !== 80) {
            break;
          }

          message.OrderDetailType = reader.int32() as any;
          continue;
        case 11:
          if (tag !== 90) {
            break;
          }

          message.Hold = Hold.decode(reader, reader.uint32());
          continue;
        case 12:
          if (tag !== 98) {
            break;
          }

          message.FundsSent = Coin.decode(reader, reader.uint32());
          continue;
        case 13:
          if (tag !== 104) {
            break;
          }

          message.OrderType = reader.int32() as any;
          continue;
        case 14:
          if (tag !== 114) {
            break;
          }

          message.OrderState = OrderState.decode(reader, reader.uint32());
          continue;
        case 15:
          if (tag !== 120) {
            break;
          }

          message.PaymentState = reader.int32() as any;
          continue;
        case 16:
          if (tag !== 128) {
            break;
          }

          message.AmountExecuted = longToNumber(reader.int64() as Long);
          continue;
        case 17:
          if (tag !== 136) {
            break;
          }

          message.AmountExecutedExp = reader.int32();
          continue;
        case 18:
          if (tag !== 144) {
            break;
          }

          message.UsedFundsAmount = longToNumber(reader.int64() as Long);
          continue;
        case 19:
          if (tag !== 152) {
            break;
          }

          message.UsedFundsAmountExp = reader.int32();
          continue;
        case 20:
          if (tag !== 160) {
            break;
          }

          message.Costs = longToNumber(reader.int64() as Long);
          continue;
        case 21:
          if (tag !== 168) {
            break;
          }

          message.CostsExp = reader.int32();
          continue;
        case 22:
          if (tag !== 176) {
            break;
          }

          message.TimeInForce = reader.int32() as any;
          continue;
        case 23:
          if (tag !== 185) {
            break;
          }

          message.LimitPriceFloat = reader.double();
          continue;
        case 24:
          if (tag !== 194) {
            break;
          }

          message.Receiver = Receiver.decode(reader, reader.uint32());
          continue;
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skipType(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): OrderInstruction {
    return {
      OrderID: isSet(object.OrderID) ? globalThis.Number(object.OrderID) : 0,
      Creator: isSet(object.Creator) ? globalThis.String(object.Creator) : "",
      Denom: isSet(object.Denom) ? globalThis.String(object.Denom) : "",
      Amount: isSet(object.Amount) ? globalThis.Number(object.Amount) : 0,
      AmountExp: isSet(object.AmountExp) ? globalThis.Number(object.AmountExp) : 0,
      LimitPrice: isSet(object.LimitPrice) ? globalThis.Number(object.LimitPrice) : 0,
      LimitPriceExp: isSet(object.LimitPriceExp) ? globalThis.Number(object.LimitPriceExp) : 0,
      FillOrKill: isSet(object.FillOrKill) ? globalThis.Boolean(object.FillOrKill) : false,
      ExpiresAt: isSet(object.ExpiresAt) ? globalThis.String(object.ExpiresAt) : undefined,
      OrderDetailType: isSet(object.OrderDetailType) ? orderDetailTypeFromJSON(object.OrderDetailType) : 0,
      Hold: isSet(object.Hold) ? Hold.fromJSON(object.Hold) : undefined,
      FundsSent: isSet(object.FundsSent) ? Coin.fromJSON(object.FundsSent) : undefined,
      OrderType: isSet(object.OrderType) ? orderTypeFromJSON(object.OrderType) : 0,
      OrderState: isSet(object.OrderState) ? OrderState.fromJSON(object.OrderState) : undefined,
      PaymentState: isSet(object.PaymentState) ? paymentStateFromJSON(object.PaymentState) : undefined,
      AmountExecuted: isSet(object.AmountExecuted) ? globalThis.Number(object.AmountExecuted) : undefined,
      AmountExecutedExp: isSet(object.AmountExecutedExp) ? globalThis.Number(object.AmountExecutedExp) : undefined,
      UsedFundsAmount: isSet(object.UsedFundsAmount) ? globalThis.Number(object.UsedFundsAmount) : undefined,
      UsedFundsAmountExp: isSet(object.UsedFundsAmountExp) ? globalThis.Number(object.UsedFundsAmountExp) : undefined,
      Costs: isSet(object.Costs) ? globalThis.Number(object.Costs) : undefined,
      CostsExp: isSet(object.CostsExp) ? globalThis.Number(object.CostsExp) : undefined,
      TimeInForce: isSet(object.TimeInForce) ? timeInForceFromJSON(object.TimeInForce) : undefined,
      LimitPriceFloat: isSet(object.LimitPriceFloat) ? globalThis.Number(object.LimitPriceFloat) : undefined,
      Receiver: isSet(object.Receiver) ? Receiver.fromJSON(object.Receiver) : undefined,
    };
  },

  toJSON(message: OrderInstruction): unknown {
    const obj: any = {};
    if (message.OrderID !== 0) {
      obj.OrderID = Math.round(message.OrderID);
    }
    if (message.Creator !== "") {
      obj.Creator = message.Creator;
    }
    if (message.Denom !== "") {
      obj.Denom = message.Denom;
    }
    if (message.Amount !== 0) {
      obj.Amount = Math.round(message.Amount);
    }
    if (message.AmountExp !== 0) {
      obj.AmountExp = Math.round(message.AmountExp);
    }
    if (message.LimitPrice !== 0) {
      obj.LimitPrice = Math.round(message.LimitPrice);
    }
    if (message.LimitPriceExp !== 0) {
      obj.LimitPriceExp = Math.round(message.LimitPriceExp);
    }
    if (message.FillOrKill !== false) {
      obj.FillOrKill = message.FillOrKill;
    }
    if (message.ExpiresAt !== undefined) {
      obj.ExpiresAt = message.ExpiresAt;
    }
    if (message.OrderDetailType !== 0) {
      obj.OrderDetailType = orderDetailTypeToJSON(message.OrderDetailType);
    }
    if (message.Hold !== undefined) {
      obj.Hold = Hold.toJSON(message.Hold);
    }
    if (message.FundsSent !== undefined) {
      obj.FundsSent = Coin.toJSON(message.FundsSent);
    }
    if (message.OrderType !== 0) {
      obj.OrderType = orderTypeToJSON(message.OrderType);
    }
    if (message.OrderState !== undefined) {
      obj.OrderState = OrderState.toJSON(message.OrderState);
    }
    if (message.PaymentState !== undefined) {
      obj.PaymentState = paymentStateToJSON(message.PaymentState);
    }
    if (message.AmountExecuted !== undefined) {
      obj.AmountExecuted = Math.round(message.AmountExecuted);
    }
    if (message.AmountExecutedExp !== undefined) {
      obj.AmountExecutedExp = Math.round(message.AmountExecutedExp);
    }
    if (message.UsedFundsAmount !== undefined) {
      obj.UsedFundsAmount = Math.round(message.UsedFundsAmount);
    }
    if (message.UsedFundsAmountExp !== undefined) {
      obj.UsedFundsAmountExp = Math.round(message.UsedFundsAmountExp);
    }
    if (message.Costs !== undefined) {
      obj.Costs = Math.round(message.Costs);
    }
    if (message.CostsExp !== undefined) {
      obj.CostsExp = Math.round(message.CostsExp);
    }
    if (message.TimeInForce !== undefined) {
      obj.TimeInForce = timeInForceToJSON(message.TimeInForce);
    }
    if (message.LimitPriceFloat !== undefined) {
      obj.LimitPriceFloat = message.LimitPriceFloat;
    }
    if (message.Receiver !== undefined) {
      obj.Receiver = Receiver.toJSON(message.Receiver);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<OrderInstruction>, I>>(base?: I): OrderInstruction {
    return OrderInstruction.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<OrderInstruction>, I>>(object: I): OrderInstruction {
    const message = createBaseOrderInstruction();
    message.OrderID = object.OrderID ?? 0;
    message.Creator = object.Creator ?? "";
    message.Denom = object.Denom ?? "";
    message.Amount = object.Amount ?? 0;
    message.AmountExp = object.AmountExp ?? 0;
    message.LimitPrice = object.LimitPrice ?? 0;
    message.LimitPriceExp = object.LimitPriceExp ?? 0;
    message.FillOrKill = object.FillOrKill ?? false;
    message.ExpiresAt = object.ExpiresAt ?? undefined;
    message.OrderDetailType = object.OrderDetailType ?? 0;
    message.Hold = (object.Hold !== undefined && object.Hold !== null) ? Hold.fromPartial(object.Hold) : undefined;
    message.FundsSent = (object.FundsSent !== undefined && object.FundsSent !== null)
      ? Coin.fromPartial(object.FundsSent)
      : undefined;
    message.OrderType = object.OrderType ?? 0;
    message.OrderState = (object.OrderState !== undefined && object.OrderState !== null)
      ? OrderState.fromPartial(object.OrderState)
      : undefined;
    message.PaymentState = object.PaymentState ?? undefined;
    message.AmountExecuted = object.AmountExecuted ?? undefined;
    message.AmountExecutedExp = object.AmountExecutedExp ?? undefined;
    message.UsedFundsAmount = object.UsedFundsAmount ?? undefined;
    message.UsedFundsAmountExp = object.UsedFundsAmountExp ?? undefined;
    message.Costs = object.Costs ?? undefined;
    message.CostsExp = object.CostsExp ?? undefined;
    message.TimeInForce = object.TimeInForce ?? undefined;
    message.LimitPriceFloat = object.LimitPriceFloat ?? undefined;
    message.Receiver = (object.Receiver !== undefined && object.Receiver !== null)
      ? Receiver.fromPartial(object.Receiver)
      : undefined;
    return message;
  },
};

function createBaseOrders(): Orders {
  return { Orders: [], Offset: undefined };
}

export const Orders = {
  encode(message: Orders, writer: _m0.Writer = _m0.Writer.create()): _m0.Writer {
    for (const v of message.Orders) {
      Order.encode(v!, writer.uint32(10).fork()).ldelim();
    }
    if (message.Offset !== undefined) {
      writer.uint32(16).int32(message.Offset);
    }
    return writer;
  },

  decode(input: _m0.Reader | Uint8Array, length?: number): Orders {
    const reader = input instanceof _m0.Reader ? input : _m0.Reader.create(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseOrders();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1:
          if (tag !== 10) {
            break;
          }

          message.Orders.push(Order.decode(reader, reader.uint32()));
          continue;
        case 2:
          if (tag !== 16) {
            break;
          }

          message.Offset = reader.int32();
          continue;
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skipType(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): Orders {
    return {
      Orders: globalThis.Array.isArray(object?.Orders) ? object.Orders.map((e: any) => Order.fromJSON(e)) : [],
      Offset: isSet(object.Offset) ? globalThis.Number(object.Offset) : undefined,
    };
  },

  toJSON(message: Orders): unknown {
    const obj: any = {};
    if (message.Orders?.length) {
      obj.Orders = message.Orders.map((e) => Order.toJSON(e));
    }
    if (message.Offset !== undefined) {
      obj.Offset = Math.round(message.Offset);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<Orders>, I>>(base?: I): Orders {
    return Orders.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<Orders>, I>>(object: I): Orders {
    const message = createBaseOrders();
    message.Orders = object.Orders?.map((e) => Order.fromPartial(e)) || [];
    message.Offset = object.Offset ?? undefined;
    return message;
  },
};

function createBaseHold(): Hold {
  return { Denom: "", Amount: 0, AmountExp: 0 };
}

export const Hold = {
  encode(message: Hold, writer: _m0.Writer = _m0.Writer.create()): _m0.Writer {
    if (message.Denom !== "") {
      writer.uint32(10).string(message.Denom);
    }
    if (message.Amount !== 0) {
      writer.uint32(16).int64(message.Amount);
    }
    if (message.AmountExp !== 0) {
      writer.uint32(24).int32(message.AmountExp);
    }
    return writer;
  },

  decode(input: _m0.Reader | Uint8Array, length?: number): Hold {
    const reader = input instanceof _m0.Reader ? input : _m0.Reader.create(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseHold();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1:
          if (tag !== 10) {
            break;
          }

          message.Denom = reader.string();
          continue;
        case 2:
          if (tag !== 16) {
            break;
          }

          message.Amount = longToNumber(reader.int64() as Long);
          continue;
        case 3:
          if (tag !== 24) {
            break;
          }

          message.AmountExp = reader.int32();
          continue;
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skipType(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): Hold {
    return {
      Denom: isSet(object.Denom) ? globalThis.String(object.Denom) : "",
      Amount: isSet(object.Amount) ? globalThis.Number(object.Amount) : 0,
      AmountExp: isSet(object.AmountExp) ? globalThis.Number(object.AmountExp) : 0,
    };
  },

  toJSON(message: Hold): unknown {
    const obj: any = {};
    if (message.Denom !== "") {
      obj.Denom = message.Denom;
    }
    if (message.Amount !== 0) {
      obj.Amount = Math.round(message.Amount);
    }
    if (message.AmountExp !== 0) {
      obj.AmountExp = Math.round(message.AmountExp);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<Hold>, I>>(base?: I): Hold {
    return Hold.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<Hold>, I>>(object: I): Hold {
    const message = createBaseHold();
    message.Denom = object.Denom ?? "";
    message.Amount = object.Amount ?? 0;
    message.AmountExp = object.AmountExp ?? 0;
    return message;
  },
};

function createBaseCoin(): Coin {
  return { Denom: "", Amount: 0 };
}

export const Coin = {
  encode(message: Coin, writer: _m0.Writer = _m0.Writer.create()): _m0.Writer {
    if (message.Denom !== "") {
      writer.uint32(10).string(message.Denom);
    }
    if (message.Amount !== 0) {
      writer.uint32(16).int64(message.Amount);
    }
    return writer;
  },

  decode(input: _m0.Reader | Uint8Array, length?: number): Coin {
    const reader = input instanceof _m0.Reader ? input : _m0.Reader.create(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseCoin();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1:
          if (tag !== 10) {
            break;
          }

          message.Denom = reader.string();
          continue;
        case 2:
          if (tag !== 16) {
            break;
          }

          message.Amount = longToNumber(reader.int64() as Long);
          continue;
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skipType(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): Coin {
    return {
      Denom: isSet(object.Denom) ? globalThis.String(object.Denom) : "",
      Amount: isSet(object.Amount) ? globalThis.Number(object.Amount) : 0,
    };
  },

  toJSON(message: Coin): unknown {
    const obj: any = {};
    if (message.Denom !== "") {
      obj.Denom = message.Denom;
    }
    if (message.Amount !== 0) {
      obj.Amount = Math.round(message.Amount);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<Coin>, I>>(base?: I): Coin {
    return Coin.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<Coin>, I>>(object: I): Coin {
    const message = createBaseCoin();
    message.Denom = object.Denom ?? "";
    message.Amount = object.Amount ?? 0;
    return message;
  },
};

function createBaseOrderState(): OrderState {
  return { OrderStateType: 0, OrderCancelledBy: undefined };
}

export const OrderState = {
  encode(message: OrderState, writer: _m0.Writer = _m0.Writer.create()): _m0.Writer {
    if (message.OrderStateType !== 0) {
      writer.uint32(8).int32(message.OrderStateType);
    }
    if (message.OrderCancelledBy !== undefined) {
      writer.uint32(16).int32(message.OrderCancelledBy);
    }
    return writer;
  },

  decode(input: _m0.Reader | Uint8Array, length?: number): OrderState {
    const reader = input instanceof _m0.Reader ? input : _m0.Reader.create(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseOrderState();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1:
          if (tag !== 8) {
            break;
          }

          message.OrderStateType = reader.int32() as any;
          continue;
        case 2:
          if (tag !== 16) {
            break;
          }

          message.OrderCancelledBy = reader.int32() as any;
          continue;
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skipType(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): OrderState {
    return {
      OrderStateType: isSet(object.OrderStateType) ? orderStateTypeFromJSON(object.OrderStateType) : 0,
      OrderCancelledBy: isSet(object.OrderCancelledBy) ? orderCancelledByFromJSON(object.OrderCancelledBy) : undefined,
    };
  },

  toJSON(message: OrderState): unknown {
    const obj: any = {};
    if (message.OrderStateType !== 0) {
      obj.OrderStateType = orderStateTypeToJSON(message.OrderStateType);
    }
    if (message.OrderCancelledBy !== undefined) {
      obj.OrderCancelledBy = orderCancelledByToJSON(message.OrderCancelledBy);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<OrderState>, I>>(base?: I): OrderState {
    return OrderState.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<OrderState>, I>>(object: I): OrderState {
    const message = createBaseOrderState();
    message.OrderStateType = object.OrderStateType ?? 0;
    message.OrderCancelledBy = object.OrderCancelledBy ?? undefined;
    return message;
  },
};

function createBaseReceiver(): Receiver {
  return { Address: "", Type: 0 };
}

export const Receiver = {
  encode(message: Receiver, writer: _m0.Writer = _m0.Writer.create()): _m0.Writer {
    if (message.Address !== "") {
      writer.uint32(10).string(message.Address);
    }
    if (message.Type !== 0) {
      writer.uint32(16).int32(message.Type);
    }
    return writer;
  },

  decode(input: _m0.Reader | Uint8Array, length?: number): Receiver {
    const reader = input instanceof _m0.Reader ? input : _m0.Reader.create(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseReceiver();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1:
          if (tag !== 10) {
            break;
          }

          message.Address = reader.string();
          continue;
        case 2:
          if (tag !== 16) {
            break;
          }

          message.Type = reader.int32() as any;
          continue;
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skipType(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): Receiver {
    return {
      Address: isSet(object.Address) ? globalThis.String(object.Address) : "",
      Type: isSet(object.Type) ? receiverTypeFromJSON(object.Type) : 0,
    };
  },

  toJSON(message: Receiver): unknown {
    const obj: any = {};
    if (message.Address !== "") {
      obj.Address = message.Address;
    }
    if (message.Type !== 0) {
      obj.Type = receiverTypeToJSON(message.Type);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<Receiver>, I>>(base?: I): Receiver {
    return Receiver.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<Receiver>, I>>(object: I): Receiver {
    const message = createBaseReceiver();
    message.Address = object.Address ?? "";
    message.Type = object.Type ?? 0;
    return message;
  },
};

type Builtin = Date | Function | Uint8Array | string | number | boolean | undefined;

export type DeepPartial<T> = T extends Builtin ? T
  : T extends globalThis.Array<infer U> ? globalThis.Array<DeepPartial<U>>
  : T extends ReadonlyArray<infer U> ? ReadonlyArray<DeepPartial<U>>
  : T extends {} ? { [K in keyof T]?: DeepPartial<T[K]> }
  : Partial<T>;

type KeysOfUnion<T> = T extends T ? keyof T : never;
export type Exact<P, I extends P> = P extends Builtin ? P
  : P & { [K in keyof P]: Exact<P[K], I[K]> } & { [K in Exclude<keyof I, KeysOfUnion<P>>]: never };

function toTimestamp(date: Date): Timestamp {
  const seconds = Math.trunc(date.getTime() / 1_000);
  const nanos = (date.getTime() % 1_000) * 1_000_000;
  return { seconds, nanos };
}

function fromTimestamp(t: Timestamp): Date {
  let millis = (t.seconds || 0) * 1_000;
  millis += (t.nanos || 0) / 1_000_000;
  return new globalThis.Date(millis);
}

function fromJsonTimestamp(o: any): Date {
  if (o instanceof globalThis.Date) {
    return o;
  } else if (typeof o === "string") {
    return new globalThis.Date(o);
  } else {
    return fromTimestamp(Timestamp.fromJSON(o));
  }
}

function longToNumber(long: Long): number {
  if (long.gt(globalThis.Number.MAX_SAFE_INTEGER)) {
    throw new globalThis.Error("Value is larger than Number.MAX_SAFE_INTEGER");
  }
  if (long.lt(globalThis.Number.MIN_SAFE_INTEGER)) {
    throw new globalThis.Error("Value is smaller than Number.MIN_SAFE_INTEGER");
  }
  return long.toNumber();
}

if (_m0.util.Long !== Long) {
  _m0.util.Long = Long as any;
  _m0.configure();
}

function isSet(value: any): boolean {
  return value !== null && value !== undefined;
}
