// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v1.181.2
//   protoc               v5.29.3
// source: sologenic/com-fs-order-model/order-grpc.proto

/* eslint-disable */
import Long from "long";
import _m0 from "protobufjs/minimal";
import { Empty } from "../../google/protobuf/empty";
import { Network, networkFromJSON, networkToJSON } from "../com-fs-utils-lib/models/metadata/metadata";
import {
  InternalOrderState,
  internalOrderStateFromJSON,
  internalOrderStateToJSON,
  Order,
  Orders,
  OrderStateType,
  orderStateTypeFromJSON,
  orderStateTypeToJSON,
  PaymentState,
  paymentStateFromJSON,
  paymentStateToJSON,
  TransactionType,
  transactionTypeFromJSON,
  transactionTypeToJSON,
} from "./order";
import { Key, OrderType, orderTypeFromJSON, orderTypeToJSON, ProcessInfo } from "./util";

export const protobufPackage = "order";

export interface UpsertMessage {
  Order: Order | undefined;
  OrderStepInstruction: OrderStepInstruction | undefined;
}

export interface OrderID {
  TXID: string;
  Network: Network;
}

export interface OrderQuery {
  Network: Network;
  Offset?: number | undefined;
  SmartContractAddr?: string | undefined;
  TransactionType?: TransactionType | undefined;
  TXID?: string | undefined;
  Height?: number | undefined;
  InternalOrderState?: InternalOrderState | undefined;
  ProcessInfo?:
    | ProcessInfo
    | undefined;
  /** Fields in OrderInstruction */
  Creator?: string | undefined;
  OrderID?: number | undefined;
  Denom?: string | undefined;
  OrderType?: OrderType | undefined;
  OrderStateType?: OrderStateType | undefined;
  PaymentState?: PaymentState | undefined;
}

export interface OrderStepInstruction {
  Key?: string | undefined;
  Order?: Order | undefined;
  MustHaveState: InternalOrderState[];
  TargetState: InternalOrderState;
}

function createBaseUpsertMessage(): UpsertMessage {
  return { Order: undefined, OrderStepInstruction: undefined };
}

export const UpsertMessage = {
  encode(message: UpsertMessage, writer: _m0.Writer = _m0.Writer.create()): _m0.Writer {
    if (message.Order !== undefined) {
      Order.encode(message.Order, writer.uint32(10).fork()).ldelim();
    }
    if (message.OrderStepInstruction !== undefined) {
      OrderStepInstruction.encode(message.OrderStepInstruction, writer.uint32(18).fork()).ldelim();
    }
    return writer;
  },

  decode(input: _m0.Reader | Uint8Array, length?: number): UpsertMessage {
    const reader = input instanceof _m0.Reader ? input : _m0.Reader.create(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseUpsertMessage();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1:
          if (tag !== 10) {
            break;
          }

          message.Order = Order.decode(reader, reader.uint32());
          continue;
        case 2:
          if (tag !== 18) {
            break;
          }

          message.OrderStepInstruction = OrderStepInstruction.decode(reader, reader.uint32());
          continue;
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skipType(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): UpsertMessage {
    return {
      Order: isSet(object.Order) ? Order.fromJSON(object.Order) : undefined,
      OrderStepInstruction: isSet(object.OrderStepInstruction)
        ? OrderStepInstruction.fromJSON(object.OrderStepInstruction)
        : undefined,
    };
  },

  toJSON(message: UpsertMessage): unknown {
    const obj: any = {};
    if (message.Order !== undefined) {
      obj.Order = Order.toJSON(message.Order);
    }
    if (message.OrderStepInstruction !== undefined) {
      obj.OrderStepInstruction = OrderStepInstruction.toJSON(message.OrderStepInstruction);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<UpsertMessage>, I>>(base?: I): UpsertMessage {
    return UpsertMessage.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<UpsertMessage>, I>>(object: I): UpsertMessage {
    const message = createBaseUpsertMessage();
    message.Order = (object.Order !== undefined && object.Order !== null) ? Order.fromPartial(object.Order) : undefined;
    message.OrderStepInstruction = (object.OrderStepInstruction !== undefined && object.OrderStepInstruction !== null)
      ? OrderStepInstruction.fromPartial(object.OrderStepInstruction)
      : undefined;
    return message;
  },
};

function createBaseOrderID(): OrderID {
  return { TXID: "", Network: 0 };
}

export const OrderID = {
  encode(message: OrderID, writer: _m0.Writer = _m0.Writer.create()): _m0.Writer {
    if (message.TXID !== "") {
      writer.uint32(10).string(message.TXID);
    }
    if (message.Network !== 0) {
      writer.uint32(16).int32(message.Network);
    }
    return writer;
  },

  decode(input: _m0.Reader | Uint8Array, length?: number): OrderID {
    const reader = input instanceof _m0.Reader ? input : _m0.Reader.create(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseOrderID();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1:
          if (tag !== 10) {
            break;
          }

          message.TXID = reader.string();
          continue;
        case 2:
          if (tag !== 16) {
            break;
          }

          message.Network = reader.int32() as any;
          continue;
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skipType(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): OrderID {
    return {
      TXID: isSet(object.TXID) ? globalThis.String(object.TXID) : "",
      Network: isSet(object.Network) ? networkFromJSON(object.Network) : 0,
    };
  },

  toJSON(message: OrderID): unknown {
    const obj: any = {};
    if (message.TXID !== "") {
      obj.TXID = message.TXID;
    }
    if (message.Network !== 0) {
      obj.Network = networkToJSON(message.Network);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<OrderID>, I>>(base?: I): OrderID {
    return OrderID.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<OrderID>, I>>(object: I): OrderID {
    const message = createBaseOrderID();
    message.TXID = object.TXID ?? "";
    message.Network = object.Network ?? 0;
    return message;
  },
};

function createBaseOrderQuery(): OrderQuery {
  return {
    Network: 0,
    Offset: undefined,
    SmartContractAddr: undefined,
    TransactionType: undefined,
    TXID: undefined,
    Height: undefined,
    InternalOrderState: undefined,
    ProcessInfo: undefined,
    Creator: undefined,
    OrderID: undefined,
    Denom: undefined,
    OrderType: undefined,
    OrderStateType: undefined,
    PaymentState: undefined,
  };
}

export const OrderQuery = {
  encode(message: OrderQuery, writer: _m0.Writer = _m0.Writer.create()): _m0.Writer {
    if (message.Network !== 0) {
      writer.uint32(8).int32(message.Network);
    }
    if (message.Offset !== undefined) {
      writer.uint32(16).int32(message.Offset);
    }
    if (message.SmartContractAddr !== undefined) {
      writer.uint32(26).string(message.SmartContractAddr);
    }
    if (message.TransactionType !== undefined) {
      writer.uint32(32).int32(message.TransactionType);
    }
    if (message.TXID !== undefined) {
      writer.uint32(42).string(message.TXID);
    }
    if (message.Height !== undefined) {
      writer.uint32(48).int64(message.Height);
    }
    if (message.InternalOrderState !== undefined) {
      writer.uint32(56).int32(message.InternalOrderState);
    }
    if (message.ProcessInfo !== undefined) {
      ProcessInfo.encode(message.ProcessInfo, writer.uint32(66).fork()).ldelim();
    }
    if (message.Creator !== undefined) {
      writer.uint32(74).string(message.Creator);
    }
    if (message.OrderID !== undefined) {
      writer.uint32(80).int64(message.OrderID);
    }
    if (message.Denom !== undefined) {
      writer.uint32(90).string(message.Denom);
    }
    if (message.OrderType !== undefined) {
      writer.uint32(96).int32(message.OrderType);
    }
    if (message.OrderStateType !== undefined) {
      writer.uint32(104).int32(message.OrderStateType);
    }
    if (message.PaymentState !== undefined) {
      writer.uint32(112).int32(message.PaymentState);
    }
    return writer;
  },

  decode(input: _m0.Reader | Uint8Array, length?: number): OrderQuery {
    const reader = input instanceof _m0.Reader ? input : _m0.Reader.create(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseOrderQuery();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1:
          if (tag !== 8) {
            break;
          }

          message.Network = reader.int32() as any;
          continue;
        case 2:
          if (tag !== 16) {
            break;
          }

          message.Offset = reader.int32();
          continue;
        case 3:
          if (tag !== 26) {
            break;
          }

          message.SmartContractAddr = reader.string();
          continue;
        case 4:
          if (tag !== 32) {
            break;
          }

          message.TransactionType = reader.int32() as any;
          continue;
        case 5:
          if (tag !== 42) {
            break;
          }

          message.TXID = reader.string();
          continue;
        case 6:
          if (tag !== 48) {
            break;
          }

          message.Height = longToNumber(reader.int64() as Long);
          continue;
        case 7:
          if (tag !== 56) {
            break;
          }

          message.InternalOrderState = reader.int32() as any;
          continue;
        case 8:
          if (tag !== 66) {
            break;
          }

          message.ProcessInfo = ProcessInfo.decode(reader, reader.uint32());
          continue;
        case 9:
          if (tag !== 74) {
            break;
          }

          message.Creator = reader.string();
          continue;
        case 10:
          if (tag !== 80) {
            break;
          }

          message.OrderID = longToNumber(reader.int64() as Long);
          continue;
        case 11:
          if (tag !== 90) {
            break;
          }

          message.Denom = reader.string();
          continue;
        case 12:
          if (tag !== 96) {
            break;
          }

          message.OrderType = reader.int32() as any;
          continue;
        case 13:
          if (tag !== 104) {
            break;
          }

          message.OrderStateType = reader.int32() as any;
          continue;
        case 14:
          if (tag !== 112) {
            break;
          }

          message.PaymentState = reader.int32() as any;
          continue;
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skipType(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): OrderQuery {
    return {
      Network: isSet(object.Network) ? networkFromJSON(object.Network) : 0,
      Offset: isSet(object.Offset) ? globalThis.Number(object.Offset) : undefined,
      SmartContractAddr: isSet(object.SmartContractAddr) ? globalThis.String(object.SmartContractAddr) : undefined,
      TransactionType: isSet(object.TransactionType) ? transactionTypeFromJSON(object.TransactionType) : undefined,
      TXID: isSet(object.TXID) ? globalThis.String(object.TXID) : undefined,
      Height: isSet(object.Height) ? globalThis.Number(object.Height) : undefined,
      InternalOrderState: isSet(object.InternalOrderState)
        ? internalOrderStateFromJSON(object.InternalOrderState)
        : undefined,
      ProcessInfo: isSet(object.ProcessInfo) ? ProcessInfo.fromJSON(object.ProcessInfo) : undefined,
      Creator: isSet(object.Creator) ? globalThis.String(object.Creator) : undefined,
      OrderID: isSet(object.OrderID) ? globalThis.Number(object.OrderID) : undefined,
      Denom: isSet(object.Denom) ? globalThis.String(object.Denom) : undefined,
      OrderType: isSet(object.OrderType) ? orderTypeFromJSON(object.OrderType) : undefined,
      OrderStateType: isSet(object.OrderStateType) ? orderStateTypeFromJSON(object.OrderStateType) : undefined,
      PaymentState: isSet(object.PaymentState) ? paymentStateFromJSON(object.PaymentState) : undefined,
    };
  },

  toJSON(message: OrderQuery): unknown {
    const obj: any = {};
    if (message.Network !== 0) {
      obj.Network = networkToJSON(message.Network);
    }
    if (message.Offset !== undefined) {
      obj.Offset = Math.round(message.Offset);
    }
    if (message.SmartContractAddr !== undefined) {
      obj.SmartContractAddr = message.SmartContractAddr;
    }
    if (message.TransactionType !== undefined) {
      obj.TransactionType = transactionTypeToJSON(message.TransactionType);
    }
    if (message.TXID !== undefined) {
      obj.TXID = message.TXID;
    }
    if (message.Height !== undefined) {
      obj.Height = Math.round(message.Height);
    }
    if (message.InternalOrderState !== undefined) {
      obj.InternalOrderState = internalOrderStateToJSON(message.InternalOrderState);
    }
    if (message.ProcessInfo !== undefined) {
      obj.ProcessInfo = ProcessInfo.toJSON(message.ProcessInfo);
    }
    if (message.Creator !== undefined) {
      obj.Creator = message.Creator;
    }
    if (message.OrderID !== undefined) {
      obj.OrderID = Math.round(message.OrderID);
    }
    if (message.Denom !== undefined) {
      obj.Denom = message.Denom;
    }
    if (message.OrderType !== undefined) {
      obj.OrderType = orderTypeToJSON(message.OrderType);
    }
    if (message.OrderStateType !== undefined) {
      obj.OrderStateType = orderStateTypeToJSON(message.OrderStateType);
    }
    if (message.PaymentState !== undefined) {
      obj.PaymentState = paymentStateToJSON(message.PaymentState);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<OrderQuery>, I>>(base?: I): OrderQuery {
    return OrderQuery.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<OrderQuery>, I>>(object: I): OrderQuery {
    const message = createBaseOrderQuery();
    message.Network = object.Network ?? 0;
    message.Offset = object.Offset ?? undefined;
    message.SmartContractAddr = object.SmartContractAddr ?? undefined;
    message.TransactionType = object.TransactionType ?? undefined;
    message.TXID = object.TXID ?? undefined;
    message.Height = object.Height ?? undefined;
    message.InternalOrderState = object.InternalOrderState ?? undefined;
    message.ProcessInfo = (object.ProcessInfo !== undefined && object.ProcessInfo !== null)
      ? ProcessInfo.fromPartial(object.ProcessInfo)
      : undefined;
    message.Creator = object.Creator ?? undefined;
    message.OrderID = object.OrderID ?? undefined;
    message.Denom = object.Denom ?? undefined;
    message.OrderType = object.OrderType ?? undefined;
    message.OrderStateType = object.OrderStateType ?? undefined;
    message.PaymentState = object.PaymentState ?? undefined;
    return message;
  },
};

function createBaseOrderStepInstruction(): OrderStepInstruction {
  return { Key: undefined, Order: undefined, MustHaveState: [], TargetState: 0 };
}

export const OrderStepInstruction = {
  encode(message: OrderStepInstruction, writer: _m0.Writer = _m0.Writer.create()): _m0.Writer {
    if (message.Key !== undefined) {
      writer.uint32(10).string(message.Key);
    }
    if (message.Order !== undefined) {
      Order.encode(message.Order, writer.uint32(18).fork()).ldelim();
    }
    writer.uint32(26).fork();
    for (const v of message.MustHaveState) {
      writer.int32(v);
    }
    writer.ldelim();
    if (message.TargetState !== 0) {
      writer.uint32(32).int32(message.TargetState);
    }
    return writer;
  },

  decode(input: _m0.Reader | Uint8Array, length?: number): OrderStepInstruction {
    const reader = input instanceof _m0.Reader ? input : _m0.Reader.create(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseOrderStepInstruction();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1:
          if (tag !== 10) {
            break;
          }

          message.Key = reader.string();
          continue;
        case 2:
          if (tag !== 18) {
            break;
          }

          message.Order = Order.decode(reader, reader.uint32());
          continue;
        case 3:
          if (tag === 24) {
            message.MustHaveState.push(reader.int32() as any);

            continue;
          }

          if (tag === 26) {
            const end2 = reader.uint32() + reader.pos;
            while (reader.pos < end2) {
              message.MustHaveState.push(reader.int32() as any);
            }

            continue;
          }

          break;
        case 4:
          if (tag !== 32) {
            break;
          }

          message.TargetState = reader.int32() as any;
          continue;
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skipType(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): OrderStepInstruction {
    return {
      Key: isSet(object.Key) ? globalThis.String(object.Key) : undefined,
      Order: isSet(object.Order) ? Order.fromJSON(object.Order) : undefined,
      MustHaveState: globalThis.Array.isArray(object?.MustHaveState)
        ? object.MustHaveState.map((e: any) => internalOrderStateFromJSON(e))
        : [],
      TargetState: isSet(object.TargetState) ? internalOrderStateFromJSON(object.TargetState) : 0,
    };
  },

  toJSON(message: OrderStepInstruction): unknown {
    const obj: any = {};
    if (message.Key !== undefined) {
      obj.Key = message.Key;
    }
    if (message.Order !== undefined) {
      obj.Order = Order.toJSON(message.Order);
    }
    if (message.MustHaveState?.length) {
      obj.MustHaveState = message.MustHaveState.map((e) => internalOrderStateToJSON(e));
    }
    if (message.TargetState !== 0) {
      obj.TargetState = internalOrderStateToJSON(message.TargetState);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<OrderStepInstruction>, I>>(base?: I): OrderStepInstruction {
    return OrderStepInstruction.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<OrderStepInstruction>, I>>(object: I): OrderStepInstruction {
    const message = createBaseOrderStepInstruction();
    message.Key = object.Key ?? undefined;
    message.Order = (object.Order !== undefined && object.Order !== null) ? Order.fromPartial(object.Order) : undefined;
    message.MustHaveState = object.MustHaveState?.map((e) => e) || [];
    message.TargetState = object.TargetState ?? 0;
    return message;
  },
};

export interface OrderService {
  GetByID(request: OrderID): Promise<Order>;
  GetByKey(request: Key): Promise<Order>;
  GetAll(request: OrderQuery): Promise<Orders>;
  /** TODO: determine if we need this method: recovery uses unprocessed (open or locked) logs */
  GetAllUnfinished(request: Empty): Promise<Orders>;
  /** Transactional operations */
  UpsertWithState(request: UpsertMessage): Promise<OrderID>;
  UpdateStep(request: OrderStepInstruction): Promise<Order>;
}

export const OrderServiceServiceName = "order.OrderService";
export class OrderServiceClientImpl implements OrderService {
  private readonly rpc: Rpc;
  private readonly service: string;
  constructor(rpc: Rpc, opts?: { service?: string }) {
    this.service = opts?.service || OrderServiceServiceName;
    this.rpc = rpc;
    this.GetByID = this.GetByID.bind(this);
    this.GetByKey = this.GetByKey.bind(this);
    this.GetAll = this.GetAll.bind(this);
    this.GetAllUnfinished = this.GetAllUnfinished.bind(this);
    this.UpsertWithState = this.UpsertWithState.bind(this);
    this.UpdateStep = this.UpdateStep.bind(this);
  }
  GetByID(request: OrderID): Promise<Order> {
    const data = OrderID.encode(request).finish();
    const promise = this.rpc.request(this.service, "GetByID", data);
    return promise.then((data) => Order.decode(_m0.Reader.create(data)));
  }

  GetByKey(request: Key): Promise<Order> {
    const data = Key.encode(request).finish();
    const promise = this.rpc.request(this.service, "GetByKey", data);
    return promise.then((data) => Order.decode(_m0.Reader.create(data)));
  }

  GetAll(request: OrderQuery): Promise<Orders> {
    const data = OrderQuery.encode(request).finish();
    const promise = this.rpc.request(this.service, "GetAll", data);
    return promise.then((data) => Orders.decode(_m0.Reader.create(data)));
  }

  GetAllUnfinished(request: Empty): Promise<Orders> {
    const data = Empty.encode(request).finish();
    const promise = this.rpc.request(this.service, "GetAllUnfinished", data);
    return promise.then((data) => Orders.decode(_m0.Reader.create(data)));
  }

  UpsertWithState(request: UpsertMessage): Promise<OrderID> {
    const data = UpsertMessage.encode(request).finish();
    const promise = this.rpc.request(this.service, "UpsertWithState", data);
    return promise.then((data) => OrderID.decode(_m0.Reader.create(data)));
  }

  UpdateStep(request: OrderStepInstruction): Promise<Order> {
    const data = OrderStepInstruction.encode(request).finish();
    const promise = this.rpc.request(this.service, "UpdateStep", data);
    return promise.then((data) => Order.decode(_m0.Reader.create(data)));
  }
}

interface Rpc {
  request(service: string, method: string, data: Uint8Array): Promise<Uint8Array>;
}

type Builtin = Date | Function | Uint8Array | string | number | boolean | undefined;

export type DeepPartial<T> = T extends Builtin ? T
  : T extends globalThis.Array<infer U> ? globalThis.Array<DeepPartial<U>>
  : T extends ReadonlyArray<infer U> ? ReadonlyArray<DeepPartial<U>>
  : T extends {} ? { [K in keyof T]?: DeepPartial<T[K]> }
  : Partial<T>;

type KeysOfUnion<T> = T extends T ? keyof T : never;
export type Exact<P, I extends P> = P extends Builtin ? P
  : P & { [K in keyof P]: Exact<P[K], I[K]> } & { [K in Exclude<keyof I, KeysOfUnion<P>>]: never };

function longToNumber(long: Long): number {
  if (long.gt(globalThis.Number.MAX_SAFE_INTEGER)) {
    throw new globalThis.Error("Value is larger than Number.MAX_SAFE_INTEGER");
  }
  if (long.lt(globalThis.Number.MIN_SAFE_INTEGER)) {
    throw new globalThis.Error("Value is smaller than Number.MIN_SAFE_INTEGER");
  }
  return long.toNumber();
}

if (_m0.util.Long !== Long) {
  _m0.util.Long = Long as any;
  _m0.configure();
}

function isSet(value: any): boolean {
  return value !== null && value !== undefined;
}
