// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v1.181.2
//   protoc               v5.29.1
// source: sologenic/com-fs-order-model/smartcontractlog-grpc.proto

/* eslint-disable */
import _m0 from "protobufjs/minimal";
import { Empty } from "../../google/protobuf/empty";
import { Order, Orders } from "./order";
import { InstanceID, Key, LockLogRecord } from "./util";

export const protobufPackage = "order";

/** Smart Contract Log */
export interface SmartContractLogService {
  Create(request: Order): Promise<Key>;
  /** Transaction */
  SetLock(request: LockLogRecord): Promise<Order>;
  /** For recovery, get all unprocessed Smart Contract Logs. Unprocessed logs are logs that are in the states `OPEN` or `LOCKED`. */
  GetAllUnprocessed(request: InstanceID): Promise<Orders>;
  /** Starting point for rescanner */
  GetLatest(request: Empty): Promise<Order>;
}

export const SmartContractLogServiceServiceName = "order.SmartContractLogService";
export class SmartContractLogServiceClientImpl implements SmartContractLogService {
  private readonly rpc: Rpc;
  private readonly service: string;
  constructor(rpc: Rpc, opts?: { service?: string }) {
    this.service = opts?.service || SmartContractLogServiceServiceName;
    this.rpc = rpc;
    this.Create = this.Create.bind(this);
    this.SetLock = this.SetLock.bind(this);
    this.GetAllUnprocessed = this.GetAllUnprocessed.bind(this);
    this.GetLatest = this.GetLatest.bind(this);
  }
  Create(request: Order): Promise<Key> {
    const data = Order.encode(request).finish();
    const promise = this.rpc.request(this.service, "Create", data);
    return promise.then((data) => Key.decode(_m0.Reader.create(data)));
  }

  SetLock(request: LockLogRecord): Promise<Order> {
    const data = LockLogRecord.encode(request).finish();
    const promise = this.rpc.request(this.service, "SetLock", data);
    return promise.then((data) => Order.decode(_m0.Reader.create(data)));
  }

  GetAllUnprocessed(request: InstanceID): Promise<Orders> {
    const data = InstanceID.encode(request).finish();
    const promise = this.rpc.request(this.service, "GetAllUnprocessed", data);
    return promise.then((data) => Orders.decode(_m0.Reader.create(data)));
  }

  GetLatest(request: Empty): Promise<Order> {
    const data = Empty.encode(request).finish();
    const promise = this.rpc.request(this.service, "GetLatest", data);
    return promise.then((data) => Order.decode(_m0.Reader.create(data)));
  }
}

interface Rpc {
  request(service: string, method: string, data: Uint8Array): Promise<Uint8Array>;
}
