// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             v4.24.3
// source: smartcontract-grpc.proto

package order

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	SmartContractLogService_CreateSmartContractLog_FullMethodName  = "/order.SmartContractLogService/CreateSmartContractLog"
	SmartContractLogService_UpdateSmartContractLog_FullMethodName  = "/order.SmartContractLogService/UpdateSmartContractLog"
	SmartContractLogService_SetSmartContractLogLock_FullMethodName = "/order.SmartContractLogService/SetSmartContractLogLock"
)

// SmartContractLogServiceClient is the client API for SmartContractLogService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type SmartContractLogServiceClient interface {
	// Non-transaction
	CreateSmartContractLog(ctx context.Context, in *Order, opts ...grpc.CallOption) (*emptypb.Empty, error)
	// TODO: determine if we will need the Update method -> with the introduction of the LockLogRecord message,
	// we can handle the must have state and target state dynamically. Therefore, we may not need the Update method.
	UpdateSmartContractLog(ctx context.Context, in *Order, opts ...grpc.CallOption) (*emptypb.Empty, error)
	// Transaction
	SetSmartContractLogLock(ctx context.Context, in *LockLogRecord, opts ...grpc.CallOption) (*Order, error)
}

type smartContractLogServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewSmartContractLogServiceClient(cc grpc.ClientConnInterface) SmartContractLogServiceClient {
	return &smartContractLogServiceClient{cc}
}

func (c *smartContractLogServiceClient) CreateSmartContractLog(ctx context.Context, in *Order, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, SmartContractLogService_CreateSmartContractLog_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *smartContractLogServiceClient) UpdateSmartContractLog(ctx context.Context, in *Order, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, SmartContractLogService_UpdateSmartContractLog_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *smartContractLogServiceClient) SetSmartContractLogLock(ctx context.Context, in *LockLogRecord, opts ...grpc.CallOption) (*Order, error) {
	out := new(Order)
	err := c.cc.Invoke(ctx, SmartContractLogService_SetSmartContractLogLock_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// SmartContractLogServiceServer is the server API for SmartContractLogService service.
// All implementations should embed UnimplementedSmartContractLogServiceServer
// for forward compatibility
type SmartContractLogServiceServer interface {
	// Non-transaction
	CreateSmartContractLog(context.Context, *Order) (*emptypb.Empty, error)
	// TODO: determine if we will need the Update method -> with the introduction of the LockLogRecord message,
	// we can handle the must have state and target state dynamically. Therefore, we may not need the Update method.
	UpdateSmartContractLog(context.Context, *Order) (*emptypb.Empty, error)
	// Transaction
	SetSmartContractLogLock(context.Context, *LockLogRecord) (*Order, error)
}

// UnimplementedSmartContractLogServiceServer should be embedded to have forward compatible implementations.
type UnimplementedSmartContractLogServiceServer struct {
}

func (UnimplementedSmartContractLogServiceServer) CreateSmartContractLog(context.Context, *Order) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateSmartContractLog not implemented")
}
func (UnimplementedSmartContractLogServiceServer) UpdateSmartContractLog(context.Context, *Order) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateSmartContractLog not implemented")
}
func (UnimplementedSmartContractLogServiceServer) SetSmartContractLogLock(context.Context, *LockLogRecord) (*Order, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SetSmartContractLogLock not implemented")
}

// UnsafeSmartContractLogServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to SmartContractLogServiceServer will
// result in compilation errors.
type UnsafeSmartContractLogServiceServer interface {
	mustEmbedUnimplementedSmartContractLogServiceServer()
}

func RegisterSmartContractLogServiceServer(s grpc.ServiceRegistrar, srv SmartContractLogServiceServer) {
	s.RegisterService(&SmartContractLogService_ServiceDesc, srv)
}

func _SmartContractLogService_CreateSmartContractLog_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Order)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SmartContractLogServiceServer).CreateSmartContractLog(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SmartContractLogService_CreateSmartContractLog_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SmartContractLogServiceServer).CreateSmartContractLog(ctx, req.(*Order))
	}
	return interceptor(ctx, in, info, handler)
}

func _SmartContractLogService_UpdateSmartContractLog_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Order)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SmartContractLogServiceServer).UpdateSmartContractLog(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SmartContractLogService_UpdateSmartContractLog_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SmartContractLogServiceServer).UpdateSmartContractLog(ctx, req.(*Order))
	}
	return interceptor(ctx, in, info, handler)
}

func _SmartContractLogService_SetSmartContractLogLock_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LockLogRecord)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SmartContractLogServiceServer).SetSmartContractLogLock(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SmartContractLogService_SetSmartContractLogLock_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SmartContractLogServiceServer).SetSmartContractLogLock(ctx, req.(*LockLogRecord))
	}
	return interceptor(ctx, in, info, handler)
}

// SmartContractLogService_ServiceDesc is the grpc.ServiceDesc for SmartContractLogService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var SmartContractLogService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "order.SmartContractLogService",
	HandlerType: (*SmartContractLogServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateSmartContractLog",
			Handler:    _SmartContractLogService_CreateSmartContractLog_Handler,
		},
		{
			MethodName: "UpdateSmartContractLog",
			Handler:    _SmartContractLogService_UpdateSmartContractLog_Handler,
		},
		{
			MethodName: "SetSmartContractLogLock",
			Handler:    _SmartContractLogService_SetSmartContractLogLock_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "smartcontract-grpc.proto",
}
