// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             v5.29.1
// source: smartcontract-grpc.proto

package order

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	SmartContractLogService_Create_FullMethodName            = "/order.SmartContractLogService/Create"
	SmartContractLogService_SetLock_FullMethodName           = "/order.SmartContractLogService/SetLock"
	SmartContractLogService_GetAllUnprocessed_FullMethodName = "/order.SmartContractLogService/GetAllUnprocessed"
	SmartContractLogService_GetLatest_FullMethodName         = "/order.SmartContractLogService/GetLatest"
)

// SmartContractLogServiceClient is the client API for SmartContractLogService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type SmartContractLogServiceClient interface {
	Create(ctx context.Context, in *Order, opts ...grpc.CallOption) (*Key, error)
	// Transaction
	SetLock(ctx context.Context, in *LockLogRecord, opts ...grpc.CallOption) (*Order, error)
	// For recovery, get all unprocessed Smart Contract Logs. Unprocessed logs are logs that are in the states `OPEN` or `LOCKED`.
	GetAllUnprocessed(ctx context.Context, in *InstanceID, opts ...grpc.CallOption) (*Orders, error)
	// Starting point for rescanner
	GetLatest(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*Order, error)
}

type smartContractLogServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewSmartContractLogServiceClient(cc grpc.ClientConnInterface) SmartContractLogServiceClient {
	return &smartContractLogServiceClient{cc}
}

func (c *smartContractLogServiceClient) Create(ctx context.Context, in *Order, opts ...grpc.CallOption) (*Key, error) {
	out := new(Key)
	err := c.cc.Invoke(ctx, SmartContractLogService_Create_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *smartContractLogServiceClient) SetLock(ctx context.Context, in *LockLogRecord, opts ...grpc.CallOption) (*Order, error) {
	out := new(Order)
	err := c.cc.Invoke(ctx, SmartContractLogService_SetLock_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *smartContractLogServiceClient) GetAllUnprocessed(ctx context.Context, in *InstanceID, opts ...grpc.CallOption) (*Orders, error) {
	out := new(Orders)
	err := c.cc.Invoke(ctx, SmartContractLogService_GetAllUnprocessed_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *smartContractLogServiceClient) GetLatest(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*Order, error) {
	out := new(Order)
	err := c.cc.Invoke(ctx, SmartContractLogService_GetLatest_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// SmartContractLogServiceServer is the server API for SmartContractLogService service.
// All implementations should embed UnimplementedSmartContractLogServiceServer
// for forward compatibility
type SmartContractLogServiceServer interface {
	Create(context.Context, *Order) (*Key, error)
	// Transaction
	SetLock(context.Context, *LockLogRecord) (*Order, error)
	// For recovery, get all unprocessed Smart Contract Logs. Unprocessed logs are logs that are in the states `OPEN` or `LOCKED`.
	GetAllUnprocessed(context.Context, *InstanceID) (*Orders, error)
	// Starting point for rescanner
	GetLatest(context.Context, *emptypb.Empty) (*Order, error)
}

// UnimplementedSmartContractLogServiceServer should be embedded to have forward compatible implementations.
type UnimplementedSmartContractLogServiceServer struct {
}

func (UnimplementedSmartContractLogServiceServer) Create(context.Context, *Order) (*Key, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Create not implemented")
}
func (UnimplementedSmartContractLogServiceServer) SetLock(context.Context, *LockLogRecord) (*Order, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SetLock not implemented")
}
func (UnimplementedSmartContractLogServiceServer) GetAllUnprocessed(context.Context, *InstanceID) (*Orders, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetAllUnprocessed not implemented")
}
func (UnimplementedSmartContractLogServiceServer) GetLatest(context.Context, *emptypb.Empty) (*Order, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetLatest not implemented")
}

// UnsafeSmartContractLogServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to SmartContractLogServiceServer will
// result in compilation errors.
type UnsafeSmartContractLogServiceServer interface {
	mustEmbedUnimplementedSmartContractLogServiceServer()
}

func RegisterSmartContractLogServiceServer(s grpc.ServiceRegistrar, srv SmartContractLogServiceServer) {
	s.RegisterService(&SmartContractLogService_ServiceDesc, srv)
}

func _SmartContractLogService_Create_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Order)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SmartContractLogServiceServer).Create(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SmartContractLogService_Create_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SmartContractLogServiceServer).Create(ctx, req.(*Order))
	}
	return interceptor(ctx, in, info, handler)
}

func _SmartContractLogService_SetLock_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LockLogRecord)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SmartContractLogServiceServer).SetLock(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SmartContractLogService_SetLock_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SmartContractLogServiceServer).SetLock(ctx, req.(*LockLogRecord))
	}
	return interceptor(ctx, in, info, handler)
}

func _SmartContractLogService_GetAllUnprocessed_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(InstanceID)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SmartContractLogServiceServer).GetAllUnprocessed(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SmartContractLogService_GetAllUnprocessed_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SmartContractLogServiceServer).GetAllUnprocessed(ctx, req.(*InstanceID))
	}
	return interceptor(ctx, in, info, handler)
}

func _SmartContractLogService_GetLatest_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(emptypb.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SmartContractLogServiceServer).GetLatest(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SmartContractLogService_GetLatest_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SmartContractLogServiceServer).GetLatest(ctx, req.(*emptypb.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

// SmartContractLogService_ServiceDesc is the grpc.ServiceDesc for SmartContractLogService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var SmartContractLogService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "order.SmartContractLogService",
	HandlerType: (*SmartContractLogServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Create",
			Handler:    _SmartContractLogService_Create_Handler,
		},
		{
			MethodName: "SetLock",
			Handler:    _SmartContractLogService_SetLock_Handler,
		},
		{
			MethodName: "GetAllUnprocessed",
			Handler:    _SmartContractLogService_GetAllUnprocessed_Handler,
		},
		{
			MethodName: "GetLatest",
			Handler:    _SmartContractLogService_GetLatest_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "smartcontract-grpc.proto",
}
