syntax = "proto3";

package order;

import "google/protobuf/empty.proto";
import "order.proto";
import "util.proto";

option go_package = "github.com/sologenic/com-fs-order-model;order";

// Smart Contract Log
service SmartContractLogService {
  rpc Create(Order) returns (Key) {}

  // rpc Get(Filter) returns (Records) {}
  
  // Transaction
  rpc SetLock(LockLogRecord) returns (Order) {}

  // For recovery, get all unprocessed Smart Contract Logs. Unprocessed logs are logs that are in the states `OPEN` or `LOCKED`.
  rpc GetAllUnprocessed(InstanceID) returns (Orders) {}
  // Starting point for rescanner
  rpc GetLatest(google.protobuf.Empty) returns (Order) {}
}
