// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: sologenic/com-fs-order-model/smartcontractlog-grpc.proto

package order

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

var File_sologenic_com_fs_order_model_smartcontractlog_grpc_proto protoreflect.FileDescriptor

const file_sologenic_com_fs_order_model_smartcontractlog_grpc_proto_rawDesc = "" +
	"\n" +
	"8sologenic/com-fs-order-model/smartcontractlog-grpc.proto\x12\x05order\x1a\x1bgoogle/protobuf/empty.proto\x1a(sologenic/com-fs-order-model/order.proto\x1a'sologenic/com-fs-order-model/util.proto2\xde\x01\n" +
	"\x17SmartContractLogService\x12$\n" +
	"\x06Create\x12\f.order.Order\x1a\n" +
	".order.Key\"\x00\x12/\n" +
	"\aSetLock\x12\x14.order.LockLogRecord\x1a\f.order.Order\"\x00\x127\n" +
	"\x11GetAllUnprocessed\x12\x11.order.InstanceID\x1a\r.order.Orders\"\x00\x123\n" +
	"\tGetLatest\x12\x16.google.protobuf.Empty\x1a\f.order.Order\"\x00B/Z-github.com/sologenic/com-fs-order-model;orderb\x06proto3"

var file_sologenic_com_fs_order_model_smartcontractlog_grpc_proto_goTypes = []any{
	(*Order)(nil),         // 0: order.Order
	(*LockLogRecord)(nil), // 1: order.LockLogRecord
	(*InstanceID)(nil),    // 2: order.InstanceID
	(*emptypb.Empty)(nil), // 3: google.protobuf.Empty
	(*Key)(nil),           // 4: order.Key
	(*Orders)(nil),        // 5: order.Orders
}
var file_sologenic_com_fs_order_model_smartcontractlog_grpc_proto_depIdxs = []int32{
	0, // 0: order.SmartContractLogService.Create:input_type -> order.Order
	1, // 1: order.SmartContractLogService.SetLock:input_type -> order.LockLogRecord
	2, // 2: order.SmartContractLogService.GetAllUnprocessed:input_type -> order.InstanceID
	3, // 3: order.SmartContractLogService.GetLatest:input_type -> google.protobuf.Empty
	4, // 4: order.SmartContractLogService.Create:output_type -> order.Key
	0, // 5: order.SmartContractLogService.SetLock:output_type -> order.Order
	5, // 6: order.SmartContractLogService.GetAllUnprocessed:output_type -> order.Orders
	0, // 7: order.SmartContractLogService.GetLatest:output_type -> order.Order
	4, // [4:8] is the sub-list for method output_type
	0, // [0:4] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_sologenic_com_fs_order_model_smartcontractlog_grpc_proto_init() }
func file_sologenic_com_fs_order_model_smartcontractlog_grpc_proto_init() {
	if File_sologenic_com_fs_order_model_smartcontractlog_grpc_proto != nil {
		return
	}
	file_sologenic_com_fs_order_model_order_proto_init()
	file_sologenic_com_fs_order_model_util_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_sologenic_com_fs_order_model_smartcontractlog_grpc_proto_rawDesc), len(file_sologenic_com_fs_order_model_smartcontractlog_grpc_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_sologenic_com_fs_order_model_smartcontractlog_grpc_proto_goTypes,
		DependencyIndexes: file_sologenic_com_fs_order_model_smartcontractlog_grpc_proto_depIdxs,
	}.Build()
	File_sologenic_com_fs_order_model_smartcontractlog_grpc_proto = out.File
	file_sologenic_com_fs_order_model_smartcontractlog_grpc_proto_goTypes = nil
	file_sologenic_com_fs_order_model_smartcontractlog_grpc_proto_depIdxs = nil
}
