// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package order

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// SmartContractLogServiceClient is the client API for SmartContractLogService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type SmartContractLogServiceClient interface {
	// Non-transaction
	Create(ctx context.Context, in *Order, opts ...grpc.CallOption) (*Key, error)
	// TODO: determine if we will need the Update method -> with the introduction of the LockLogRecord message,
	// we can handle the must have state and target state dynamically. Therefore, we may not need the Update method.
	Update(ctx context.Context, in *Order, opts ...grpc.CallOption) (*emptypb.Empty, error)
	// Transaction
	SetLock(ctx context.Context, in *LockLogRecord, opts ...grpc.CallOption) (*Order, error)
}

type smartContractLogServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewSmartContractLogServiceClient(cc grpc.ClientConnInterface) SmartContractLogServiceClient {
	return &smartContractLogServiceClient{cc}
}

func (c *smartContractLogServiceClient) Create(ctx context.Context, in *Order, opts ...grpc.CallOption) (*Key, error) {
	out := new(Key)
	err := c.cc.Invoke(ctx, "/order.SmartContractLogService/Create", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *smartContractLogServiceClient) Update(ctx context.Context, in *Order, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, "/order.SmartContractLogService/Update", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *smartContractLogServiceClient) SetLock(ctx context.Context, in *LockLogRecord, opts ...grpc.CallOption) (*Order, error) {
	out := new(Order)
	err := c.cc.Invoke(ctx, "/order.SmartContractLogService/SetLock", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// SmartContractLogServiceServer is the server API for SmartContractLogService service.
// All implementations should embed UnimplementedSmartContractLogServiceServer
// for forward compatibility
type SmartContractLogServiceServer interface {
	// Non-transaction
	Create(context.Context, *Order) (*Key, error)
	// TODO: determine if we will need the Update method -> with the introduction of the LockLogRecord message,
	// we can handle the must have state and target state dynamically. Therefore, we may not need the Update method.
	Update(context.Context, *Order) (*emptypb.Empty, error)
	// Transaction
	SetLock(context.Context, *LockLogRecord) (*Order, error)
}

// UnimplementedSmartContractLogServiceServer should be embedded to have forward compatible implementations.
type UnimplementedSmartContractLogServiceServer struct {
}

func (UnimplementedSmartContractLogServiceServer) Create(context.Context, *Order) (*Key, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Create not implemented")
}
func (UnimplementedSmartContractLogServiceServer) Update(context.Context, *Order) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Update not implemented")
}
func (UnimplementedSmartContractLogServiceServer) SetLock(context.Context, *LockLogRecord) (*Order, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SetLock not implemented")
}

// UnsafeSmartContractLogServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to SmartContractLogServiceServer will
// result in compilation errors.
type UnsafeSmartContractLogServiceServer interface {
	mustEmbedUnimplementedSmartContractLogServiceServer()
}

func RegisterSmartContractLogServiceServer(s grpc.ServiceRegistrar, srv SmartContractLogServiceServer) {
	s.RegisterService(&SmartContractLogService_ServiceDesc, srv)
}

func _SmartContractLogService_Create_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Order)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SmartContractLogServiceServer).Create(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/order.SmartContractLogService/Create",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SmartContractLogServiceServer).Create(ctx, req.(*Order))
	}
	return interceptor(ctx, in, info, handler)
}

func _SmartContractLogService_Update_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Order)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SmartContractLogServiceServer).Update(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/order.SmartContractLogService/Update",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SmartContractLogServiceServer).Update(ctx, req.(*Order))
	}
	return interceptor(ctx, in, info, handler)
}

func _SmartContractLogService_SetLock_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LockLogRecord)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SmartContractLogServiceServer).SetLock(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/order.SmartContractLogService/SetLock",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SmartContractLogServiceServer).SetLock(ctx, req.(*LockLogRecord))
	}
	return interceptor(ctx, in, info, handler)
}

// SmartContractLogService_ServiceDesc is the grpc.ServiceDesc for SmartContractLogService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var SmartContractLogService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "order.SmartContractLogService",
	HandlerType: (*SmartContractLogServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Create",
			Handler:    _SmartContractLogService_Create_Handler,
		},
		{
			MethodName: "Update",
			Handler:    _SmartContractLogService_Update_Handler,
		},
		{
			MethodName: "SetLock",
			Handler:    _SmartContractLogService_SetLock_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "smartcontract-grpc.proto",
}
