// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: util.proto

package order

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type OrderType int32

const (
	OrderType_NOT_USED_ORDER_TYPE OrderType = 0
	OrderType_ORDER_TYPE_PURCHASE OrderType = 1 // Avoid naming conflicts with PURCHASE in the action enum
	OrderType_ORDER_TYPE_SELL     OrderType = 2
)

// Enum value maps for OrderType.
var (
	OrderType_name = map[int32]string{
		0: "NOT_USED_ORDER_TYPE",
		1: "ORDER_TYPE_PURCHASE",
		2: "ORDER_TYPE_SELL",
	}
	OrderType_value = map[string]int32{
		"NOT_USED_ORDER_TYPE": 0,
		"ORDER_TYPE_PURCHASE": 1,
		"ORDER_TYPE_SELL":     2,
	}
)

func (x OrderType) Enum() *OrderType {
	p := new(OrderType)
	*p = x
	return p
}

func (x OrderType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (OrderType) Descriptor() protoreflect.EnumDescriptor {
	return file_util_proto_enumTypes[0].Descriptor()
}

func (OrderType) Type() protoreflect.EnumType {
	return &file_util_proto_enumTypes[0]
}

func (x OrderType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use OrderType.Descriptor instead.
func (OrderType) EnumDescriptor() ([]byte, []int) {
	return file_util_proto_rawDescGZIP(), []int{0}
}

type ProcessState int32

const (
	ProcessState_NOT_USED_PROCESS_STATE  ProcessState = 0
	ProcessState_PROCESS_STATE_OPEN      ProcessState = 1
	ProcessState_PROCESS_STATE_LOCKED    ProcessState = 2
	ProcessState_PROCESS_STATE_FAILED    ProcessState = 3
	ProcessState_PROCESS_STATE_PROCESSED ProcessState = 4
)

// Enum value maps for ProcessState.
var (
	ProcessState_name = map[int32]string{
		0: "NOT_USED_PROCESS_STATE",
		1: "PROCESS_STATE_OPEN",
		2: "PROCESS_STATE_LOCKED",
		3: "PROCESS_STATE_FAILED",
		4: "PROCESS_STATE_PROCESSED",
	}
	ProcessState_value = map[string]int32{
		"NOT_USED_PROCESS_STATE":  0,
		"PROCESS_STATE_OPEN":      1,
		"PROCESS_STATE_LOCKED":    2,
		"PROCESS_STATE_FAILED":    3,
		"PROCESS_STATE_PROCESSED": 4,
	}
)

func (x ProcessState) Enum() *ProcessState {
	p := new(ProcessState)
	*p = x
	return p
}

func (x ProcessState) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ProcessState) Descriptor() protoreflect.EnumDescriptor {
	return file_util_proto_enumTypes[1].Descriptor()
}

func (ProcessState) Type() protoreflect.EnumType {
	return &file_util_proto_enumTypes[1]
}

func (x ProcessState) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ProcessState.Descriptor instead.
func (ProcessState) EnumDescriptor() ([]byte, []int) {
	return file_util_proto_rawDescGZIP(), []int{1}
}

type ProcessInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProcessState  ProcessState           `protobuf:"varint,1,opt,name=ProcessState,proto3,enum=order.ProcessState" json:"ProcessState,omitempty"`
	ProcessedAt   *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=ProcessedAt,proto3" json:"ProcessedAt,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProcessInfo) Reset() {
	*x = ProcessInfo{}
	mi := &file_util_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProcessInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProcessInfo) ProtoMessage() {}

func (x *ProcessInfo) ProtoReflect() protoreflect.Message {
	mi := &file_util_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProcessInfo.ProtoReflect.Descriptor instead.
func (*ProcessInfo) Descriptor() ([]byte, []int) {
	return file_util_proto_rawDescGZIP(), []int{0}
}

func (x *ProcessInfo) GetProcessState() ProcessState {
	if x != nil {
		return x.ProcessState
	}
	return ProcessState_NOT_USED_PROCESS_STATE
}

func (x *ProcessInfo) GetProcessedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.ProcessedAt
	}
	return nil
}

type LockLogRecord struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           string                 `protobuf:"bytes,1,opt,name=Key,proto3" json:"Key,omitempty"`
	MustHaveState []ProcessState         `protobuf:"varint,2,rep,packed,name=MustHaveState,proto3,enum=order.ProcessState" json:"MustHaveState,omitempty"`
	TargetState   ProcessState           `protobuf:"varint,3,opt,name=TargetState,proto3,enum=order.ProcessState" json:"TargetState,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LockLogRecord) Reset() {
	*x = LockLogRecord{}
	mi := &file_util_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LockLogRecord) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LockLogRecord) ProtoMessage() {}

func (x *LockLogRecord) ProtoReflect() protoreflect.Message {
	mi := &file_util_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LockLogRecord.ProtoReflect.Descriptor instead.
func (*LockLogRecord) Descriptor() ([]byte, []int) {
	return file_util_proto_rawDescGZIP(), []int{1}
}

func (x *LockLogRecord) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *LockLogRecord) GetMustHaveState() []ProcessState {
	if x != nil {
		return x.MustHaveState
	}
	return nil
}

func (x *LockLogRecord) GetTargetState() ProcessState {
	if x != nil {
		return x.TargetState
	}
	return ProcessState_NOT_USED_PROCESS_STATE
}

// The `Key` field represents the datastore key for the `Order` message.
// The `KeyPrefix` field is used to create a key for broker or smart contract logs (prefix + key = key for logs).
// The `IsNew` field identifies if the record linked to the key is new. This is helpful for recovery because
// both the rescanner and the recovery service might pick up the same record. When creating log records, if `IsNew` is true, the Key is sent
// through the channel for processing. Otherwise, it isn't sent, as an existing key signals the recovery service will handle it.
type Key struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           string                 `protobuf:"bytes,1,opt,name=Key,proto3" json:"Key,omitempty"`
	KeyPrefix     *string                `protobuf:"bytes,2,opt,name=KeyPrefix,proto3,oneof" json:"KeyPrefix,omitempty"`
	IsNew         *bool                  `protobuf:"varint,3,opt,name=IsNew,proto3,oneof" json:"IsNew,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Key) Reset() {
	*x = Key{}
	mi := &file_util_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Key) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Key) ProtoMessage() {}

func (x *Key) ProtoReflect() protoreflect.Message {
	mi := &file_util_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Key.ProtoReflect.Descriptor instead.
func (*Key) Descriptor() ([]byte, []int) {
	return file_util_proto_rawDescGZIP(), []int{2}
}

func (x *Key) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *Key) GetKeyPrefix() string {
	if x != nil && x.KeyPrefix != nil {
		return *x.KeyPrefix
	}
	return ""
}

func (x *Key) GetIsNew() bool {
	if x != nil && x.IsNew != nil {
		return *x.IsNew
	}
	return false
}

type InstanceID struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	InstanceID    string                 `protobuf:"bytes,1,opt,name=InstanceID,proto3" json:"InstanceID,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InstanceID) Reset() {
	*x = InstanceID{}
	mi := &file_util_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InstanceID) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InstanceID) ProtoMessage() {}

func (x *InstanceID) ProtoReflect() protoreflect.Message {
	mi := &file_util_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InstanceID.ProtoReflect.Descriptor instead.
func (*InstanceID) Descriptor() ([]byte, []int) {
	return file_util_proto_rawDescGZIP(), []int{3}
}

func (x *InstanceID) GetInstanceID() string {
	if x != nil {
		return x.InstanceID
	}
	return ""
}

var File_util_proto protoreflect.FileDescriptor

const file_util_proto_rawDesc = "" +
	"\n" +
	"\n" +
	"util.proto\x12\x05order\x1a\x1fgoogle/protobuf/timestamp.proto\"\x84\x01\n" +
	"\vProcessInfo\x127\n" +
	"\fProcessState\x18\x01 \x01(\x0e2\x13.order.ProcessStateR\fProcessState\x12<\n" +
	"\vProcessedAt\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\vProcessedAt\"\x93\x01\n" +
	"\rLockLogRecord\x12\x10\n" +
	"\x03Key\x18\x01 \x01(\tR\x03Key\x129\n" +
	"\rMustHaveState\x18\x02 \x03(\x0e2\x13.order.ProcessStateR\rMustHaveState\x125\n" +
	"\vTargetState\x18\x03 \x01(\x0e2\x13.order.ProcessStateR\vTargetState\"m\n" +
	"\x03Key\x12\x10\n" +
	"\x03Key\x18\x01 \x01(\tR\x03Key\x12!\n" +
	"\tKeyPrefix\x18\x02 \x01(\tH\x00R\tKeyPrefix\x88\x01\x01\x12\x19\n" +
	"\x05IsNew\x18\x03 \x01(\bH\x01R\x05IsNew\x88\x01\x01B\f\n" +
	"\n" +
	"_KeyPrefixB\b\n" +
	"\x06_IsNew\",\n" +
	"\n" +
	"InstanceID\x12\x1e\n" +
	"\n" +
	"InstanceID\x18\x01 \x01(\tR\n" +
	"InstanceID*R\n" +
	"\tOrderType\x12\x17\n" +
	"\x13NOT_USED_ORDER_TYPE\x10\x00\x12\x17\n" +
	"\x13ORDER_TYPE_PURCHASE\x10\x01\x12\x13\n" +
	"\x0fORDER_TYPE_SELL\x10\x02*\x93\x01\n" +
	"\fProcessState\x12\x1a\n" +
	"\x16NOT_USED_PROCESS_STATE\x10\x00\x12\x16\n" +
	"\x12PROCESS_STATE_OPEN\x10\x01\x12\x18\n" +
	"\x14PROCESS_STATE_LOCKED\x10\x02\x12\x18\n" +
	"\x14PROCESS_STATE_FAILED\x10\x03\x12\x1b\n" +
	"\x17PROCESS_STATE_PROCESSED\x10\x04B/Z-github.com/sologenic/com-fs-order-model;orderb\x06proto3"

var (
	file_util_proto_rawDescOnce sync.Once
	file_util_proto_rawDescData []byte
)

func file_util_proto_rawDescGZIP() []byte {
	file_util_proto_rawDescOnce.Do(func() {
		file_util_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_util_proto_rawDesc), len(file_util_proto_rawDesc)))
	})
	return file_util_proto_rawDescData
}

var file_util_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_util_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_util_proto_goTypes = []any{
	(OrderType)(0),                // 0: order.OrderType
	(ProcessState)(0),             // 1: order.ProcessState
	(*ProcessInfo)(nil),           // 2: order.ProcessInfo
	(*LockLogRecord)(nil),         // 3: order.LockLogRecord
	(*Key)(nil),                   // 4: order.Key
	(*InstanceID)(nil),            // 5: order.InstanceID
	(*timestamppb.Timestamp)(nil), // 6: google.protobuf.Timestamp
}
var file_util_proto_depIdxs = []int32{
	1, // 0: order.ProcessInfo.ProcessState:type_name -> order.ProcessState
	6, // 1: order.ProcessInfo.ProcessedAt:type_name -> google.protobuf.Timestamp
	1, // 2: order.LockLogRecord.MustHaveState:type_name -> order.ProcessState
	1, // 3: order.LockLogRecord.TargetState:type_name -> order.ProcessState
	4, // [4:4] is the sub-list for method output_type
	4, // [4:4] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_util_proto_init() }
func file_util_proto_init() {
	if File_util_proto != nil {
		return
	}
	file_util_proto_msgTypes[2].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_util_proto_rawDesc), len(file_util_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_util_proto_goTypes,
		DependencyIndexes: file_util_proto_depIdxs,
		EnumInfos:         file_util_proto_enumTypes,
		MessageInfos:      file_util_proto_msgTypes,
	}.Build()
	File_util_proto = out.File
	file_util_proto_goTypes = nil
	file_util_proto_depIdxs = nil
}
