syntax = "proto3";

package order;

import "google/protobuf/timestamp.proto";

option go_package = "github.com/sologenic/com-fs-order-model;order";

enum OrderType {
    NOT_USED_ORDER_TYPE = 0;
    ORDER_TYPE_PURCHASE = 1; // Avoid naming conflicts with PURCHASE in the action enum
    ORDER_TYPE_SELL = 2;
}

message ProcessInfo {
    ProcessState ProcessState = 1;
    google.protobuf.Timestamp ProcessedAt = 2;
}

enum ProcessState {
    NOT_USED_PROCESS_STATE = 0;
    PROCESS_STATE_OPEN = 1;
    PROCESS_STATE_LOCKED = 2;
    PROCESS_STATE_FAILED = 3;
    PROCESS_STATE_PROCESSED = 4;
}

message LockLogRecord {
    string Key = 1;
    repeated ProcessState MustHaveState = 2;
    ProcessState TargetState = 3;
}

message Key {
    string Key = 1;
    optional int64 Timestamp = 2;
}
