// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.31.0
// 	protoc        v4.24.3
// source: util.proto

package order

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type OrderType int32

const (
	OrderType_NOT_USED_ORDER_TYPE OrderType = 0
	OrderType_ORDER_TYPE_PURCHASE OrderType = 1 // Avoid naming conflicts with PURCHASE in the action enum
	OrderType_ORDER_TYPE_SELL     OrderType = 2
)

// Enum value maps for OrderType.
var (
	OrderType_name = map[int32]string{
		0: "NOT_USED_ORDER_TYPE",
		1: "ORDER_TYPE_PURCHASE",
		2: "ORDER_TYPE_SELL",
	}
	OrderType_value = map[string]int32{
		"NOT_USED_ORDER_TYPE": 0,
		"ORDER_TYPE_PURCHASE": 1,
		"ORDER_TYPE_SELL":     2,
	}
)

func (x OrderType) Enum() *OrderType {
	p := new(OrderType)
	*p = x
	return p
}

func (x OrderType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (OrderType) Descriptor() protoreflect.EnumDescriptor {
	return file_util_proto_enumTypes[0].Descriptor()
}

func (OrderType) Type() protoreflect.EnumType {
	return &file_util_proto_enumTypes[0]
}

func (x OrderType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use OrderType.Descriptor instead.
func (OrderType) EnumDescriptor() ([]byte, []int) {
	return file_util_proto_rawDescGZIP(), []int{0}
}

type ProcessState int32

const (
	ProcessState_NOT_USED_PROCESS_STATE  ProcessState = 0
	ProcessState_PROCESS_STATE_OPEN      ProcessState = 1
	ProcessState_PROCESS_STATE_LOCKED    ProcessState = 2
	ProcessState_PROCESS_STATE_FAILED    ProcessState = 3
	ProcessState_PROCESS_STATE_PROCESSED ProcessState = 4
)

// Enum value maps for ProcessState.
var (
	ProcessState_name = map[int32]string{
		0: "NOT_USED_PROCESS_STATE",
		1: "PROCESS_STATE_OPEN",
		2: "PROCESS_STATE_LOCKED",
		3: "PROCESS_STATE_FAILED",
		4: "PROCESS_STATE_PROCESSED",
	}
	ProcessState_value = map[string]int32{
		"NOT_USED_PROCESS_STATE":  0,
		"PROCESS_STATE_OPEN":      1,
		"PROCESS_STATE_LOCKED":    2,
		"PROCESS_STATE_FAILED":    3,
		"PROCESS_STATE_PROCESSED": 4,
	}
)

func (x ProcessState) Enum() *ProcessState {
	p := new(ProcessState)
	*p = x
	return p
}

func (x ProcessState) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ProcessState) Descriptor() protoreflect.EnumDescriptor {
	return file_util_proto_enumTypes[1].Descriptor()
}

func (ProcessState) Type() protoreflect.EnumType {
	return &file_util_proto_enumTypes[1]
}

func (x ProcessState) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ProcessState.Descriptor instead.
func (ProcessState) EnumDescriptor() ([]byte, []int) {
	return file_util_proto_rawDescGZIP(), []int{1}
}

type ProcesseInfo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ProcessState ProcessState           `protobuf:"varint,1,opt,name=ProcessState,proto3,enum=order.ProcessState" json:"ProcessState,omitempty"`
	ProcessedAt  *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=ProcessedAt,proto3" json:"ProcessedAt,omitempty"`
}

func (x *ProcesseInfo) Reset() {
	*x = ProcesseInfo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_util_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ProcesseInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProcesseInfo) ProtoMessage() {}

func (x *ProcesseInfo) ProtoReflect() protoreflect.Message {
	mi := &file_util_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProcesseInfo.ProtoReflect.Descriptor instead.
func (*ProcesseInfo) Descriptor() ([]byte, []int) {
	return file_util_proto_rawDescGZIP(), []int{0}
}

func (x *ProcesseInfo) GetProcessState() ProcessState {
	if x != nil {
		return x.ProcessState
	}
	return ProcessState_NOT_USED_PROCESS_STATE
}

func (x *ProcesseInfo) GetProcessedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.ProcessedAt
	}
	return nil
}

var File_util_proto protoreflect.FileDescriptor

var file_util_proto_rawDesc = []byte{
	0x0a, 0x0a, 0x75, 0x74, 0x69, 0x6c, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x05, 0x6f, 0x72,
	0x64, 0x65, 0x72, 0x1a, 0x1f, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x62, 0x75, 0x66, 0x2f, 0x74, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x22, 0x85, 0x01, 0x0a, 0x0c, 0x50, 0x72, 0x6f, 0x63, 0x65, 0x73, 0x73,
	0x65, 0x49, 0x6e, 0x66, 0x6f, 0x12, 0x37, 0x0a, 0x0c, 0x50, 0x72, 0x6f, 0x63, 0x65, 0x73, 0x73,
	0x53, 0x74, 0x61, 0x74, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x13, 0x2e, 0x6f, 0x72,
	0x64, 0x65, 0x72, 0x2e, 0x50, 0x72, 0x6f, 0x63, 0x65, 0x73, 0x73, 0x53, 0x74, 0x61, 0x74, 0x65,
	0x52, 0x0c, 0x50, 0x72, 0x6f, 0x63, 0x65, 0x73, 0x73, 0x53, 0x74, 0x61, 0x74, 0x65, 0x12, 0x3c,
	0x0a, 0x0b, 0x50, 0x72, 0x6f, 0x63, 0x65, 0x73, 0x73, 0x65, 0x64, 0x41, 0x74, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x54, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x52,
	0x0b, 0x50, 0x72, 0x6f, 0x63, 0x65, 0x73, 0x73, 0x65, 0x64, 0x41, 0x74, 0x2a, 0x52, 0x0a, 0x09,
	0x4f, 0x72, 0x64, 0x65, 0x72, 0x54, 0x79, 0x70, 0x65, 0x12, 0x17, 0x0a, 0x13, 0x4e, 0x4f, 0x54,
	0x5f, 0x55, 0x53, 0x45, 0x44, 0x5f, 0x4f, 0x52, 0x44, 0x45, 0x52, 0x5f, 0x54, 0x59, 0x50, 0x45,
	0x10, 0x00, 0x12, 0x17, 0x0a, 0x13, 0x4f, 0x52, 0x44, 0x45, 0x52, 0x5f, 0x54, 0x59, 0x50, 0x45,
	0x5f, 0x50, 0x55, 0x52, 0x43, 0x48, 0x41, 0x53, 0x45, 0x10, 0x01, 0x12, 0x13, 0x0a, 0x0f, 0x4f,
	0x52, 0x44, 0x45, 0x52, 0x5f, 0x54, 0x59, 0x50, 0x45, 0x5f, 0x53, 0x45, 0x4c, 0x4c, 0x10, 0x02,
	0x2a, 0x93, 0x01, 0x0a, 0x0c, 0x50, 0x72, 0x6f, 0x63, 0x65, 0x73, 0x73, 0x53, 0x74, 0x61, 0x74,
	0x65, 0x12, 0x1a, 0x0a, 0x16, 0x4e, 0x4f, 0x54, 0x5f, 0x55, 0x53, 0x45, 0x44, 0x5f, 0x50, 0x52,
	0x4f, 0x43, 0x45, 0x53, 0x53, 0x5f, 0x53, 0x54, 0x41, 0x54, 0x45, 0x10, 0x00, 0x12, 0x16, 0x0a,
	0x12, 0x50, 0x52, 0x4f, 0x43, 0x45, 0x53, 0x53, 0x5f, 0x53, 0x54, 0x41, 0x54, 0x45, 0x5f, 0x4f,
	0x50, 0x45, 0x4e, 0x10, 0x01, 0x12, 0x18, 0x0a, 0x14, 0x50, 0x52, 0x4f, 0x43, 0x45, 0x53, 0x53,
	0x5f, 0x53, 0x54, 0x41, 0x54, 0x45, 0x5f, 0x4c, 0x4f, 0x43, 0x4b, 0x45, 0x44, 0x10, 0x02, 0x12,
	0x18, 0x0a, 0x14, 0x50, 0x52, 0x4f, 0x43, 0x45, 0x53, 0x53, 0x5f, 0x53, 0x54, 0x41, 0x54, 0x45,
	0x5f, 0x46, 0x41, 0x49, 0x4c, 0x45, 0x44, 0x10, 0x03, 0x12, 0x1b, 0x0a, 0x17, 0x50, 0x52, 0x4f,
	0x43, 0x45, 0x53, 0x53, 0x5f, 0x53, 0x54, 0x41, 0x54, 0x45, 0x5f, 0x50, 0x52, 0x4f, 0x43, 0x45,
	0x53, 0x53, 0x45, 0x44, 0x10, 0x04, 0x42, 0x2f, 0x5a, 0x2d, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62,
	0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x73, 0x6f, 0x6c, 0x6f, 0x67, 0x65, 0x6e, 0x69, 0x63, 0x2f, 0x63,
	0x6f, 0x6d, 0x2d, 0x66, 0x73, 0x2d, 0x6f, 0x72, 0x64, 0x65, 0x72, 0x2d, 0x6d, 0x6f, 0x64, 0x65,
	0x6c, 0x3b, 0x6f, 0x72, 0x64, 0x65, 0x72, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_util_proto_rawDescOnce sync.Once
	file_util_proto_rawDescData = file_util_proto_rawDesc
)

func file_util_proto_rawDescGZIP() []byte {
	file_util_proto_rawDescOnce.Do(func() {
		file_util_proto_rawDescData = protoimpl.X.CompressGZIP(file_util_proto_rawDescData)
	})
	return file_util_proto_rawDescData
}

var file_util_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_util_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_util_proto_goTypes = []interface{}{
	(OrderType)(0),                // 0: order.OrderType
	(ProcessState)(0),             // 1: order.ProcessState
	(*ProcesseInfo)(nil),          // 2: order.ProcesseInfo
	(*timestamppb.Timestamp)(nil), // 3: google.protobuf.Timestamp
}
var file_util_proto_depIdxs = []int32{
	1, // 0: order.ProcesseInfo.ProcessState:type_name -> order.ProcessState
	3, // 1: order.ProcesseInfo.ProcessedAt:type_name -> google.protobuf.Timestamp
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_util_proto_init() }
func file_util_proto_init() {
	if File_util_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_util_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ProcesseInfo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_util_proto_rawDesc,
			NumEnums:      2,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_util_proto_goTypes,
		DependencyIndexes: file_util_proto_depIdxs,
		EnumInfos:         file_util_proto_enumTypes,
		MessageInfos:      file_util_proto_msgTypes,
	}.Build()
	File_util_proto = out.File
	file_util_proto_rawDesc = nil
	file_util_proto_goTypes = nil
	file_util_proto_depIdxs = nil
}
