// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.32.1
// source: util.proto

package order

import (
	order_properties "github.com/sologenic/com-fs-utils-lib/models/order-properties"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type LockLogRecord struct {
	state         protoimpl.MessageState          `protogen:"open.v1"`
	Key           string                          `protobuf:"bytes,1,opt,name=Key,proto3" json:"Key,omitempty"`
	MustHaveState []order_properties.ProcessState `protobuf:"varint,2,rep,packed,name=MustHaveState,proto3,enum=orderproperties.ProcessState" json:"MustHaveState,omitempty"`
	TargetState   order_properties.ProcessState   `protobuf:"varint,3,opt,name=TargetState,proto3,enum=orderproperties.ProcessState" json:"TargetState,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LockLogRecord) Reset() {
	*x = LockLogRecord{}
	mi := &file_util_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LockLogRecord) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LockLogRecord) ProtoMessage() {}

func (x *LockLogRecord) ProtoReflect() protoreflect.Message {
	mi := &file_util_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LockLogRecord.ProtoReflect.Descriptor instead.
func (*LockLogRecord) Descriptor() ([]byte, []int) {
	return file_util_proto_rawDescGZIP(), []int{0}
}

func (x *LockLogRecord) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *LockLogRecord) GetMustHaveState() []order_properties.ProcessState {
	if x != nil {
		return x.MustHaveState
	}
	return nil
}

func (x *LockLogRecord) GetTargetState() order_properties.ProcessState {
	if x != nil {
		return x.TargetState
	}
	return order_properties.ProcessState(0)
}

// The `Key` field represents the datastore key for the `Order` message.
// The `KeyPrefix` field is used to create a key for broker or smart contract logs (prefix + key = key for logs).
// The `IsNew` field identifies if the record linked to the key is new. This is helpful for recovery because
// both the rescanner and the recovery service might pick up the same record. When creating log records, if `IsNew` is true, the Key is sent
// through the channel for processing. Otherwise, it isn't sent, as an existing key signals the recovery service will handle it.
type Key struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           string                 `protobuf:"bytes,1,opt,name=Key,proto3" json:"Key,omitempty"`
	KeyPrefix     *string                `protobuf:"bytes,2,opt,name=KeyPrefix,proto3,oneof" json:"KeyPrefix,omitempty"`
	IsNew         *bool                  `protobuf:"varint,3,opt,name=IsNew,proto3,oneof" json:"IsNew,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Key) Reset() {
	*x = Key{}
	mi := &file_util_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Key) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Key) ProtoMessage() {}

func (x *Key) ProtoReflect() protoreflect.Message {
	mi := &file_util_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Key.ProtoReflect.Descriptor instead.
func (*Key) Descriptor() ([]byte, []int) {
	return file_util_proto_rawDescGZIP(), []int{1}
}

func (x *Key) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *Key) GetKeyPrefix() string {
	if x != nil && x.KeyPrefix != nil {
		return *x.KeyPrefix
	}
	return ""
}

func (x *Key) GetIsNew() bool {
	if x != nil && x.IsNew != nil {
		return *x.IsNew
	}
	return false
}

type InstanceID struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	InstanceID    string                 `protobuf:"bytes,1,opt,name=InstanceID,proto3" json:"InstanceID,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InstanceID) Reset() {
	*x = InstanceID{}
	mi := &file_util_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InstanceID) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InstanceID) ProtoMessage() {}

func (x *InstanceID) ProtoReflect() protoreflect.Message {
	mi := &file_util_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InstanceID.ProtoReflect.Descriptor instead.
func (*InstanceID) Descriptor() ([]byte, []int) {
	return file_util_proto_rawDescGZIP(), []int{2}
}

func (x *InstanceID) GetInstanceID() string {
	if x != nil {
		return x.InstanceID
	}
	return ""
}

var File_util_proto protoreflect.FileDescriptor

const file_util_proto_rawDesc = "" +
	"\n" +
	"\n" +
	"util.proto\x12\x05order\x1aIsologenic/com-fs-utils-lib/models/order-properties/order-properties.proto\"\xa7\x01\n" +
	"\rLockLogRecord\x12\x10\n" +
	"\x03Key\x18\x01 \x01(\tR\x03Key\x12C\n" +
	"\rMustHaveState\x18\x02 \x03(\x0e2\x1d.orderproperties.ProcessStateR\rMustHaveState\x12?\n" +
	"\vTargetState\x18\x03 \x01(\x0e2\x1d.orderproperties.ProcessStateR\vTargetState\"m\n" +
	"\x03Key\x12\x10\n" +
	"\x03Key\x18\x01 \x01(\tR\x03Key\x12!\n" +
	"\tKeyPrefix\x18\x02 \x01(\tH\x00R\tKeyPrefix\x88\x01\x01\x12\x19\n" +
	"\x05IsNew\x18\x03 \x01(\bH\x01R\x05IsNew\x88\x01\x01B\f\n" +
	"\n" +
	"_KeyPrefixB\b\n" +
	"\x06_IsNew\",\n" +
	"\n" +
	"InstanceID\x12\x1e\n" +
	"\n" +
	"InstanceID\x18\x01 \x01(\tR\n" +
	"InstanceIDB/Z-github.com/sologenic/com-fs-order-model;orderb\x06proto3"

var (
	file_util_proto_rawDescOnce sync.Once
	file_util_proto_rawDescData []byte
)

func file_util_proto_rawDescGZIP() []byte {
	file_util_proto_rawDescOnce.Do(func() {
		file_util_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_util_proto_rawDesc), len(file_util_proto_rawDesc)))
	})
	return file_util_proto_rawDescData
}

var file_util_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_util_proto_goTypes = []any{
	(*LockLogRecord)(nil),              // 0: order.LockLogRecord
	(*Key)(nil),                        // 1: order.Key
	(*InstanceID)(nil),                 // 2: order.InstanceID
	(order_properties.ProcessState)(0), // 3: orderproperties.ProcessState
}
var file_util_proto_depIdxs = []int32{
	3, // 0: order.LockLogRecord.MustHaveState:type_name -> orderproperties.ProcessState
	3, // 1: order.LockLogRecord.TargetState:type_name -> orderproperties.ProcessState
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_util_proto_init() }
func file_util_proto_init() {
	if File_util_proto != nil {
		return
	}
	file_util_proto_msgTypes[1].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_util_proto_rawDesc), len(file_util_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_util_proto_goTypes,
		DependencyIndexes: file_util_proto_depIdxs,
		MessageInfos:      file_util_proto_msgTypes,
	}.Build()
	File_util_proto = out.File
	file_util_proto_goTypes = nil
	file_util_proto_depIdxs = nil
}
