// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v1.181.2
//   protoc               v5.29.3
// source: sologenic/com-fs-order-model/attestation-grpc.proto

/* eslint-disable */
import Long from "long";
import _m0 from "protobufjs/minimal";
import { Empty } from "../../google/protobuf/empty";
import { Network, networkFromJSON, networkToJSON } from "../com-fs-utils-lib/models/metadata/metadata";
import { Attestation, Attestations } from "./attestation";

export const protobufPackage = "order";

export interface AttestationID {
  Network: Network;
  SmartContractAddr: string;
  Denom: string;
  /** Default will return the latest attestation */
  BlockHeight?: number | undefined;
}

export interface AttestationQuery {
  Network: Network;
  SmartContractAddr: string;
  Denom: string;
  Offset?: number | undefined;
}

function createBaseAttestationID(): AttestationID {
  return { Network: 0, SmartContractAddr: "", Denom: "", BlockHeight: undefined };
}

export const AttestationID = {
  encode(message: AttestationID, writer: _m0.Writer = _m0.Writer.create()): _m0.Writer {
    if (message.Network !== 0) {
      writer.uint32(8).int32(message.Network);
    }
    if (message.SmartContractAddr !== "") {
      writer.uint32(18).string(message.SmartContractAddr);
    }
    if (message.Denom !== "") {
      writer.uint32(26).string(message.Denom);
    }
    if (message.BlockHeight !== undefined) {
      writer.uint32(32).int64(message.BlockHeight);
    }
    return writer;
  },

  decode(input: _m0.Reader | Uint8Array, length?: number): AttestationID {
    const reader = input instanceof _m0.Reader ? input : _m0.Reader.create(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseAttestationID();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1:
          if (tag !== 8) {
            break;
          }

          message.Network = reader.int32() as any;
          continue;
        case 2:
          if (tag !== 18) {
            break;
          }

          message.SmartContractAddr = reader.string();
          continue;
        case 3:
          if (tag !== 26) {
            break;
          }

          message.Denom = reader.string();
          continue;
        case 4:
          if (tag !== 32) {
            break;
          }

          message.BlockHeight = longToNumber(reader.int64() as Long);
          continue;
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skipType(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): AttestationID {
    return {
      Network: isSet(object.Network) ? networkFromJSON(object.Network) : 0,
      SmartContractAddr: isSet(object.SmartContractAddr) ? globalThis.String(object.SmartContractAddr) : "",
      Denom: isSet(object.Denom) ? globalThis.String(object.Denom) : "",
      BlockHeight: isSet(object.BlockHeight) ? globalThis.Number(object.BlockHeight) : undefined,
    };
  },

  toJSON(message: AttestationID): unknown {
    const obj: any = {};
    if (message.Network !== 0) {
      obj.Network = networkToJSON(message.Network);
    }
    if (message.SmartContractAddr !== "") {
      obj.SmartContractAddr = message.SmartContractAddr;
    }
    if (message.Denom !== "") {
      obj.Denom = message.Denom;
    }
    if (message.BlockHeight !== undefined) {
      obj.BlockHeight = Math.round(message.BlockHeight);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<AttestationID>, I>>(base?: I): AttestationID {
    return AttestationID.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<AttestationID>, I>>(object: I): AttestationID {
    const message = createBaseAttestationID();
    message.Network = object.Network ?? 0;
    message.SmartContractAddr = object.SmartContractAddr ?? "";
    message.Denom = object.Denom ?? "";
    message.BlockHeight = object.BlockHeight ?? undefined;
    return message;
  },
};

function createBaseAttestationQuery(): AttestationQuery {
  return { Network: 0, SmartContractAddr: "", Denom: "", Offset: undefined };
}

export const AttestationQuery = {
  encode(message: AttestationQuery, writer: _m0.Writer = _m0.Writer.create()): _m0.Writer {
    if (message.Network !== 0) {
      writer.uint32(8).int32(message.Network);
    }
    if (message.SmartContractAddr !== "") {
      writer.uint32(18).string(message.SmartContractAddr);
    }
    if (message.Denom !== "") {
      writer.uint32(26).string(message.Denom);
    }
    if (message.Offset !== undefined) {
      writer.uint32(40).int32(message.Offset);
    }
    return writer;
  },

  decode(input: _m0.Reader | Uint8Array, length?: number): AttestationQuery {
    const reader = input instanceof _m0.Reader ? input : _m0.Reader.create(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseAttestationQuery();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1:
          if (tag !== 8) {
            break;
          }

          message.Network = reader.int32() as any;
          continue;
        case 2:
          if (tag !== 18) {
            break;
          }

          message.SmartContractAddr = reader.string();
          continue;
        case 3:
          if (tag !== 26) {
            break;
          }

          message.Denom = reader.string();
          continue;
        case 5:
          if (tag !== 40) {
            break;
          }

          message.Offset = reader.int32();
          continue;
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skipType(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): AttestationQuery {
    return {
      Network: isSet(object.Network) ? networkFromJSON(object.Network) : 0,
      SmartContractAddr: isSet(object.SmartContractAddr) ? globalThis.String(object.SmartContractAddr) : "",
      Denom: isSet(object.Denom) ? globalThis.String(object.Denom) : "",
      Offset: isSet(object.Offset) ? globalThis.Number(object.Offset) : undefined,
    };
  },

  toJSON(message: AttestationQuery): unknown {
    const obj: any = {};
    if (message.Network !== 0) {
      obj.Network = networkToJSON(message.Network);
    }
    if (message.SmartContractAddr !== "") {
      obj.SmartContractAddr = message.SmartContractAddr;
    }
    if (message.Denom !== "") {
      obj.Denom = message.Denom;
    }
    if (message.Offset !== undefined) {
      obj.Offset = Math.round(message.Offset);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<AttestationQuery>, I>>(base?: I): AttestationQuery {
    return AttestationQuery.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<AttestationQuery>, I>>(object: I): AttestationQuery {
    const message = createBaseAttestationQuery();
    message.Network = object.Network ?? 0;
    message.SmartContractAddr = object.SmartContractAddr ?? "";
    message.Denom = object.Denom ?? "";
    message.Offset = object.Offset ?? undefined;
    return message;
  },
};

export interface AttestationService {
  Create(request: Attestation): Promise<Empty>;
  Update(request: Attestation): Promise<Empty>;
  Get(request: AttestationID): Promise<Attestation>;
  List(request: AttestationQuery): Promise<Attestations>;
}

export const AttestationServiceServiceName = "order.AttestationService";
export class AttestationServiceClientImpl implements AttestationService {
  private readonly rpc: Rpc;
  private readonly service: string;
  constructor(rpc: Rpc, opts?: { service?: string }) {
    this.service = opts?.service || AttestationServiceServiceName;
    this.rpc = rpc;
    this.Create = this.Create.bind(this);
    this.Update = this.Update.bind(this);
    this.Get = this.Get.bind(this);
    this.List = this.List.bind(this);
  }
  Create(request: Attestation): Promise<Empty> {
    const data = Attestation.encode(request).finish();
    const promise = this.rpc.request(this.service, "Create", data);
    return promise.then((data) => Empty.decode(_m0.Reader.create(data)));
  }

  Update(request: Attestation): Promise<Empty> {
    const data = Attestation.encode(request).finish();
    const promise = this.rpc.request(this.service, "Update", data);
    return promise.then((data) => Empty.decode(_m0.Reader.create(data)));
  }

  Get(request: AttestationID): Promise<Attestation> {
    const data = AttestationID.encode(request).finish();
    const promise = this.rpc.request(this.service, "Get", data);
    return promise.then((data) => Attestation.decode(_m0.Reader.create(data)));
  }

  List(request: AttestationQuery): Promise<Attestations> {
    const data = AttestationQuery.encode(request).finish();
    const promise = this.rpc.request(this.service, "List", data);
    return promise.then((data) => Attestations.decode(_m0.Reader.create(data)));
  }
}

interface Rpc {
  request(service: string, method: string, data: Uint8Array): Promise<Uint8Array>;
}

type Builtin = Date | Function | Uint8Array | string | number | boolean | undefined;

export type DeepPartial<T> = T extends Builtin ? T
  : T extends globalThis.Array<infer U> ? globalThis.Array<DeepPartial<U>>
  : T extends ReadonlyArray<infer U> ? ReadonlyArray<DeepPartial<U>>
  : T extends {} ? { [K in keyof T]?: DeepPartial<T[K]> }
  : Partial<T>;

type KeysOfUnion<T> = T extends T ? keyof T : never;
export type Exact<P, I extends P> = P extends Builtin ? P
  : P & { [K in keyof P]: Exact<P[K], I[K]> } & { [K in Exclude<keyof I, KeysOfUnion<P>>]: never };

function longToNumber(long: Long): number {
  if (long.gt(globalThis.Number.MAX_SAFE_INTEGER)) {
    throw new globalThis.Error("Value is larger than Number.MAX_SAFE_INTEGER");
  }
  if (long.lt(globalThis.Number.MIN_SAFE_INTEGER)) {
    throw new globalThis.Error("Value is smaller than Number.MIN_SAFE_INTEGER");
  }
  return long.toNumber();
}

if (_m0.util.Long !== Long) {
  _m0.util.Long = Long as any;
  _m0.configure();
}

function isSet(value: any): boolean {
  return value !== null && value !== undefined;
}
