// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v1.181.2
//   protoc               v5.29.1
// source: sologenic/com-fs-order-model/broker-grpc.proto

/* eslint-disable */
import _m0 from "protobufjs/minimal";
import { Empty } from "../../google/protobuf/empty";
import { BrokerOrderDetails, BrokerOrderDetailsList } from "./broker";
import { InstanceID, Key, LockLogRecord } from "./util";

export const protobufPackage = "order";

/** Broker Trade Update Log */
export interface BrokerLogService {
  Create(request: BrokerOrderDetails): Promise<Key>;
  /** Transaction */
  SetLock(request: LockLogRecord): Promise<BrokerOrderDetails>;
  /** For recovery, get all unprocessed Broker Logs. Unprocessed logs are logs that are in the states `OPEN` or `LOCKED`. */
  GetAllUnprocessed(request: InstanceID): Promise<BrokerOrderDetailsList>;
  /** Starting point for rescanner */
  GetLatest(request: Empty): Promise<BrokerOrderDetails>;
}

export const BrokerLogServiceServiceName = "order.BrokerLogService";
export class BrokerLogServiceClientImpl implements BrokerLogService {
  private readonly rpc: Rpc;
  private readonly service: string;
  constructor(rpc: Rpc, opts?: { service?: string }) {
    this.service = opts?.service || BrokerLogServiceServiceName;
    this.rpc = rpc;
    this.Create = this.Create.bind(this);
    this.SetLock = this.SetLock.bind(this);
    this.GetAllUnprocessed = this.GetAllUnprocessed.bind(this);
    this.GetLatest = this.GetLatest.bind(this);
  }
  Create(request: BrokerOrderDetails): Promise<Key> {
    const data = BrokerOrderDetails.encode(request).finish();
    const promise = this.rpc.request(this.service, "Create", data);
    return promise.then((data) => Key.decode(_m0.Reader.create(data)));
  }

  SetLock(request: LockLogRecord): Promise<BrokerOrderDetails> {
    const data = LockLogRecord.encode(request).finish();
    const promise = this.rpc.request(this.service, "SetLock", data);
    return promise.then((data) => BrokerOrderDetails.decode(_m0.Reader.create(data)));
  }

  GetAllUnprocessed(request: InstanceID): Promise<BrokerOrderDetailsList> {
    const data = InstanceID.encode(request).finish();
    const promise = this.rpc.request(this.service, "GetAllUnprocessed", data);
    return promise.then((data) => BrokerOrderDetailsList.decode(_m0.Reader.create(data)));
  }

  GetLatest(request: Empty): Promise<BrokerOrderDetails> {
    const data = Empty.encode(request).finish();
    const promise = this.rpc.request(this.service, "GetLatest", data);
    return promise.then((data) => BrokerOrderDetails.decode(_m0.Reader.create(data)));
  }
}

interface Rpc {
  request(service: string, method: string, data: Uint8Array): Promise<Uint8Array>;
}
